package:
  name: acl
  version: 2.3.2
  epoch: 2
  description: "access control list utilities"
  copyright:
    - license: LGPL-2.1-or-later AND GPL-2.0-or-later

environment:
  contents:
    packages:
      - attr-dev
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gettext-dev
      - libtool
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.savannah.nongnu.org/git/acl.git
      tag: v${{package.version}}
      expected-commit: cefe1c17f20448b7a0ca53ac9cf8a46d444a8cca

  - runs: |
      ./autogen.sh

  - runs: |
      ./configure \
         --prefix=/usr \
         --libdir=/lib \
         --libexecdir=/usr/libexec

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/lib
      mv "${{targets.destdir}}"/lib/pkgconfig "${{targets.destdir}}"/usr/lib/

  - uses: strip

subpackages:
  - name: "acl-dev"
    description: "headers for libacl"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - acl

  - name: "libacl1"
    description: "library for managing access control lists"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/lib
          mv "${{targets.destdir}}"/lib/libacl.so.* "${{targets.subpkgdir}}"/lib/

update:
  enabled: true
  release-monitor:
    identifier: 16

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        getfacl --version
        setfacl --version
