package:
  name: alsa-lib
  version: 1.2.12
  epoch: 1
  description: Advanced Linux Sound Architecture (ALSA) library
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - linux-headers

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/alsa-project/alsa-lib.git
      tag: v${{package.version}}
      expected-commit: 34422861f5549aee3e9df9fd8240d10b530d9abd

  - runs: |
      libtoolize --force --copy --automake
      aclocal
      autoheader
      automake --foreign --copy --add-missing
      autoconf

  - uses: autoconf/configure
    with:
      opts: |
        --disable-python \
        --disable-static \
        --disable-resmgr \
        --enable-rawmidi \
        --enable-seq \
        --enable-aload \
        --disable-dependency-tracking

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: alsa-lib-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - alsa-lib

update:
  enabled: true
  github:
    identifier: alsa-project/alsa-lib
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        aserver --help
