package:
  name: authservice
  version: 1.0.2
  epoch: 0
  description: Move OIDC token acquisition out of your app code and into the Istio mesh
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e99c3ebbe5a7890c84358e40ece9226a48470a02
      repository: https://github.com/istio-ecosystem/authservice
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd
      ldflags: -s -w
      output: authservice

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}/usr/local/bin"
          ln -s /usr/bin/authservice "${{targets.contextdir}}/usr/local/bin/authservice"

update:
  enabled: true
  github:
    identifier: istio-ecosystem/authservice
    strip-prefix: v

test:
  pipeline:
    - runs: |
        authservice -v
