package:
  name: aws-privateca-issuer
  version: 1.3.0
  epoch: 0
  description: Addon for cert-manager that issues certificates using AWS ACM PCA.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6e56d27d70fe49ad04b1444915327d043f8254da
      repository: https://github.com/cert-manager/aws-privateca-issuer
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: |
        -X=github.com/cert-manager/acm-pca-issuer/internal/version.Version=${{package.version}}
        -X github.com/cert-manager/aws-privateca-issuer/pkg/api/injections.PlugInVersion=${{package.version}}
      output: manager
      packages: .

subpackages:
  - name: aws-privateca-issuer-compat
    pipeline:
      - runs: |
          # Symlink the binary from usr/bin to /
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/manager ${{targets.subpkgdir}}/manager

update:
  enabled: true
  github:
    identifier: cert-manager/aws-privateca-issuer
    strip-prefix: v

test:
  pipeline:
    - name: "Verify Installation"
      runs: |
        manager --help
