package:
  name: aws-c-http
  version: 0.8.10
  epoch: 0
  description: AWS C99 implementation of the HTTP/1.1 and HTTP/2 specifications
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - aws-c-cal-dev
      - aws-c-common-dev
      - aws-c-compression-dev
      - aws-c-io-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - openssf-compiler-options
      - s2n-tls-dev
      - samurai

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6068653e1d582bd8e7d1c9f81f86beaf10444e3d
      repository: https://github.com/awslabs/aws-c-http
      tag: v${{package.version}}

  - runs: |
      if [ "$CBUILD" != "$CHOST" ]; then
        CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
      fi
      CFLAGS="$CFLAGS -flto=auto" \
      CXXFLAGS="$CXXFLAGS -flto=auto" \
      cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_TESTING="$(want_check && echo ON || echo OFF)" \
        $CMAKE_CROSSOPTS
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: aws-c-http-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/aws-c-http "${{targets.subpkgdir}}"/usr/lib/
    dependencies:
      runtime:
        - aws-c-http
    description: aws-c-http dev

update:
  enabled: true
  github:
    identifier: awslabs/aws-c-http
    strip-prefix: v
    use-tag: true
