package:
  name: azcopy
  version: 10.26.0
  epoch: 1
  description: The new Azure Storage data transfer utility
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Azure/azure-storage-azcopy
      tag: v${{package.version}}
      expected-commit: 0054ae0d9938c6f6f5f1d2ef107bfcbb5a6f148b

  - uses: go/build
    with:
      packages: .
      output: azcopy
      go-package: go

update:
  enabled: true
  github:
    identifier: Azure/azure-storage-azcopy
    strip-prefix: v

test:
  pipeline:
    - runs: |
        azcopy --version
