package:
  name: bazel-7
  version: 7.3.1
  epoch: 0
  description: Bazel is an open-source build and test tool
  resources:
    cpu: 16
    memory: 16Gi
  dependencies:
    provides:
      - bazel=${{package.full-version}}
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - libstdc++-6
      - libstdc++-6-dev
      - openjdk-21
      - python3
      - zip

pipeline:
  - uses: fetch
    with:
      expected-sha256: f0501f90c9fc74cd6933dbdc59e17b8d6272d6c09f8b8e3c428985c5897147c7
      uri: https://github.com/bazelbuild/bazel/releases/download/${{package.version}}/bazel-${{package.version}}-dist.zip
      extract: false
      delete: false

  - runs: unzip bazel-${{package.version}}-dist.zip

  - runs: |
      mkdir -p $HOME/.cache/bazel/_bazel_root
      export JAVA_HOME=/usr/lib/jvm/java-21-openjdk

      EMBED_LABEL=${{package.version}}-${{package.epoch}} \
        EXTRA_BAZEL_ARGS=--tool_java_runtime_version=local_jdk \
        ./compile.sh
      ./output/bazel clean --expunge
      mkdir -p ${{targets.destdir}}/usr/bin
      cp ./output/bazel ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  github:
    identifier: bazelbuild/bazel
    strip-prefix: v
    tag-filter: "7."

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        bazel --version
