package:
  name: bazelisk
  version: 1.21.0
  epoch: 0
  description: A user-friendly launcher for Bazel.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bazelbuild/bazelisk
      expected-commit: 22bef8d52f0fde6750720c476cc8436da8d779c2
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      output: bazelisk
      ldflags: -X github.com/bazelbuild/bazelisk/core.BazeliskVersion=${{package.version}}

  - uses: strip

subpackages:
  - name: bazelisk-default
    pipeline:
      - runs: |
          # Configure bazelisk as bazel
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          ln -sf /usr/bin/bazelisk ${{targets.subpkgdir}}/usr/bin/bazel
    dependencies:
      runtime:
        - bazelisk

update:
  enabled: true
  github:
    identifier: bazelbuild/bazelisk
    strip-prefix: v
