package:
  name: bird
  version: 2.15.1
  epoch: 1
  description: BIRD Internet Routing Daemon
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - libssh-dev
      - linux-headers
      - ncurses-dev
      - readline-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.nic.cz/labs/bird.git
      tag: v${{package.version}}
      expected-commit: 0b684a43bd7ce4a32c9cd7754b88286bcd1815bb

  - runs: |
      autoreconf -fi

  - uses: autoconf/configure
    with:
      opts: |
        --prefix=/usr \
        --sysconfdir=/etc \
        --mandir=/usr/share/man \
        --localstatedir=/var \
        --runstatedir=/run \
        --enable-libssh

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 192

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        bird --version
