package:
  name: brotli
  version: 1.1.0
  epoch: 4
  description: "a generic lossless compression algorithm"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - libtool
      - openssf-compiler-options
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/google/brotli.git
      tag: v${{package.version}}
      expected-commit: ed738e842d2fbdf2d6459e39267a633c4a9b2f5d

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: "brotli-dev"
    description: "headers for brotli"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - brotli

  - name: "libbrotlicommon1"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libbrotlicommon.so.* "${{targets.subpkgdir}}"/usr/lib/

  - name: "libbrotlienc1"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libbrotlienc.so.* "${{targets.subpkgdir}}"/usr/lib/

  - name: "libbrotlidec1"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libbrotlidec.so.* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  ignore-regex-patterns:
    - "^dev\\/null$"
  github:
    identifier: google/brotli
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        brotli --version
