package:
  name: buildah
  version: 1.37.3
  description: "A tool that facilitates building OCI images"
  epoch: 0
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - gpgme-dev
      - libassuan-dev
      - libgpg-error-dev
      - libseccomp-dev
      - libseccomp-static

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containers/buildah
      tag: v${{package.version}}
      expected-commit: 956095ee1caa2597a134168c076e48cd3fa790aa

  - uses: go/bump
    with:
      deps: github.com/opencontainers/runc@v1.2.0-rc.3

  - runs: |
      make
      make install PREFIX=${{targets.destdir}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: containers/buildah
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - name: Verify buildah installation
      runs: |
        buildah version | grep ${{package.version}} || exit 1
