package:
  name: busybox
  version: 1.36.1
  epoch: 11
  description: "swiss-army knife for embedded systems"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    provider-priority: 10
  scriptlets:
    trigger:
      paths:
        - /bin
        - /sbin
        - /usr/bin
        - /usr/sbin
      script: |
        #!/bin/busybox sh
        /bin/busybox --install -s

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: mangled-package-version

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssf-compiler-options
      - perl # provides pod2html/pod2text

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1a64f6a20aaf6ea4dbba68bbfa8cc1ab7e5c57c4
      repository: https://git.busybox.net/busybox
      tag: ${{vars.mangled-package-version}}
      cherry-picks: |
        master/5dcc443dba039b305a510c01883e9f34e42656ae: CVE-2021-42380 awk: fix use-after-realloc
        master/84ff1825dd82e8de45020e3def34d1430d8e5a99: awk: fix splitting with default FS
        # CVE from http://lists.busybox.net/pipermail/busybox/2024-May/090761.html
        master/0256e00a9d077588bd3a39f5a1ef7e2eaa2911e4: CVE-2023-42364 CVE-2023-42365 awk: fix precedence of = relative to ==
        master/5f84c5633663f6ee8c9cc3a4608b86d4b56b39d6: awk: fix backslash handling in sub() builtins
        master/fb08d43d44d1fea1f741fafb9aa7e1958a5f69aa: CVE-2023-42363 awk: fix use after free
        # CVE number comes from ubuntu debian/patches/CVE-2022-48174.patch
        master/d417193cf37ca1005830d7e16f5fa7e1d8a44209: CVE-2022-48174 shell: avoid segfault on ${0::0/0~09J}.
        # fix regression made in 0256e00a9d077588bd3a39f5a1ef7e2eaa2911e4
        master/38335df9e9f45378c3407defd38b5b610578bdda: awk: restore assignment precedence to be lower than ternary

  - uses: patch
    with:
      patches: CVE-2022-28391-1.patch CVE-2022-28391-2.patch

  # from aports.git busybox/0037-awk.c-fix-CVE-2023-42366-bug-15874.patch
  # http://lists.busybox.net/pipermail/busybox/2024-March/090654.html
  - uses: patch
    with:
      patches: 0037-awk.c-fix-CVE-2023-42366-bug-15874.patch

  - name: Configure
    runs: |
      cp busyboxconfig .config

  - runs: |
      make CC="${{host.triplet.gnu}}-gcc" V=1 -j$(nproc)

  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"/usr/sbin
      mkdir -p "${{targets.destdir}}"/usr/bin
      mkdir -p "${{targets.destdir}}"/tmp
      mkdir -p "${{targets.destdir}}"/var/cache/misc
      mkdir -p "${{targets.destdir}}"/bin
      mkdir -p "${{targets.destdir}}"/sbin
      mkdir -p "${{targets.destdir}}"/etc
      mkdir -p "${{targets.destdir}}"/usr/share/man/man1
      chmod 1777 "${{targets.destdir}}"/tmp
      install -m755 busybox "${{targets.destdir}}"/bin/busybox
      install -m644 securetty "${{targets.destdir}}"/etc/securetty

      mkdir -p "${{targets.destdir}}"/etc/busybox-paths.d
      ./busybox --list-path > "${{targets.destdir}}"/etc/busybox-paths.d/busybox

subpackages:
  - name: busybox-full
    dependencies:
      provides:
        - busybox=${{package.full-version}}
      provider-priority: 5
    options:
      no-commands: true
    pipeline:
      - name: Configure
        runs: |
          cp busyboxconfig-full .config
      - runs: |
          make CC="${{host.triplet.gnu}}-gcc" V=1 -j$(nproc)
      - name: Install
        runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/sbin
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mkdir -p "${{targets.subpkgdir}}"/tmp
          mkdir -p "${{targets.subpkgdir}}"/var/cache/misc
          mkdir -p "${{targets.subpkgdir}}"/bin
          mkdir -p "${{targets.subpkgdir}}"/sbin
          mkdir -p "${{targets.subpkgdir}}"/etc
          mkdir -p "${{targets.subpkgdir}}"/usr/share/man/man1
          chmod 1777 "${{targets.subpkgdir}}"/tmp
          install -m755 busybox "${{targets.subpkgdir}}"/bin/busybox
          install -m644 securetty "${{targets.subpkgdir}}"/etc/securetty

          mkdir -p "${{targets.subpkgdir}}"/etc/busybox-paths.d
          ./busybox --list-path > "${{targets.subpkgdir}}"/etc/busybox-paths.d/busybox-full
    scriptlets:
      trigger:
        paths:
          - /bin
          - /sbin
          - /usr/bin
          - /usr/sbin
        script: |
          #!/bin/busybox sh
          /bin/busybox --install -s
    test:
      environment:
        contents:
          packages:
            - wolfi-base
      pipeline:
        - runs: |
            busybox --help
            busybox --list-full >full.txt
            # These programs are expected to be present
            for p in nc netcat wget; do
                if ! grep "bin/$p" full.txt; then
                    echo "$p is not present in busybox --list-full output"
                    exit 1
                fi
                "$p" --help ||
                  { echo "$p --help exited $?. expected pass"; exit 1; }
            done

test:
  pipeline:
    - uses: test/hardening-check
      with:
        args: --nocfprotection
    - runs: |
        busybox --help
        busybox --list-full >full.txt

        # These programs have been intentionally removed from default busybox
        for p in nc netcat wget; do
            if grep "bin/$p" full.txt; then
                echo "Found '$p' in list-full output"
                exit 1
            fi
            command -v "$p" &&
              { echo "command '$p' is present. It should not be."; exit 1; }
        done
    - name: "awk = and ?: precedence"
      runs: |
        found=$(awk 'BEGIN { a=0?"bug":"ok"; print a}')
        [ "$found" = "ok" ] &&
          echo "PASS: ternary precedence" ||
          { echo "FAIL: ternary precedence" ; exit 1; }

update:
  enabled: true
  release-monitor:
    identifier: 230
