package:
  name: caddy
  version: 2.8.4
  epoch: 3
  description: Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7088605cc11c52c2777ab613dfc5c2a9816006e4
      repository: https://github.com/caddyserver/caddy
      tag: v${{package.version}}

  - runs: |
      install -m644 -D "./Caddyfile" "${{targets.destdir}}/etc/caddy/Caddyfile"
      install -m755 -D "./index.html" "${{targets.destdir}}/usr/share/caddy/index.html"

  - runs: tar cfv caddy-src.tar .

  - uses: go/build
    with:
      ldflags: -s -w
      output: caddy
      packages: ./cmd/caddy

  - uses: strip

subpackages:
  - name: caddy-man
    description: caddy manpages
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          "${{targets.destdir}}"/usr/bin/caddy manpage --directory "${{targets.subpkgdir}}"/usr/share/

  - name: caddy-src
    description: Caddy sources
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/src/caddy"
          tar xfv caddy-src.tar -C "${{targets.subpkgdir}}/usr/src/caddy"

update:
  enabled: true
  manual: false
  github:
    identifier: caddyserver/caddy
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        caddy --version
