package:
  name: cifs-utils
  version: 7.0
  epoch: 0
  description: CIFS filesystem user-space tools
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - keyutils-dev
      - krb5-dev
      - libcap-dev
      - py3-docutils
      - samba-dev
      - talloc-dev

pipeline:
  - uses: fetch
    with:
      expected-sha512: 4c57741af0c4567a78f352c73caca998881666a5ed36536275cfa775efd66ff1a44ebe539a8ed96c409c5b08a1378266964ce667a27e9fc7f2d43999c63dd0eb
      uri: https://ftp.samba.org/pub/linux-cifs/cifs-utils/cifs-utils-${{package.version}}.tar.bz2

  - uses: autoconf/configure

  - uses: autoconf/make

  - runs: |
      mkdir -p ${{targets.destdir}}/sbin
      make install DESTDIR="${{targets.destdir}}"

  - uses: strip

subpackages:
  - name: cifs-utils-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - cifs-utils

  - name: "cifs-utils-doc"
    description: "cifs-utils documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  release-monitor:
    identifier: 287

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        getcifsacl --version
        setcifsacl -v
        cifs.idmap --version
        cifs.upcall --version
