package:
  name: cilium-cli
  version: 0.16.18
  epoch: 0
  description: CLI to install, manage & troubleshoot Kubernetes clusters running Cilium
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cilium/cilium-cli
      tag: v${{package.version}}
      expected-commit: c39ea5e50210fde2ccfe54d07122c48fd680ac8d
      destination: cilium-cli

  - runs: |
      cd cilium-cli
      make install
      install -Dm755  /usr/local/bin/cilium ${{targets.destdir}}/usr/bin/cilium

  - uses: strip

update:
  enabled: true
  github:
    identifier: cilium/cilium-cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        cilium help
