package:
  name: cluster-autoscaler-1.31
  version: 1.31.0
  epoch: 1
  description: Autoscaling components for Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - cluster-autoscaler=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/autoscaler
      tag: cluster-autoscaler-${{package.version}}
      expected-commit: 8bda275bd3eb983b77ed002038464b2afd4bb7c1

  - uses: go/bump
    with:
      deps: github.com/opencontainers/runc@v1.1.14 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0
      modroot: cluster-autoscaler

  - uses: go/build
    with:
      modroot: cluster-autoscaler
      packages: .
      output: cluster-autoscaler
      ldflags: -s -w
      vendor: true

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}
          # The upstream helm chart assumes the binary is in /.
          ln -sf /usr/bin/cluster-autoscaler ${{targets.subpkgdir}}/cluster-autoscaler
    dependencies:
      provides:
        - cluster-autoscaler-compat=${{package.full-version}}

update:
  enabled: true
  github:
    identifier: kubernetes/autoscaler
    strip-prefix: cluster-autoscaler-
    use-tag: true
    # There are other tags like "cluster-autoscaler-chart-FOO"
    tag-filter: cluster-autoscaler-1.31.
