package:
  name: conftest
  version: 0.55.0
  epoch: 2
  description: Write tests against structured configuration data using the Open Policy Agent Rego query language
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - cue

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 99d588fa8d0864c727b9569e7b84126a9dd6b45b
      repository: https://github.com/open-policy-agent/conftest
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/open-policy-agent/opa@v0.68.0
      modroot: .

  - uses: go/build
    with:
      ldflags: -X github.com/open-policy-agent/conftest/internal/commands.version=${{package.version}}
      modroot: .
      output: conftest
      packages: .

  - uses: strip

update:
  enabled: true
  github:
    identifier: open-policy-agent/conftest
    strip-prefix: v

test:
  pipeline:
    - name: Verify conftest help command
      runs: |
        conftest --help
    - name: Verify a simple Rego policy
      runs: |
        echo 'package main' > test.rego
        conftest verify -p test.rego
