package:
  name: convco
  version: 0.6.0
  epoch: 1
  description: A Conventional commit cli
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates
      - cargo-auditable
      - cmake
      - openssf-compiler-options
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/convco/convco
      tag: v${{package.version}}
      expected-commit: 907e89d35fd4410ffa95f2ddaa17ec2ab79addc0

  - runs: |
      cargo auditable build --release
      mkdir -p "${{targets.contextdir}}"/usr/bin
      mv ./target/release/convco "${{targets.contextdir}}"/usr/bin/convco

  - uses: strip

update:
  enabled: true
  github:
    identifier: convco/convco
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        convco --version | grep ${{package.version}}
