package:
  name: cortex
  version: 1.18.0
  epoch: 1
  description: A horizontally scalable, highly available, multi-tenant, long term Prometheus.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cortexproject/cortex
      tag: v${{package.version}}
      expected-commit: 85511746c08640eb3e9e1ceb0fadaef860973958

  - uses: go/build
    with:
      packages: ./cmd/cortex
      output: cortex
      ldflags: |
        -s -w \
        -X main.Branch=$(git rev-parse --abbrev-ref HEAD) \
        -X main.Revision=$(git rev-parse --short HEAD) \
        -X main.Version=$(cat ./VERSION)

update:
  enabled: true
  github:
    identifier: cortexproject/cortex
    strip-prefix: v

test:
  pipeline:
    - runs: |
        /usr/bin/cortex --version
