package:
  name: croc
  version: 10.0.12
  epoch: 1
  description: Easily and securely send things from one computer to another
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - git

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/schollz/croc
      expected-commit: defee4b4f606221d68118f6022e83ffc591a3a46
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: .
      output: croc
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: schollz/croc
    strip-prefix: v

test:
  pipeline:
    - name: Test croc version
      runs: |
        croc --version
    - name: Test croc send and receive
      runs: |
        # Set up environment variables
        export CROC_SECRET="wolfi-test"
        port=9009

        # Start the croc relay in the background
        croc relay --ports=$port &
        relay_pid=$!
        sleep 3

        # Send a test message in the background
        croc --relay=localhost:$port send --code=$CROC_SECRET --text "test message" &
        send_pid=$!
        sleep 3

        # Receive the test message
        received_message=$(croc --relay=localhost:$port --overwrite --yes $CROC_SECRET)

        # Check if the received message matches the sent message
        [ "$received_message" = "test message" ]
