package:
  name: crossplane
  version: 1.17.1
  epoch: 0
  description: Cloud Native Control Planes
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: a33ee41b1bfdc345a2b1ba7862ad7837011aad69
      repository: https://github.com/crossplane/crossplane
      tag: v${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/crds
      cp cluster/crds/* ${{targets.destdir}}/crds

      mkdir -p ${{targets.destdir}}/webhookconfigurations
      cp cluster/webhookconfigurations/* ${{targets.destdir}}/webhookconfigurations

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.1.5

  - uses: go/build
    with:
      output: crossplane
      packages: ./cmd/crossplane
      ldflags: -X github.com/crossplane/crossplane/internal/version.version=v${{package.version}}

  - uses: strip

subpackages:
  - name: crossplane-crank
    pipeline:
      - uses: go/build
        with:
          output: crank
          packages: ./cmd/crank
      - uses: strip

update:
  enabled: true
  github:
    identifier: crossplane/crossplane
    strip-prefix: v

test:
  pipeline:
    - name: version and help output
      runs: |
        crossplane --version
        crossplane --help
