package:
  name: crun
  version: "1.17"
  epoch: 0
  description: "Fast and lightweight fully featured OCI runtime and C library for running containers"
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go-md2man
      - libcap-dev
      - libseccomp
      - libseccomp-dev
      - python3
      - wolfi-base
      - yajl
      - yajl-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/containers/crun/releases/download/${{package.version}}/crun-${{package.version}}.tar.gz
      expected-sha512: 7556467c5e0e93bb7321e2e88de8a2f537340e3e0acaa5501eab8deb0f4bb93c4561f8d063156789d3ee98fdd49069fc52c0ed0c773bd44db476eeeccc16aa1a

  - runs: |
      ./configure \
         --prefix=/usr \
         --disable-systemd

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: crun-doc
    pipeline:
      - uses: split/manpages
    description: crun manpages

update:
  enabled: true
  release-monitor:
    identifier: 96792

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        crun --version
