package:
  name: dav1d
  version: 1.4.3
  epoch: 0
  description: small and fast AV1 Decoder
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - meson
      - nasm

pipeline:
  - uses: git-checkout
    with:
      repository: https://code.videolan.org/videolan/dav1d.git
      tag: ${{package.version}}
      expected-commit: e9986de7f4264940af6fa1df1498fd2754077de4

  - uses: meson/configure
    with:
      opts: |
        -Db_lto=true \
            -Denable_tests=false \
            -Denable_tools=true \
            -Dfuzzing_engine=none \
            -Dtestdata_tests=false

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: dav1d-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - dav1d
    description: dav1d dev

  - name: libdav1d
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libdav1d.so* ${{targets.subpkgdir}}/usr/lib/

update:
  enabled: true
  release-monitor:
    identifier: 18920

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        dav1d --version
