package:
  name: dbmate
  version: 2.21.0
  epoch: 0
  description: A lightweight, framework-agnostic database migration tool.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/amacneil/dbmate
      tag: v${{package.version}}
      expected-commit: f9c7be229f6aaa97906dcdee3330a38219c9c543

  - uses: go/build
    with:
      packages: ./
      ldflags: -s -w
      output: dbmate

  - uses: strip

update:
  enabled: true
  github:
    identifier: amacneil/dbmate
    strip-prefix: v

test:
  pipeline:
    - name: Verify dbmate installation
      runs: |
        dbmate --version
