package:
  name: diffutils
  version: "3.10"
  epoch: 0
  description: "GNU diff utilities"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/diffutils/diffutils-${{package.version}}.tar.xz
      expected-sha256: 90e5e93cc724e4ebe12ede80df1634063c7a855692685919bfe60b556c9bd09e

  - runs: |
      env FORCE_UNSAFE_CONFIGURE=1 ./configure \
         --prefix=/usr \
         --libdir=/lib \
         --libexecdir=/usr/libexec \
         --sysconfdir=/etc \
         --mandir=/usr/share/man \
         --infodir=/usr/share/info \
         --disable-nls

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "diffutils-doc"
    description: "documentation for GNU coreutils"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

update:
  enabled: true
  release-monitor:
    identifier: 436

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        cmp --version
        diff --version
        diff3 --version
        sdiff --version
