package:
  name: doxygen
  version: 1.12.0
  epoch: 1
  description: A documentation system for C++, C, Java, IDL and PHP
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - coreutils
      - flex
      - openssf-compiler-options
      - perl
      - python3
      - samurai

pipeline:
  - uses: fetch
    with:
      expected-sha256: a3a3dba2018ef409d83d81a2fc42a0d19bdbe087252ef342bf214b51b8b01634
      uri: https://doxygen.nl/files/doxygen-${{package.version}}.src.tar.gz

  - runs: |
      cmake -B build -G Ninja \
          -DGIT_EXECUTABLE=/bin/false \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_BUILD_TYPE=MinSizeRel \
          -Dbuild_xmlparser=ON
      cmake --build build
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 457
  version-separator: "_"

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        doxygen --version
