package:
  name: dynamic-localpv-provisioner
  version: 4.1.1
  epoch: 0
  description: Dynamic Local Volumes for Kubernetes Stateful workloads.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - ca-certificates-bundle
      - iproute2
      - mii-tool
      - net-tools
      - procps

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openebs/dynamic-localpv-provisioner
      tag: v${{package.version}}
      expected-commit: 689f5cd6b655adb84a3f94d83bb705259d31c762

  - uses: go/bump
    with:
      deps: github.com/prometheus/client_golang@v1.11.1 github.com/Masterminds/goutils@v1.1.1 google.golang.org/grpc@v1.56.3

  - runs: |
      make provisioner-localpv
      mkdir -p ${{targets.destdir}}/usr/bin
      GOOS=$(go env GOOS)
      GOARCH=$(go env GOARCH)
      mv ./bin/provisioner-localpv/${GOOS}_${GOARCH}/provisioner-localpv ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  ignore-regex-patterns:
    - localp* # there are some misspellings in the upstream tags so using a wildcard here
  github:
    identifier: openebs/dynamic-localpv-provisioner
    strip-prefix: v
