package:
  name: emacs
  version: 30.0.91
  epoch: 0
  description: "An extensible, customizable, free/libre text editor"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gawk
      - libtool
      - libxml2-dev
      - ncurses-dev
      - posix-libc-utils
      - texinfo
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/emacs-mirror/emacs
      tag: emacs-${{package.version}}
      expected-commit: 9a1c76bf7ff49d886cc8e1a3f360d71e62544802

  - runs: autoreconf -vif

  - uses: autoconf/configure
    with:
      opts: |
        --with-x=no \
        --with-gnutls=ifavailable \
        --with-mailutils=no \
        --with-pop=no

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "emacs-doc"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

update:
  enabled: true
  github:
    identifier: emacs-mirror/emacs
    strip-prefix: emacs-
    use-tag: true
    tag-filter: emacs-

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        ctags --version
        ebrowse --version
        emacs --version
        emacs-30.0.91 --version
        emacsclient --version
        etags --version
