package:
  name: envoy-ratelimit
  # This project doesn't do releases and everything is commit based.
  # This corresponds to commit 26f28d78ccafaefe120cb698279ab2e8c4fc2c4f
  version: 0.0_git20240815
  epoch: 1
  description: Go/gRPC service designed to enable generic rate limit scenarios from different types of applications.
  copyright:
    - license: Apache-2.0

vars:
  commit: 26f28d78ccafaefe120cb698279ab2e8c4fc2c4f

environment:
  contents:
    packages:
      - git

pipeline:
  - runs: |
      git clone https://github.com/envoyproxy/ratelimit ratelimit/
      cd ratelimit/
      git checkout ${{vars.commit}}

  - uses: go/build
    with:
      modroot: ratelimit
      output: ratelimit
      packages: ./src/service_cmd

test:
  environment:
    contents:
      packages:
        - go
  pipeline:
    - runs: go version -m /usr/bin/ratelimit | grep "vcs.revision=${{vars.commit}}$"

subpackages:
  - name: envoy-ratelimit-compat
    pipeline:
      - runs: |
          # The helm chart expects the ratelimit binary to be in /bin instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"/bin
          ln -sf /usr/bin/ratelimit ${{targets.subpkgdir}}/bin/ratelimit
    description: Compatibility package to place binaries in the location expected by upstream helm charts

update:
  enabled: false
