package:
  name: execline
  version: 2.9.6.0
  epoch: 1
  description: "a small scripting language intended to be an alternative to shell scripting"
  copyright:
    - license: ISC

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - skalibs-dev
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.skarnet.org/execline
      tag: v${{package.version}}
      expected-commit: 48ebde9a5ea2a5a96f438b1bc9a19cd3bcb96f8c

  - name: Configure
    runs: |
      ./configure \
        --enable-shared \
        --enable-static \
        --disable-allstatic \
        --libdir=/usr/lib \
        --with-dynlib=/lib

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "execline-dev"
    description: "execline development headers"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 5482

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        eltest --version
        withstdinas version
