package:
  name: ffmpeg
  version: 7.0.2
  epoch: 3
  description: ffmpeg multimedia library
  copyright:
    - license: GPL-3.0-or-later AND LGPL-3.0-or-later
  resources:
    cpu: 16
    memory: 16Gi

environment:
  contents:
    packages:
      - aom
      - aom-dev
      - aom-libs
      - build-base
      - busybox
      - ca-certificates-bundle
      - dav1d-dev
      - expat-dev
      - fontconfig-dev
      - harfbuzz-dev
      - lame-dev
      - libogg-dev
      - libsdl2-dev
      - libsodium-dev
      - libsrt
      - libssh-dev
      - libtheora
      - libtheora-dev
      - libvorbis-dev
      - libwebp-dev
      - libxml2-dev
      - openjpeg-dev
      - openssl-dev
      - opus-dev
      - snappy-dev
      - soxr-dev
      - speex-dev
      - svt-av1-dev
      - wolfi-baselayout
      - x264-dev
      - x265-dev
      - yasm
      - zeromq-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.ffmpeg.org/ffmpeg.git
      expected-commit: e3a61e91030696348b56361bdf80ea358aef4a19
      tag: n${{package.version}}
      cherry-picks: |
        master/1f801dfdb5066aadf0ade9cb5e94d620f33eacdc: lavc/libx265: unbreak build for X265_BUILD >= 210

  - runs: |
      ./configure \
        --prefix=/usr \
        --libdir=/usr/lib \
        --enable-shared \
        --enable-libx264 \
        --enable-libx265 \
        --enable-libaom \
        --enable-libtheora \
        --enable-gpl \
        --enable-version3 \
        --enable-openssl \
        --enable-libmp3lame \
        --enable-ffplay \
        --enable-libdav1d \
        --enable-libharfbuzz \
        --enable-libopus \
        --enable-libsnappy \
        --enable-libsrt \
        --enable-libssh \
        --enable-libsvtav1 \
        --enable-libvorbis \
        --enable-libwebp \
        --enable-libxml2 \
        --enable-lzma \
        --enable-libfontconfig \
        --enable-libfreetype \
        --enable-libopenjpeg \
        --enable-libspeex \
        --enable-libsoxr \
        --enable-libzmq

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

data:
  - name: libraries
    items:
      libavcodec61: libavcodec
      libavdevice61: libavdevice
      libavfilter10: libavfilter
      libavformat61: libavformat
      libavutil59: libavutil
      libswresample5: libswresample
      libswscale8: libswscale
      libpostproc58: libpostproc

subpackages:
  - range: libraries
    name: ${{range.key}}
    description: "${{range.value}} library"
    pipeline:
      - runs: |
          # CHECK-WHEN-VERSION-CHANGES: 7.0.2
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/${{range.value}}.so.*.* "${{targets.subpkgdir}}"/usr/lib/

  - name: ffmpeg-static
    pipeline:
      - uses: split/static
    description: ffmpeg static libraries

  - name: ffmpeg-dev
    pipeline:
      - uses: split/dev
    description: ffmpeg development headers

  - name: ffmpeg-doc
    pipeline:
      - uses: split/manpages
    description: ffmpeg manpages

update:
  enabled: true
  release-monitor:
    identifier: 5405

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        ffmpeg --help
        ffprobe --help
