package:
  name: file
  version: "5.45"
  epoch: 3
  description: "file-type identification utility"
  copyright:
    - license: BSD-2-Clause

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: mangled-package-version

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - file
      - libtool

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/file/file.git
      tag: FILE${{vars.mangled-package-version}}
      expected-commit: 4cbd5c8f0851201d203755b76cb66ba991ffd8be

  - runs: |
      autoreconf -vif

  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "libmagic-dev"
    description: "libmagic headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libmagic

  - name: "libmagic"
    description: "file-type guessing library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libmagic.so.* "${{targets.subpkgdir}}"/usr/lib

          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/misc "${{targets.subpkgdir}}"/usr/share

  - name: "file-doc"
    description: "file documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  version-separator: _
  github:
    identifier: file/file
    tag-filter-prefix: FILE
    strip-prefix: FILE
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        file --version
