package:
  name: flex
  version: 2.6.4
  epoch: 5
  description: "tool for generating text-scanning programs"
  copyright:
    - license: BSD-2-Clause AND LGPL-2.0-or-later
  dependencies:
    runtime:
      - m4

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-baselayout

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/westes/flex/releases/download/v${{package.version}}/flex-${{package.version}}.tar.gz
      expected-sha256: e87aae032bf07c26f85ac0ed3250998c37621d95f8bd748b31f15b33c45ee995

  - name: 'Configure flex'
    runs: |
      ./configure \
        --prefix=/usr \
        --libdir=/usr/lib \
        --sysconfdir=/etc \
        --datadir=/usr/share \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --host=${{host.triplet.gnu}} \
        --target=${{host.triplet.gnu}}

  - runs: |
      make -j$(nproc) V=1

  - uses: autoconf/make-install

  - runs: |
      ln -s flex ${{targets.destdir}}/usr/bin/lex

  - uses: strip

subpackages:
  - name: "flex-dev"
    description: "flex development headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - flex

  - name: "libfl2"
    description: "flex scanner library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libfl.so* "${{targets.subpkgdir}}"/usr/lib

update:
  enabled: true
  release-monitor:
    identifier: 819

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        flex --version
        flex++ --version
        lex --version
