package:
  name: fluent-plugin-systemd
  version: 1.1.0
  epoch: 1
  description: This is a fluentd input plugin. It reads logs from the systemd journal.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby3.2-fluentd
      - ruby3.2-systemd-journal

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - systemd-dev

vars:
  gem: fluent-plugin-systemd

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 92dec83982b4dd01f02cfe565a7acc2548b8971c
      repository: https://github.com/fluent-plugins-nursery/fluent-plugin-systemd
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        ruby -e "require 'fluent/plugin/in_systemd'"
        ruby -e "require 'fluent/plugin/filter_systemd_entry'"
        ruby -e "require 'fluent/plugin/systemd/entry_mutator'"

update:
  enabled: true
  github:
    identifier: fluent-plugins-nursery/fluent-plugin-systemd
    strip-prefix: v
    use-tag: true
