package:
  name: fluent-plugin-kubernetes_metadata_filter
  version: 3.5.0
  epoch: 4
  description: This is the Filter plugin to add Kubernetes metadata
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby3.2-fluentd
      - ruby3.2-json-jwt
      - ruby3.2-kubeclient
      - ruby3.2-lru_redux
      - ruby3.2-multi_json
      - ruby3.2-net-http-persistent
      - ruby3.2-openid_connect-1.1.8
      - ruby3.2-prometheus-client
      - ruby3.2-rack-oauth2

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: fluent-plugin-kubernetes_metadata_filter

pipeline:
  # This package makes use of `git ls-files` in its gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      destination: ${{vars.gem}}
      expected-commit: 5204ec21283878003e0756d3a8ae10541d3cb597
      repository: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter.git
      tag: v${{package.version}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}

  - uses: ruby/clean

  - runs: |-
      GEM_DIR=${{targets.destdir}}$(ruby -e 'puts Gem.default_dir')/gems/${{vars.gem}}-${{package.version}}
      rm -rf ${GEM_DIR}/test \
             ${GEM_DIR}/docs \
             ${GEM_DIR}/*.md \
             ${GEM_DIR}/.github

update:
  enabled: true
  github:
    identifier: fabric8io/fluent-plugin-kubernetes_metadata_filter
    strip-prefix: v
    use-tag: true
