package:
  name: fmt
  version: 11.0.2
  epoch: 1
  description: Modern formatting library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - make
      - openssf-compiler-options

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0c9fce2ffefecfdce794e1859584e25877b7b592
      repository: https://github.com/fmtlib/fmt
      tag: ${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DBUILD_SHARED_LIBS=True \

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: fmtlib/fmt

test:
  environment:
    contents:
      packages:
        - fmt-dev
        - gcc
        - glibc-dev
  pipeline:
    - runs: |
        cat << EOF > test_fmt.cc
        #include <fmt/core.h>
        int main() {
            fmt::print("hello {}\n", "world");
            return 0;
        }
        EOF
        g++ -o test_fmt test_fmt.cc -lfmt
        ./test_fmt |grep "hello world"
