package:
  name: freetds
  version: 1.4.23
  epoch: 0
  description: FreeTDS is a set of libraries for Unix and Linux that allows programs to natively talk to Microsoft SQL Server and Sybase databases.
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - gettext-dev
      - gnutls-dev
      - gperf
      - libgcrypt-dev
      - libtool
      - pkgconf-dev
      - unixodbc-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/FreeTDS/freetds
      tag: "v${{package.version}}"
      expected-commit: eebd082fa44fa8139a87b53679a2b088c49c0a4f
      destination: "${{package.name}}"

  - working-directory: ${{package.name}}
    pipeline:
      - name: Configure
        runs: |
          ./autogen.sh --prefix=/usr --with-unixodbc=/usr --disable-libiconv --with-gnutls=/usr
      - uses: autoconf/make
      - uses: autoconf/make-install
      - uses: strip

subpackages:
  - name: freetds-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - freetds
    description: freetds dev

update:
  enabled: true
  github:
    identifier: FreeTDS/freetds
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - unixodbc
        - openssl
  pipeline:
    - name: Verify tsql command
      runs: |
        tsql -C
