package:
  name: gdb
  version: "15.2"
  epoch: 0
  description: The GNU Debugger
  copyright:
    - license: GPL-3.0-or-later AND LGPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - expat-dev
      - gmp-dev
      - libtool
      - linux-headers
      - mpfr-dev
      - ncurses-dev
      - perl
      - python3-dev
      - readline-dev
      - texinfo
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 83350ccd35b5b5a0cba6b334c41294ea968158c573940904f00b92f76345314d
      uri: https://ftp.gnu.org/gnu/gdb/gdb-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        --with-python=/usr/bin/python3 \
        --disable-nls \
        --disable-werror \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --with-system-readline \
        --with-system-zlib

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: gdb-doc
    pipeline:
      - uses: split/manpages
      - uses: split/infodir
    description: gdb manpages

update:
  enabled: true
  release-monitor:
    identifier: 11798

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        gdb --version
        gdbserver --version
