package:
  name: ggshield
  version: 1.32.0
  epoch: 0
  description: Find and fix 360+ types of hardcoded secrets and 70+ types of infrastructure-as-code misconfigurations.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - git
      - py3-certifi
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/GitGuardian/ggshield
      tag: v${{package.version}}
      expected-commit: 767ecca08e4cec0e1ffcdfb2d1c63a8fadc2454f

  - runs: |
      pip3 install certifi -U  # https://github.com/advisories/GHSA-xqr8-7jwr-rhp7
      python3 setup.py bdist_wheel
      pip3 install . --prefix=/usr --root="${{targets.destdir}}"
      find ${{targets.destdir}} -name "*.pyc" -exec rm -rf '{}' +

  - uses: strip

update:
  enabled: true
  github:
    identifier: GitGuardian/ggshield
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    - name: Check ggshield version
      runs: |
        ggshield --version
    - name: Check ggshield API status without API key
      runs: |
        output=$(ggshield api-status 2>&1 || true)
        echo "$output" | grep "Error: A GitGuardian API key is needed to use ggshield."
