package:
  name: gitlab-pages-17.4
  version: 17.4.1
  epoch: 0
  description: GitLab Pages daemon used to serve static websites for GitLab users.
  copyright:
    - license: MIT
  dependencies:
    provides:
      - gitlab-pages=${{package.full-version}}

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/gitlab-pages.git
      tag: v${{package.version}}
      expected-commit: 1a5ebda50db9b91712526b31f3ab271218f6f850

  - uses: go/build
    with:
      packages: .
      output: gitlab-pages
      tags: continuous_profiler_stackdriver
      ldflags: "-w -X main.VERSION=${{package.version}} -X main.REVISION=${{package.version}}"

  - runs: |
      mkdir -p ${{targets.contextdir}}/srv/gitlab-pages
      mkdir -p ${{targets.contextdir}}/var/log/gitlab

subpackages:
  - name: gitlab-pages-compat-${{vars.major-minor-version}}
    description: Links GitLab pages to bin directory
    dependencies:
      provides:
        - gitlab-pages-compat=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/bin
          ln -sf /usr/bin/gitlab-pages ${{targets.contextdir}}/bin/gitlab-pages

update:
  enabled: true
  git:
    strip-prefix: v
    tag-filter-prefix: v17.4

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        gitlab-pages --version
