package:
  name: glow
  version: 2.0.0
  epoch: 1
  description: Render markdown on the CLI, with pizzazz!
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/charmbracelet/glow
      tag: v${{package.version}}
      expected-commit: 67243bb6fbf6d49eddb6ab644e8e2c1395f9cb00

  - uses: go/build
    with:
      packages: .
      ldflags: |
        -s -w
        -X main.Version=${{package.version}}
        -X main.CommitSHA=$(git rev-parse HEAD)
        -X main.CommitDate=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      output: glow

  - uses: strip

update:
  enabled: true
  github:
    identifier: charmbracelet/glow
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        glow --version
