package:
  name: gpgme
  version: 1.23.2
  epoch: 1
  description: GNU - GnuPG Made Easy
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gnupg-gpgconf
      - gpg
      - gpg-agent
      - gpgsm
      - libassuan-dev
      - libgpg-error-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 9499e8b1f33cccb6815527a1bc16049d35a6198a6c5fae0185f2bd561bce5224
      uri: https://gnupg.org/ftp/gcrypt/gpgme/gpgme-${{package.version}}.tar.bz2

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: gpgme-doc
    pipeline:
      - uses: split/manpages
    description: gpgme manpages

  - name: gpgme-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - gpgme
    description: gpgme dev

update:
  enabled: true
  release-monitor:
    identifier: 1239

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        gpgme-json --version
        gpgme-tool --version
