package:
  name: grafana-agent-operator
  version: 0.43.3
  epoch: 0
  description: Grafana Agent Operator is a Kubernetes operator for the static mode of Grafana Agent. It makes it easier to deploy and configure static mode to collect telemetry data from Kubernetes resources.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.22
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/agent
      tag: v${{package.version}}
      expected-commit: d930d88c063174c60ef1e2c0526caac310351be6

  - uses: go/build
    with:
      packages: ./cmd/grafana-agent-operator
      output: grafana-agent-operator
      ldflags: -s -w

  - uses: strip

test:
  pipeline:
    - runs: /usr/bin/grafana-agent-operator -version

update:
  enabled: true
  ignore-regex-patterns:
    - -rc
  github:
    identifier: grafana/agent
    strip-prefix: v
    use-tag: true
    tag-filter-prefix: v
