package:
  name: grafana-mimir
  version: 2.13.0
  epoch: 3
  description: Grafana Mimir provides horizontally scalable, highly available, multi-tenant, long-term storage for Prometheus.
  copyright:
    - license: AGPL-3.0-or-later

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go-1.22

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/mimir
      tag: mimir-${{package.version}}
      expected-commit: 4775ec156855ba1eb498e564f09abad35053a44f

  # the repo has an ssh://git@github.com URI for mimir-prometheus
  # so just rm the file and default to the https URL for go.mod
  - runs: rm .gitconfig

  - uses: go/bump
    with:
      deps: github.com/rs/cors@v1.11.0 google.golang.org/grpc@v1.64.1
      modroot: .

  - uses: go/build
    with:
      modroot: .
      packages: ./cmd/mimir
      output: grafana-mimir
      ldflags: "-extldflags -static -s -w"

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - distributed
    - weekly
  github:
    identifier: grafana/mimir
    strip-prefix: mimir-
    use-tag: true

test:
  pipeline:
    - runs: |
        grafana-mimir -version
