package:
  name: graphviz
  version: 12.1.2
  epoch: 0
  description: Graph Visualization Tools
  copyright:
    - license: EPL-1.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo-dev
      - expat-dev
      - flex
      - fontconfig-dev
      - freetype-dev
      - gd-dev
      - gmp-dev
      - libjpeg-turbo-dev
      - libltdl
      - libpng-dev
      - libsm-dev
      - libxaw-dev
      - libxext-dev
      - lua5.4-dev
      - m4
      - pango-dev
      - python3-dev
      - swig
      - tcl
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: cf9e6de9d5949dffbc4dd46f833085ff8e7e55482ffb84641819bbf0d18c5f02
      uri: https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/${{package.version}}/graphviz-${{package.version}}.tar.xz

  - runs: |
      LUA=lua5.4 \
      lua_suffix=5.4 \
      ./configure \
        --prefix=/usr \
        --libdir=/usr/lib \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info \
        --localstatedir=/var \
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --sysconfdir=/etc \
        --disable-python \
        --disable-silent-rules \
        --disable-static \
        --disable-dependency-tracking \
        --disable-ltdl-install \
        --enable-ltdl \
        --enable-sharp=no \
        --enable-go=no \
        --enable-guile=no \
        --enable-java=no \
        --enable-lua=yes \
        --enable-ocaml=no \
        --enable-perl=no \
        --enable-php=no \
        --enable-python3 \
        --enable-r=no \
        --enable-ruby=no \
        --enable-tcl=no \
        --without-included-ltdl \
        --with-gdk-pixbuf=yes \
        --with-ipsepcola=yes \
        --with-jpeg \
        --with-libgd=yes \
        --with-pangocairo=yes \
        --with-rsvg=yes \
        --with-x

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: graphviz-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - graphviz
        - cairo-dev
        - expat-dev
        - fontconfig-dev
        - freetype-dev
        - gd-dev
        - gmp-dev
        - libjpeg-turbo-dev
        - libpng-dev
        - libsm-dev
        - libxext-dev
        - pango-dev
        - python3-dev
        - zlib-dev
    description: graphviz dev

  - name: graphviz-doc
    pipeline:
      - uses: split/manpages
    description: graphviz manpages

  - name: py3-gv
    dependencies:
      runtime:
        - python3
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/graphviz
          mv ${{targets.destdir}}/usr/lib/graphviz/python3* ${{targets.subpkgdir}}/usr/lib/graphviz/
          mv ${{targets.destdir}}/usr/lib/python3* ${{targets.subpkgdir}}/usr/lib/
    description: Python3 extension for graphviz

  - name: lua5.4-graphviz
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib/lua/5.4
          mkdir -p ${{targets.subpkgdir}}/usr/lib/graphviz

          mv ${{targets.destdir}}/usr/lib/lua5.4/lua/* ${{targets.subpkgdir}}/usr/lib/lua/5.4/
          mv ${{targets.destdir}}/usr/lib/graphviz/lua ${{targets.subpkgdir}}/usr/lib/graphviz/
    description: Lua5.4 extension for graphviz

  - name: graphviz-graphs
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/graphviz
          mv ${{targets.destdir}}/usr/share/graphviz/graphs/* ${{targets.subpkgdir}}/usr/share/graphviz/
    description: Demo graphs for graphviz

update:
  enabled: true
  release-monitor:
    identifier: 1249

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        acyclic -?
        bcomps version
        ccomps version
        circo --version
        cluster version
        diffimg -?
        dijkstra version
        dot --version
        dot2gxl version
        dot_builtins --version
        edgepaint --version
        fdp --version
        gc version
        gml2gv version
        graphml2gv version
        gv2gml version
        gv2gxl version
        gvcolor version
        gvgen -?
        gvmap version
        gvmap.sh version
        gvpack version
        gvpr -V
        gxl2dot version
        gxl2gv version
        mm2gv -?
        neato --version
        nop -?
        osage --version
        patchwork --version
        prune version
        sccmap version
        sfdp --version
        tred version
        twopi --version
        unflatten version
