package:
  name: gtk-3
  version: 3.24.43
  epoch: 1
  description: The GTK+ Toolkit (v3)
  copyright:
    - license: LGPL-2.1-or-later

# creates a new var that contains only the major and minor version to be used in the fetch URL
# e.g. 2.46.0 will create a new var mangled-package-version=2.46
var-transforms:
  - from: ${{package.version}}
    match: (\d+\.\d+)\.\d+
    replace: $1
    to: mangled-package-version

environment:
  contents:
    packages:
      - at-spi2-core-dev
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo-dev
      - cmake
      - cups-dev
      - dbus-dev
      - expat-dev
      - fontconfig-dev
      - fribidi-dev
      - gdk-pixbuf-dev
      - gettext-dev
      - git
      - glib-dev
      - glib-gir
      - gobject-introspection-dev
      - gtk-doc
      - harfbuzz-dev
      - hicolor-icon-theme
      - iso-codes-dev
      - libatk-bridge-2.0
      - libepoxy-dev
      - libice-dev
      - libtool
      - libx11-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxdamage-dev
      - libxext-dev
      - libxfixes-dev
      - libxft-dev
      - libxi-dev
      - libxinerama-dev
      - libxkbcommon
      - libxkbcommon-dev
      - libxrandr-dev
      - libxtst-dev
      - mesa-dev
      - meson
      - ninja
      - openssf-compiler-options
      - pango-dev
      - py3-packaging
      - shared-mime-info
      - tiff-dev
      - wayland-dev
      - wayland-protocols
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://download.gnome.org/sources/gtk+/${{vars.mangled-package-version}}/gtk+-${{package.version}}.tar.xz
      expected-sha512: 2f208a353d94fa504088ab080006cb097de721ec934b69b5719af0f4c8c72d2aa9a68b47239feca1622ec67c7389be87023729ee6ad3580a87777f2bf9ed5375

  - uses: meson/configure
    with:
      opts: |
        -Db_lto=true \
        -Dman=true \
        -Dgtk_doc=false \
        -Dbroadway_backend=true \
        -Dexamples=false

  - uses: meson/compile

  - uses: meson/install

  - runs: |
      # We've had trouble with this build accidentally including pango. This should be fixed,
      # but throw in a test here in case.
      if [ -f ${{targets.destdir}}/usr/lib/libpango-1.0.so ]; then
        echo "ERROR: libpango-1.0.so found in /usr/lib. This is a bug in the build system."
        exit 1
      fi

  - uses: strip

subpackages:
  - name: gtk-3-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - shared-mime-info
        - at-spi2-core-dev
        - gdk-pixbuf-dev
        - glib-dev
        - libepoxy-dev
        - libxext-dev
        - libxi-dev
        - libxinerama-dev
        - libxkbcommon-dev
        - wayland-dev
    description: gtk+3 dev

  - name: gtk-3-doc
    pipeline:
      - uses: split/manpages
    description: gtk+3 manpages

  - name: gtk-3-lang
    pipeline:
      - uses: split/locales
    description: gtk+3 locales

update:
  enabled: true
  release-monitor:
    identifier: 311549

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        broadwayd --help
        gtk-encode-symbolic-svg --help
        gtk-launch --version
        gtk-update-icon-cache --help
        gtk3-demo --version
        gtk3-icon-browser --help
        gtk3-widget-factory --version
