package:
  name: gzip
  version: "1.13"
  epoch: 3
  description: "GNU data compression program"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - gettext-dev
      - texinfo
      - xz

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.savannah.gnu.org/git/gzip.git
      tag: v${{package.version}}
      expected-commit: ec1a0b1af679e252839ef4996e92f69d3ee8b3d2

  - runs: |
      ./bootstrap

  - name: Configure
    runs: |
      export DEFS="NO_ASM"
      ./configure \
         --host=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --datadir=/usr/share

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      mkdir -p ${{targets.destdir}}/bin

      for i in gzip gunzip; do
        mv ${{targets.destdir}}/usr/bin/${i} ${{targets.destdir}}/bin/${i}
        ln -s /bin/${i} ${{targets.destdir}}/usr/bin/${i}
      done

      ln -sf /bin/gunzip ${{targets.destdir}}/usr/bin/uncompress

  - uses: strip

subpackages:
  - name: "gzip-doc"
    description: "gzip documentation"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

update:
  enabled: true
  release-monitor:
    identifier: 1290

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        gunzip --version
        gzip --version
        gunzip --version
        gzexe --version
        gzip --version
        uncompress --version
        zcat --version
        zcmp --version
        zdiff --version
        zegrep --version
        zfgrep --version
        zforce --version
        zgrep --version
        zless --version
        zmore --version
        znew --version
