package:
  name: harbor-scanner-trivy
  version: 0.31.4
  epoch: 1
  description: Use Trivy as a plug-in vulnerability scanner in the Harbor registry
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - trivy

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d42c6b1f91f9ec87c789035f7583f684bcde0103
      repository: https://github.com/aquasecurity/harbor-scanner-trivy
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/scanner-trivy
      output: scanner-trivy

  - uses: strip

test:
  pipeline:
    - runs: |
        # No version or help info
        scanner-trivy & sleep 3; kill $!

update:
  enabled: true
  github:
    identifier: aquasecurity/harbor-scanner-trivy
    strip-prefix: v
