package:
  name: harfbuzz
  version: 10.0.1
  epoch: 0
  description: Text shaping library
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo-dev
      - expat-dev
      - freetype-dev
      - glib-dev
      - glib-gir
      - gobject-introspection-dev
      - graphite2-dev
      - icu-dev
      - meson
      - posix-libc-utils
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: b2cb13bd351904cb9038f907dc0dee0ae07127061242fe3556b2795c4e9748fc
      uri: https://github.com/harfbuzz/harfbuzz/releases/download/${{package.version}}/harfbuzz-${{package.version}}.tar.xz

  - uses: meson/configure
    with:
      opts: |
        --default-library=both \
        -Dcpp_std=c++17 \
        -Dglib=enabled \
        -Dgobject=enabled \
        -Dgraphite=enabled \
        -Dicu=enabled \
        -Dfreetype=enabled \
        -Dcairo=enabled

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: harfbuzz-static
    pipeline:
      - uses: split/static
    description: harfbuzz static

  - name: harfbuzz-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - harfbuzz
        - harfbuzz-icu
        - graphite2-dev
        - freetype-dev
        - glib-dev~2
    description: harfbuzz dev

  - name: harfbuzz-icu
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv ${{targets.destdir}}/usr/lib/lib*icu.so.* ${{targets.subpkgdir}}/usr/lib/
    description: Harfbuzz ICU support library

  - name: harfbuzz-utils
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr
          mv ${{targets.destdir}}/usr/bin ${{targets.subpkgdir}}/usr/
    description: harfbuzz (utilities)

update:
  enabled: true
  github:
    identifier: harfbuzz/harfbuzz
    strip-prefix: v
