package:
  name: httpie
  version: 3.2.3
  epoch: 0
  description: "HTTPie for Terminal — modern, user-friendly command-line HTTP client for the API era. JSON support, colors, sessions, downloads, plugins & more."
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-multidict
      - py3-pygments
      - py3-requests
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/httpie/httpie
      tag: ${{package.version}}
      expected-commit: 7f03c52d2237440c5a672296ce6955aae4ed4f09

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  github:
    identifier: httpie/httpie
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        http --version
        httpie --version
        https --version
