package:
  name: hugo
  version: 0.135.0
  epoch: 0
  description: The world's fastest framework for building websites.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gohugoio/hugo
      tag: v${{package.version}}
      expected-commit: f30603c47f5205e30ef83c70419f57d7eb7175ab

  - uses: go/build
    with:
      packages: .
      output: hugo

  - uses: strip

update:
  enabled: true
  github:
    identifier: gohugoio/hugo
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - git
        - bash
  pipeline:
    - name: Create a new Hugo site
      runs: |
        # Create a new Hugo site
        hugo new site test-site
    - name: Check Hugo version
      runs: |
        # Check the Hugo version
        hugo version
    - uses: test/daemon-check-output
      working-directory: test-site
      with:
        start: /usr/bin/hugo serve
        expected_output: "Web Server is available at"
        timeout: 10
