package:
  name: hunspell
  version: 1.7.2
  epoch: 1
  description: Spell checker and morphological analyzer library and program
  copyright:
    - license: GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gettext-dev
      - ncurses-dev
      - readline-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 11ddfa39afe28c28539fe65fc4f1592d410c1e9b6dd7d8a91ca25d85e9ec65b8
      uri: https://github.com/hunspell/hunspell/releases/download/v${{package.version}}/hunspell-${{package.version}}.tar.gz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libhunspell
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libhunspell-*.so.* "${{targets.contextdir}}"/usr/lib/

  - name: hunspell-dev
    pipeline:
      - uses: split/dev
    description: hunspell dev

  - name: hunspell-doc
    pipeline:
      - uses: split/manpages
    description: hunspell manpages

update:
  enabled: true
  github:
    identifier: hunspell/hunspell
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        affixcompress --version
        hunspell --version
        hunzip --version
        ispellaff2myspell --version
        makealias --version
