package:
  name: hwloc
  version: 2.11.2
  epoch: 0
  description: Portable abstraction of hierarchical hardware architectures
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo-dev
      - eudev-dev
      - libxml2-dev
      - ncurses-dev
      - numactl-dev
      - py3-sphinx-7
      - py3-sphinx-rtd-theme
      - python-3.12

# creates a new var that contains only the major and minor version to be used in the fetch URL
# e.g. 2.46.0 will create a new var mangled-package-version=2.46
var-transforms:
  - from: ${{package.version}}
    match: (\d+\.\d+)\.\d+
    replace: $1
    to: mangled-package-version

pipeline:
  - uses: fetch
    with:
      expected-sha256: f7f88fecae067100f1a1a915b658add0f4f71561259482910a69baea22fe8409
      uri: https://download.open-mpi.org/release/hwloc/v${{vars.mangled-package-version}}/hwloc-${{package.version}}.tar.bz2

  - uses: autoconf/configure
    with:
      opts: |
        --enable-plugins

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: hwloc-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - hwloc
    description: hwloc dev

  - name: hwloc-doc
    pipeline:
      - uses: split/manpages
    description: hwloc manpages

update:
  enabled: true
  github:
    identifier: open-mpi/hwloc
    strip-prefix: hwloc-
    tag-filter: hwloc-
    use-tag: true

test:
  pipeline:
    - runs: |
        hwloc-ls
