package:
  name: i2c-tools
  version: "4.3"
  epoch: 0
  description: Tools for monitoring I2C devices
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - linux-headers
      - py3.12-setuptools
      - python3-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: b4f63b9f8d74e89a010f1d6e4748659df2f556717dfa273cedc144be451758b9
      uri: https://fossies.org/linux/misc/i2c-tools-${{package.version}}.tar.gz

  - runs: |
      make DESTDIR="${{targets.destdir}}"
      builddir="$(pwd)"
      cd "$builddir"/py-smbus
      CFLAGS="$CFLAGS -I$builddir/include" python3 setup.py build
      cd $builddir
      make DESTDIR="${{targets.destdir}}" install
      cd "$builddir"/py-smbus
      python3 setup.py install --skip-build --root="${{targets.destdir}}"

  - uses: strip

subpackages:
  - name: i2c-tools-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - i2c-tools
    description: i2c-tools dev

  - name: i2c-tools-doc
    pipeline:
      - uses: split/manpages
    description: i2c-tools manpages

  - name: py3-smbus
    pipeline:
      - runs: |
          install -d "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/python3* "${{targets.subpkgdir}}"/usr/lib
    description: i2c-tools python bindings
    dependencies:
      runtime:
        - i2c-tools
    options:
      no-depends: true

update:
  enabled: true
  release-monitor:
    identifier: 9272

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        i2cdetect -V
        i2cdump -V
        i2cget -V
        i2cset -V
        i2ctransfer -V
