package:
  name: imagemagick
  version: 7.1.1.38
  epoch: 0
  description: Tools and libraries for manipulating common image formats
  copyright:
    - license: ImageMagick
  dependencies:
    runtime:
      - libgomp

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - chrpath
      - fftw-dev
      - fontconfig-dev
      - freetype-dev
      - ghostscript-dev
      - lcms2-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - libtool
      - libwebp-dev
      - libx11-dev
      - libxext-dev
      - libxml2-dev
      - openjpeg-dev
      - pango-dev
      - perl-dev
      - tiff-dev
      - zlib-dev

var-transforms:
  - from: ${{package.version}}
    match: \.([^\[.-]*)$
    replace: "-$1"
    to: mangled-package-version

pipeline:
  - uses: fetch
    with:
      expected-sha256: 5e449530ccec8b85ae2bfd1ad773184fb7a4737d40fd9439db8a5d4beee4403e
      uri: https://github.com/ImageMagick/ImageMagick/archive/refs/tags/${{vars.mangled-package-version}}.tar.gz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: imagemagick-doc
    description: "ImageMagick documentation and manpages"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc/ "${{targets.subpkgdir}}"/usr/share

  - name: imagemagick-static
    description: ImageMagick static libraries
    pipeline:
      - uses: split/static

  - name: imagemagick-dev
    description: ImageMagick dev headers
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - imagemagick

update:
  enabled: true
  version-transform:
    - match: "-"
      replace: .
  github:
    identifier: ImageMagick/ImageMagick
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        animate --version
        compare --version
        composite --version
        convert --version
        display --version
        identify --version
        import --version
        magick --version
        magick-script --version
        mogrify --version
        montage --version
        stream --help
