package:
  name: iniparser
  version: 4.2.4
  epoch: 3
  description: "C library for parsing 'INI-style' files"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - doxygen
      - graphviz
      - openssf-compiler-options
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ndevilla/iniparser
      tag: v${{package.version}}
      expected-commit: 4e5d1cc10215ce328c61bb5fd7839746e47375f9

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: "iniparser-dev"
    description: "headers for iniparser"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - iniparser

  - name: "iniparser-doc"
    description: "iniparser documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc/iniparser "${{targets.subpkgdir}}"/usr/share

update:
  enabled: true
  github:
    identifier: ndevilla/iniparser
    strip-prefix: v
    use-tag: true
    tag-filter: v
