package:
  name: jaeger
  version: 1.61.0
  epoch: 1
  description: Jaeger, a Distributed Tracing Platform

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jaegertracing/jaeger
      tag: v${{package.version}}
      expected-commit: e047f2091158d7c9b3e9e12afa9f74de0da02f43
      recurse-submodules: true

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - nodejs-20
      - yarn

data:
  - name: jaeger-components
    items:
      agent: "."
      all-in-one: "."
      anonymizer: "."
      collector: "."
      es-index-cleaner: "."
      es-rollover: "."
      esmapping-generator: "."
      ingester: "."
      query: "."
      remote-storage: "."
      tracegen: "."

subpackages:
  - range: jaeger-components
    name: "${{package.name}}-${{range.key}}"
    pipeline:
      - runs: |
          ## Only run this step if building for all-in-one package
          ## This builds the ui component of jaeger with yarn
          if [[ "${{range.key}}" = "all-in-one" ]]; then
            mkdir -p jaeger-ui/packages/jaeger-ui/build
            rm -rf cmd/query/app/ui/actual/*
            yarn install --frozen-lockfile --cwd jaeger-ui
            cd jaeger-ui/packages/jaeger-ui/build
            yarn build
          fi
      - runs: |
          ## Only run this step if building for all-in-one package
          ## This copies the build artifact into a go package
          if [[ "${{range.key}}" = "all-in-one" ]]; then
            cp -r jaeger-ui/packages/jaeger-ui/build/* cmd/query/app/ui/actual
            find cmd/query/app/ui/actual -type f | grep -v .gitignore | xargs gzip --no-name
            touch -t $(date -r jaeger-ui/packages/jaeger-ui/build/index.html '+%Y%m%d%H%M.%S') cmd/query/app/ui/actual/index.html.gz
          fi
      - uses: go/build
        with:
          modroot: cmd/${{range.key}}
          packages: .
          ldflags: -X github.com/jaegertracing/jaeger/pkg/version.latestVersion=v${{package.version}}
          output: ${{range.key}}
    test:
      pipeline:
        - runs: |
            apk add ${{package.name}}-${{range.key}}
            ${{range.key}} --help

update:
  enabled: true
  github:
    identifier: jaegertracing/jaeger
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-agent
        - ${{package.name}}-all-in-one
        - ${{package.name}}-anonymizer
        - ${{package.name}}-collector
        - ${{package.name}}-es-index-cleaner
        - ${{package.name}}-es-rollover
        - ${{package.name}}-esmapping-generator
        - ${{package.name}}-ingester
        - ${{package.name}}-query
        - ${{package.name}}-remote-storage
        - ${{package.name}}-tracegen
        - jq
  pipeline:
    - name: "Check Versions"
      runs: |
        agent version 2>&1 | grep ${{package.version}}
        all-in-one version 2>&1 | grep ${{package.version}}
        anonymizer version 2>&1 | grep ${{package.version}}
        collector version 2>&1 | grep ${{package.version}}
        esmapping-generator version 2>&1 | grep ${{package.version}}
        ingester version 2>&1 | grep ${{package.version}}
        query version 2>&1 | grep ${{package.version}}
        remote-storage version 2>&1 | grep ${{package.version}}
        tracegen version 2>&1 | grep ${{package.version}}
    - name: "Check all in one status"
      uses: test/daemon-check-output
      with:
        start: "/usr/bin/all-in-one"
        timeout: 60
        expected_output: |
          Starting HTTP server
    - name: "Check connector status"
      uses: test/daemon-check-output
      with:
        start: "/usr/bin/collector"
        timeout: 60
        expected_output: |
          Admin server started
    - name: "Check query status"
      uses: test/daemon-check-output
      with:
        start: "/usr/bin/query"
        timeout: 60
        expected_output: |
          Admin server started
    - name: "Check ingester status"
      uses: test/daemon-check-output
      with:
        start: "/usr/bin/query"
        timeout: 60
        expected_output: |
          Admin server started
