package:
  name: json-c
  version: "0.18"
  epoch: 0
  description: A JSON implementation in C
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - doxygen
      - samurai

pipeline:
  - uses: fetch
    with:
      expected-sha256: 876ab046479166b869afc6896d288183bbc0e5843f141200c677b3e8dfb11724
      uri: https://s3.amazonaws.com/json-c_releases/releases/json-c-${{package.version}}.tar.gz

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: json-c-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - json-c
    description: json-c dev

  - name: json-c-doc
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/doc/json-c
          mv doc/html "${{targets.subpkgdir}}"/usr/share/doc/json-c
    description: json-c doc

update:
  enabled: true
  release-monitor:
    identifier: 1477
