package:
  name: k8s-sidecar
  version: 1.28.0
  epoch: 0
  description: "container intended to run inside a kubernetes cluster to collect config maps with a specified label and store the included files in a local folder"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kiwigrid/k8s-sidecar
      tag: ${{package.version}}
      expected-commit: a58636830886e902130fa5efece78fa276b43fa7

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/share/app

      cd src
      # Mitigate CVE-2022-40897 / GHSA-r9hx-vwmv-q579
      pip install --upgrade setuptools
      pip3 install --no-cache-dir -r requirements.txt --prefix=/usr --root="${{targets.destdir}}"

      # Patch CVE-2024-3651
      pip install idna==3.7
      # Patch GHSA-34jh-p97f-mpxf
      pip install urllib3==2.2.2
      # Patch GHSA-248v-346w-9cwc
      pip install certifi==2024.07.04

      cd ..
      mv src/* ${{targets.destdir}}/usr/share/app

      find ${{targets.destdir}} \( -type d -a -name test -o -name tests \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' \+

  - uses: strip

update:
  enabled: true
  github:
    identifier: kiwigrid/k8s-sidecar
    use-tag: true

test:
  pipeline:
    - runs: |
        # This only runs in k8s but make sure it errors correctly
        python3 /usr/share/app/sidecar.py 2>&1 | grep CRITICAL
