package:
  name: k8ssandra-client
  version: 0.5.0
  epoch: 2
  description: A kubectl plugin to simplify usage of k8ssandra.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6d6f0acdfeb764460a25f9d2e141d101b4a87727
      repository: https://github.com/k8ssandra/k8ssandra-client
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0 google.golang.org/protobuf@v1.33.0 helm.sh/helm/v3@v3.14.4 oras.land/oras-go@v1.2.6 github.com/docker/docker@v27.1.1

  - uses: go/build
    with:
      modroot: .
      output: kubectl-k8ssandra
      packages: ./cmd/kubectl-k8ssandra

update:
  enabled: true
  github:
    identifier: k8ssandra/k8ssandra-client
    strip-prefix: v

subpackages:
  - name: k8ssandra-client-compat
    description: Compatibility package to place binaries in the location expected by upstream Dockerfile
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"
          ln -sf /usr/bin/kubectl-k8ssandra ${{targets.contextdir}}/kubectl-k8ssandra

test:
  pipeline:
    - runs: |
        kubectl-k8ssandra --help
