package:
  name: kafka-proxy
  version: 0.3.11
  epoch: 1
  description: Allows a service to connect to Kafka brokers without having to deal with SASL/PLAIN authentication and SSL certificates
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grepplabs/kafka-proxy
      tag: v${{package.version}}
      expected-commit: 71d07615c0e733a5418e245e3fb8b7e117187834

  - uses: go/build
    with:
      packages: .
      output: kafka-proxy

  - uses: strip

update:
  enabled: true
  github:
    identifier: grepplabs/kafka-proxy
    strip-prefix: v

test:
  pipeline:
    - runs: |
        kafka-proxy --help
