package:
  name: kapp
  version: 0.63.3
  epoch: 0
  description: kapp is a simple deployment tool focused on the concept of "Kubernetes application" — a set of resources with the same label
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: e77aa1c451be38edf91f063094a28c1dd1f08deb
      repository: https://github.com/carvel-dev/kapp
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: k8s.io/kubernetes@v1.30.3

  - uses: go/build
    with:
      packages: ./cmd/kapp
      output: kapp
      ldflags: -X carvel.dev/kapp/pkg/kapp/version.Version=v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: carvel-dev/kapp
    strip-prefix: v

test:
  pipeline:
    - name: version check
      runs: kapp version | grep ${{package.version}}
    - uses: test/kwok/cluster
    - name: demo application
      runs: |
        cat <<'EOF' > app.yaml
        ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-deployment
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
              - name: nginx
                image: cgr.dev/chainguard/nginx:latest
                ports:
                - containerPort: 80
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: nginx-service
        spec:
          type: ClusterIP
          ports:
          - port: 80
            targetPort: 80
          selector:
            app: nginx
        EOF
        kapp --yes deploy --app simple-app --file app.yaml
        kapp list
        kapp inspect --app simple-app --tree
