package:
  name: kdash
  version: 0.6.1
  epoch: 1
  description: "A simple and fast dashboard for Kubernetes"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - libgit2-dev
      - libxcb
      - libxcb-dev
      - openssl
      - openssl-dev
      - pkgconf
      - pkgconf-dev
      - python3
      - rust
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kdash-rs/kdash
      tag: v${{package.version}}
      expected-commit: 4433e6dda5466955a21f168476b0483db05839bf

  - uses: rust/cargobump

  - runs: |
      # https://github.com/time-rs/time/issues/693
      cargo update time --precise 0.3.36
      OPENSSL_NO_VENDOR=true cargo auditable build --release
      install -Dm755 target/release/kdash "${{targets.destdir}}"/usr/bin/kdash

  - uses: strip

update:
  enabled: true
  github:
    identifier: kdash-rs/kdash
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        kdash --version
