package:
  name: kserve
  version: 0.13.1
  epoch: 5
  description: "Standardized Serverless ML Inference Platform on Kubernetes"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - go
      - py3.11-pip
      - python-3.11-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kserve/kserve
      tag: v${{package.version}}
      expected-commit: e7d9ac8c48900bfd6db4821305b762bc51d8a67b

data:
  - name: go-components
    items:
      agent: "."
      router: "."
      manager: "."
      qpext: "qpext"

subpackages:
  - range: go-components
    name: kserve-${{range.key}}
    pipeline:
      - uses: go/build
        working-directory: ${{range.value}}
        with:
          modroot: .
          packages: ./cmd/${{range.key}}
          output: ${{range.key}}

  - range: go-components
    name: kserve-${{range.key}}-compat
    dependencies:
      runtime:
        - kserve-${{range.key}}
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}/"
          ln -s ../usr/bin/${{range.key}} "${{targets.contextdir}}/${{range.key}}"
    test:
      environment:
        contents:
          packages:
            - busybox
      pipeline:
        - name: "check paths"
          runs: |
            [ -x /${{range.key}} -a -f /${{range.key}} ]

  - name: kserve-storage-controller
    options:
      no-commands: true
    pipeline:
      - working-directory: ./python
        runs: |
          python=$(which python3.11)

          (
            set -x
            cd kserve

            # get poetry - until poetry is multi-versioned, just install from pip
            workd=$(mktemp -d)
            $python -m venv "$workd"
            $workd/bin/pip install poetry

            # PATCH_RAY: patch ray to address its embedded thirdparty_files
            #  aiohttp CVE-2024-30251, CVE-2024-27306, CVE-2024-42367
            #  idna CVE-2024-3651
            #
            # error if new version does not have 2.10.0, so we do not pin
            # current version is 2.35
            $workd/bin/poetry show ray >/tmp/out
            ver=$(awk '$1 == "version" { print $3 }' /tmp/out)
            case "$ver" in
              2.10.*) :;;
              *) echo "FAIL: Found ray at version '$ver', expected 2.10.*,"
                 echo "FAIL: update or drop PATCH_RAY section"
                 exit 1;;
            esac
            $workd/bin/poetry add ray~2.35 --extras=serve --lock

            $workd/bin/poetry build

            wheel=$(echo dist/*.whl)
            [ -f "$wheel" ] || { echo "not exactly one wheel: $wheel"; exit 1; }

            # just let pip handle deps for now.
            $python -m pip install --verbose --prefix=/usr "--root=${{targets.contextdir}}" \
               "$wheel[storage]"

            rm -Rf "$workd"
          )

          # CVE-2024-6345 - see duplicate code in py3-virtualenv.yaml
          ( cd "${{targets.contextdir}}" &&
            cd usr/lib/python*/site-packages/virtualenv/seed/wheels/embed &&
            rm -v \
               setuptools-68.0.0-py3-none-any.whl \
               pip-24.0-py3-none-any.whl \
               wheel-0.42.0-py3-none-any.whl
          )

          (
            d=${{targets.contextdir}}/storage-initializer/scripts/
            mkdir -p "$d"
            cp storage-initializer/scripts/initializer-entrypoint "$d"
            cd "$d"
            chmod 755 initializer-entrypoint

            # update shbang to point to the python used rather than '/usr/bin/env python'
            sed -i.dist "1s,#!/usr/bin/env python[^ ]*,#!$python," initializer-entrypoint
            # exit fail if it did not change anything
            diff -u initializer-entrypoint.dist initializer-entrypoint && exit 1
            rm initializer-entrypoint.dist
          )
      - uses: strip
    test:
      environment:
        contents:
          packages:
            - busybox
      pipeline:
        - name: "test entrypoint usage"
          runs: |
            /storage-initializer/scripts/initializer-entrypoint --help

update:
  enabled: true
  github:
    identifier: kserve/kserve
    strip-prefix: v
