package:
  name: kserve-modelmesh
  version: 0.12.0
  epoch: 1
  description: The ModelMesh framework is a mature, general-purpose model serving management/routing layer designed for high-scale, high-density and frequently-changing model use cases.
  dependencies:
    runtime:
      - bash # entrypoint script uses bash
      - openjdk-17-default-jvm
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - maven-3.9
      - openjdk-17

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kserve/modelmesh.git
      tag: v${{package.version}}
      expected-commit: f8212c75fffba9af22c3f3831ea0a8caade518d2

  - name: Compile
    runs: |
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
      mvn -B package -Dfile.encoding=UTF8 -DskipTests=true --file pom.xml

subpackages:
  - name: kserve-modelmesh-compat
    description: "compat package with kserve/modelmesh image"
    pipeline:
      - runs: |
          mkdir -p ${{targets.destdir}}/opt/kserve/mmesh
          cp -r /home/build/target/dockerhome/ ${{targets.destdir}}/opt/kserve/mmesh/

test:
  pipeline:
    - name: Verify compat packages exist at the right directories
      runs: |
        ls /opt/kserve/mmesh/dockerhome/lib/ | grep -q  'model-.*\.jar'
        ls /opt/kserve/mmesh/dockerhome/ | grep -q 'start.sh'

update:
  enabled: true
  github:
    identifier: kserve/modelmesh
    strip-prefix: v
