package:
  name: ksops
  version: 4.3.2
  epoch: 3
  description: Flexible Kustomize Plugin for SOPS Encrypted Resources
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - kustomize

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/viaduct-ai/kustomize-sops.git
      tag: v${{package.version}}
      expected-commit: 7f6baaa40b4e419bc3c8523e341090de04f3aa73

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1

  - uses: go/build
    with:
      packages: ksops.go
      output: ksops

  - uses: strip

update:
  enabled: true
  github:
    identifier: viaduct-ai/kustomize-sops
    strip-prefix: v
