package:
  name: kubeadm-controlplane-controller
  version: 1.8.3
  epoch: 0
  description: Cluster API kubeadm controlplane controller
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 945c938ce3e093c71950e022de4253373f911ae8
      repository: https://github.com/kubernetes-sigs/cluster-api
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: -s -w
      output: kubeadm-controlplane-controller
      packages: ./controlplane/kubeadm

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cluster-api
    strip-prefix: v
    tag-filter: v
    use-tag: true
