package:
  name: kubernetes-csi-external-provisioner
  version: 5.1.0
  epoch: 1
  description: A dynamic provisioner for Kubernetes CSI plugins.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-csi/external-provisioner
      expected-commit: 656955bc2294f10a5ec505acfac6091048e30a08
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/csi-provisioner
      output: csi-provisioner
      ldflags: -s -w -X main.version=$(git describe --long --tags --match='v*' --dirty)
      vendor: "true"

  - uses: strip

test:
  pipeline:
    - runs: csi-provisioner --version | grep ${{package.version}}

update:
  enabled: true
  github:
    identifier: kubernetes-csi/external-provisioner
    strip-prefix: v
