package:
  name: kubernetes-release
  version: 0.17.8
  epoch: 0
  description: Release infrastructure for Kubernetes and related components
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/release
      tag: v${{package.version}}
      expected-commit: 27310fb3f16ee2c1ef7d4f71d30ab9b0dc9c642c

subpackages:
  - name: ${{package.name}}-go-runner
    description: "A go based binary that can run commands and wrap stdout/stderr"
    pipeline:
      - working-directory: /home/build/images/build/go-runner
        uses: go/build
        with:
          packages: .
          output: go-runner
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/
          ln -sf /usr/bin/go-runner ${{targets.subpkgdir}}/go-runner

test:
  environment:
    contents:
      packages:
        - go
        - ${{package.name}}-go-runner
  pipeline:
    - name: Verify go-runner installation
      runs: |
        go-runner go version
        /go-runner go version

update:
  enabled: true
  github:
    identifier: kubernetes/release
    strip-prefix: v
