package:
  name: kube-state-metrics
  version: 2.13.0
  epoch: 1
  description: Add-on agent to generate and expose cluster-level metrics.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes/kube-state-metrics
      tag: v${{package.version}}
      expected-commit: 76c5888e3402c946abd6f31876f3aada4c0c84fc

  - uses: go/bump
    with:
      deps: github.com/emicklei/go-restful/v3@v3.11.3
      modroot: .

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      make build-local
      cp kube-state-metrics ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubernetes/kube-state-metrics
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - runs: |
        kube-state-metrics version
