package:
  name: kubescape
  version: 3.0.17
  epoch: 0
  description: Kubescape is an open-source Kubernetes security platform for your IDE, CI/CD pipelines, and clusters. It includes risk analysis, security, compliance, and misconfiguration scanning, saving Kubernetes users and administrators precious time, effort, and resources.
  copyright:
    - license: Apache-2.0 AND MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - git
      - go
      - openssf-compiler-options

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0e846b2dc56e1c02439da27e74aa238d69b12014
      recurse-submodules: "true"
      repository: https://github.com/kubescape/kubescape
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/mholt/archiver/v3@v3.5.1
      replaces: github.com/mholt/archiver/v3=github.com/anchore/archiver/v3@v3.5.2

  - runs: |
      make build
      install -Dm755 ./kubescape ${{targets.destdir}}/usr/bin/kubescape

  - uses: strip

update:
  enabled: true
  github:
    identifier: kubescape/kubescape
    strip-prefix: v

test:
  pipeline:
    - runs: kubescape version
    - uses: test/kwok/cluster
    - name: Verify kubescape scan
      runs: |
        kubescape scan | grep -qi "Compliance Score"
