package:
  name: kubevela
  version: 1.9.13
  epoch: 0
  description: KubeVela is a modern application delivery platform that makes deploying and operating applications across today's hybrid, multi-cloud environments easier, faster and more reliable
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d56da069eb5ee06d9716810e828d6370b93b70ba
      repository: https://github.com/kubevela/kubevela
      tag: v${{package.version}}

  - runs: |
      export CGO_ENABLED=0
      export GO111MODULE=on

  - uses: go/bump
    with:
      deps: github.com/containerd/containerd@v1.7.11 github.com/cloudflare/circl@v1.3.7 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.0 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.21.0 github.com/fluxcd/source-controller/api@v0.30.0 oras.land/oras-go@v1.2.5 golang.org/x/net@v0.23.0 github.com/hashicorp/go-retryablehttp@v0.7.7
      replaces: github.com/go-git/go-git/v5=github.com/go-git/go-git/v5@v5.11.0 github.com/docker/docker=github.com/moby/moby@v24.0.9+incompatible

  - uses: go/build
    with:
      ldflags: -s -w -X github.com/oam-dev/kubevela/version.VelaVersion=${{package.version}}
      output: manager
      packages: ./cmd/core/main.go

  - uses: go/build
    with:
      ldflags: -s -w -X github.com/oam-dev/kubevela/version.VelaVersion=${{package.version}}
      output: vela
      packages: ./references/cmd/cli/main.go

  - uses: strip

update:
  enabled: true
  manual: false
  github:
    identifier: kubevela/kubevela
    strip-prefix: v

test:
  pipeline:
    - name: version check
      runs: vela version
