package:
  name: libgpg-error
  version: "1.50"
  epoch: 2
  description: Support library for libgcrypt
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gettext-dev
      - texinfo

pipeline:
  - uses: git-checkout
    with:
      repository: git://git.gnupg.org/libgpg-error.git
      tag: libgpg-error-${{package.version}}
      expected-commit: bb732615daad9bba9026354ae90f0f5292ea4908

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --disable-nls \
        --enable-static \
        --sysconfdir=/etc \
        --enable-maintainer-mode

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libgpg-error-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libgpg-error
    description: libgpg-error dev

  - name: "libgpg-error-doc"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

update:
  enabled: true
  release-monitor:
    identifier: 1628

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        gpg-error --version
        yat2m --version
