package:
  name: libpaper
  version: 2.2.5
  epoch: 0
  description: Library for handling paper characteristics
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      expected-sha256: 7be50974ce0df0c74e7587f10b04272cd53fd675cb6a1273ae1cc5c9cc9cab09
      uri: https://github.com/rrthomas/libpaper/releases/download/v${{package.version}}/libpaper-${{package.version}}.tar.gz

  - uses: autoconf/configure
    with:
      opts: --disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libpaper-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libpaper
    description: libpaper dev

  - name: libpaper-doc
    pipeline:
      - uses: split/manpages
    description: libpaper manpages

update:
  enabled: true
  github:
    identifier: rrthomas/libpaper
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        paper --version
        paperconf -h
