package:
  name: libpulsar
  version: 3.6.0
  epoch: 0
  description: Optimizer and compiler/toolchain library for WebAssembly
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - abseil-cpp-dev
      - autoconf
      - automake
      - boost-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - curl-dev
      - gmock
      - gtest-dev
      - openssl-dev
      - protobuf-dev
      - python3
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/pulsar-client-cpp
      tag: v${{package.version}}
      expected-commit: aba8d6d618e56df18966ce4d9e8084241a958e0d

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_CXX_STANDARD=17 \
        -DBUILD_TESTS=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: libpulsar-dev
    pipeline:
      - uses: split/dev
    description: libpulsar dev

update:
  enabled: true
  github:
    identifier: apache/pulsar-client-cpp
    strip-prefix: v
