package:
  name: libreoffice-24.2
  version: 24.2.6.2
  epoch: 0
  description:
  # https://www.libreoffice.org/about-us/licenses
  copyright:
    - license: GPL-3.0-only AND LGPL-3.0-only AND MPL-2.0
  resources:
    cpu: 65
    memory: 32Gi
  options:
    no-provides: true
  dependencies:
    runtime:
      - argon2
      - boost
      - cairo
      - cups-libs
      - dbus-libs
      - fontconfig
      - freetype
      - glib
      - gpgme
      - libcurl-openssl4
      - libfontconfig1
      - liblangtag
      - libnspr
      - libnss
      - libstdc++
      - libx11
      - libxext
      - libxml2
      - libxslt
      - zlib
    provides:
      - libreoffice=${{package.full-version}}

environment:
  contents:
    packages:
      - ant
      - argon2-dev
      - autoconf
      - automake
      - bash
      - bison
      - boost-dev
      - build-base
      - busybox
      - cairo-dev
      - coreutils
      - cups-dev
      - curl
      - curl-dev
      - dbus-dev
      - diffutils
      - expat-dev
      - flex
      - fontconfig-dev
      - freetype-dev
      - fribidi-dev
      - glib-dev
      - gnutar
      - gperf
      - gpgme-dev
      - gst-plugins-base-dev
      - gstreamer-dev
      - gtk-3-dev
      - harfbuzz-dev
      - krb5-dev
      - libassuan-dev
      - libatk-1.0
      - libatk-bridge-2.0
      - libcmis-dev
      - libice-dev
      - liblangtag-dev
      - libnspr-dev
      - libnss-dev
      - libsm-dev
      - libtool
      - libx11-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxdamage-dev
      - libxft-dev
      - libxml2-dev
      - libxrandr-dev
      - libxrender
      - libxslt-dev
      - libxt-dev
      - libxtst-dev
      - m4
      - mesa-dev
      - mesa-egl
      - mesa-gl
      - nasm
      - openjdk-17
      - openjdk-17-default-jvm
      - openssl-dev
      - orc-dev
      - pango-dev
      - patch
      - perl
      - pkgconf
      - pkgconf-dev
      - python-3.11
      - python-3.11-dev
      - zip
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/LibreOffice/core
      tag: libreoffice-${{package.version}}
      expected-commit: ef66aa7e36a1bb8e65bfbc63aba53045a14d0871

  - uses: patch
    with:
      patches: 2b27f0eb5858a4fd296170fb7e4533e5fc7aa3e9.patch # fix build issue with xml2, this patch is in main upstream but not released yet

  - runs: |
      cat > autogen.input <<EOF
      --with-jdk-home=$JAVA_HOME
      --enable-python=system
      --enable-split-debug
      --prefix=/usr
      --with-system-argon2
      --with-system-libcmis
      --with-system-expat
      --with-system-gpgmepp
      --with-system-liblangtag
      --with-system-openssl
      --with-system-cairo
      --with-system-zlib
      --with-system-boost
      --with-system-curl
      --host=${{host.triplet.gnu}}
      --build=${{host.triplet.gnu}}
      --without-junit
      --without-galleries
      EOF
      ./autogen.sh
      sed -i 's/bootstrap: check-if-root/bootstrap: /g' Makefile.in

  - runs: make -j$(nproc)

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev

update:
  enabled: true
  ignore-regex-patterns:
    - 'cp-*'
    - 'co-*'
    - 'cib-*'
    - 'mimo-*'
  github:
    identifier: LibreOffice/core
    use-tag: true
    strip-prefix: libreoffice-
    tag-filter-prefix: libreoffice-24.2

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        /usr/lib/libreoffice/program/soffice.bin --help
