package:
  name: libsolv
  version: 0.7.30
  epoch: 1
  description: Library for solving packages and reading repositories
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - openssf-compiler-options
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openSUSE/libsolv
      expected-commit: 27aa6a72c7db73d78aa711ae412231768e77c9e0
      tag: ${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DENABLE_CONDA=ON \

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: libsolv-dev
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/
          mv "${{targets.destdir}}"/usr/share/cmake "${{targets.subpkgdir}}"/usr/lib/
    description: libsolv dev

  - name: libsolv-doc
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: openSUSE/libsolv
    use-tag: true
    tag-filter: "0."

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        conda2solv -h
        dumpsolv -h
        mergesolv --version
        repo2solv -h
