package:
  name: lighttpd
  version: 1.4.76
  epoch: 0
  description: Secure, fast, compliant and very flexible web-server
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - brotli-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - e2fsprogs
      - flex
      - libdbi-dev
      - libtool
      - libxml2-dev
      - linux-pam-dev
      - lua5.4-dev
      - m4
      - openldap-dev
      - openssl-dev
      - pcre-dev
      - pcre2-dev
      - pkgconf-dev
      - readline-dev
      - sqlite-dev
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: fetch
    with:
      uri: https://download.lighttpd.net/lighttpd/releases-1.4.x/lighttpd-${{package.version}}.tar.xz
      expected-sha512: 940f00f2d84e3424c389108d09756a0af41db3559474135b6c502deccd08ad051b5184f3f7907436384964d2b05045e27dca463af98c889cee69b0ae6e202782

  - runs: |
      ./autogen.sh
      mkdir -p "${{targets.destdir}}"/var/tmp

  - uses: autoconf/configure
    with:
      opts: |
        --with-ldap \
        --with-pam \
        --with-attr \
        --with-openssl \
        --with-webdav-props \
        --with-webdav-locks \
        --with-lua \
        --with-pcre2 \
        --with-brotli \
        --with-zstd \
        --with-dbi

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 1817

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        lighttpd -v
        lighttpd-angel --version
