package:
  name: local-path-provisioner
  version: 0.0.29
  epoch: 1
  description: Dynamically provisioning persistent local storage with Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - busybox
      - zlib

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/local-path-provisioner
      tag: v${{package.version}}
      expected-commit: 7a64e376245fcfd57d5d8a9ba6ab04f10f39f68e

  - uses: go/build
    with:
      packages: .
      output: local-path-provisioner
      ldflags: -w -X main.VERSION=${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: rancher/local-path-provisioner
    strip-prefix: v

test:
  pipeline:
    - runs: |
        set +e
        output=$(local-path-provisioner --debug start 2>&1)
        set -e
        echo "$output" | grep "unable to get client config" # Kubeconfig will be provided on runtime
