package:
  name: management-api-for-apache-cassandra-4.1
  version: 0.1.86
  epoch: 0
  description: RESTful / Secure Management Sidecar for Apache Cassandra
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - procps
    provides:
      - management-api-for-apache-cassandra=${{package.full-version}}

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - maven
      - openjdk-11
      - openjdk-11-default-jvm
  environment:
    JAVA_HOME: /usr/lib/jvm/java-11-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k8ssandra/management-api-for-apache-cassandra
      expected-commit: 1822715aba5cc5e475b8ac7a7a470ba70824eac2
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: upgrade-deps.patch GHSA-5jpm-x58v-624v.patch

  - runs: |
      MAAC_PATH="${{targets.contextdir}}"/opt/management-api
      mkdir -p "${{targets.contextdir}}"/usr/local/bin
      mkdir -p "${{targets.contextdir}}"/opt/management-api
      mvn -q -ff package -Dskip.surefire.tests -DskipTests -DskipOpenApi

      cp ./cassandra/scripts/docker-entrypoint.sh "${{targets.contextdir}}"/usr/local/bin/
      find . -type f -name "datastax-*.jar" -exec mv -t $MAAC_PATH -i '{}' +
      chmod +x "${{targets.contextdir}}"/usr/local/bin/docker-entrypoint.sh

subpackages:
  - name: ${{package.name}}-compat
    dependencies:
      # Backwards compatibility with previous package name.
      provides:
        - management-api-for-apache-cassandra-compat=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/opt/management-api
          mkdir -p ${{targets.contextdir}}/bin
          ln -s /opt/management-api/datastax-mgmtapi-agent-4.1.x-0.1.0-SNAPSHOT.jar ${{targets.contextdir}}/opt/management-api/datastax-mgmtapi-agent.jar
          ln -s /opt/management-api/datastax-mgmtapi-server-0.1.0-SNAPSHOT.jar ${{targets.contextdir}}/opt/management-api/datastax-mgmtapi-server.jar
          ln -sf /usr/local/bin/docker-entrypoint.sh ${{targets.contextdir}}/docker-entrypoint.sh

          # the reason why we need to do this is because the java code hard-codes /bin/ps
          ln -s /usr/bin/ps ${{targets.contextdir}}/bin/ps
          # the reason why we need to do this is because the java code hard-codes /bin/which
          ln -s /usr/bin/which ${{targets.contextdir}}/bin/which

update:
  enabled: true
  github:
    identifier: k8ssandra/management-api-for-apache-cassandra
    # Upstream doesn't use tags to differentiate between supported cassandra
    # releases. Each new tag cut supports multiple Cassandra versions.
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - management-api-for-apache-cassandra-compat
        - openjdk-11
        - openjdk-11-default-jvm
  pipeline:
    - runs: |
        java -jar /opt/management-api/datastax-mgmtapi-server.jar --help
