package:
  name: mc
  version: 0.20240916.174314
  epoch: 0
  description: Multi-Cloud Object Storage
  copyright:
    - license: AGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - perl

var-transforms:
  - from: ${{package.version}}
    match: ^0\.(\d{4})(\d{2})(\d{2})\.(\d{2})(\d{2})(\d{2})$
    replace: RELEASE.${1}-${2}-${3}T${4}-${5}-${6}Z
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/minio/mc
      tag: ${{vars.mangled-package-version}}
      expected-commit: 11ebe952ea30e426e564f66e78d178465ae7c432

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv mc ${{targets.destdir}}/usr/bin

  - uses: strip

subpackages:
  - name: mc-bitnami-2024-compat
    description: "compat package with bitnami/minio-client image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: minio-client
          version-path: 2024/debian-12
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/minio-client/bin/
          chmod g+rwX ${{targets.subpkgdir}}/opt/bitnami
          # Use package path while unpacking
          find ${{targets.subpkgdir}}/opt/bitnami -iname "*.sh" -exec sh -c '
              sed -i "s#/opt/bitnami#${{targets.subpkgdir}}/opt/bitnami#g" "$1"
              sed -i "s#\"/bitnami\"#\"${{targets.subpkgdir}}/bitnami\"#g" "$1"
              sed -i "s#\"/certs\"#\"${{targets.subpkgdir}}/certs\"#g" "$1"
              sed -i "s#/bitnami/minio-client/data#${{targets.subpkgdir}}/bitnami/minio-client/data#g" "$1"
              sed -i "s#/.mc#${{targets.subpkgdir}}/.mc#g" "$1"
          ' sh {} \;
            ${{targets.subpkgdir}}/opt/bitnami/scripts/minio-client/postunpack.sh || true
          # Restore path
          find ${{targets.subpkgdir}}/opt/bitnami -type f -exec sed 's#${{targets.subpkgdir}}##g' -i {} \;

update:
  enabled: true
  version-transform:
    - match: ^RELEASE\.(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})-(\d{2})Z$
      replace: 0.${1}${2}${3}.${4}${5}${6}
  github:
    identifier: minio/mc
    use-tag: true

test:
  pipeline:
    - runs: |
        mc --version
    - runs: |
        mc ls
