package:
  name: meilisearch
  version: 1.10.2
  epoch: 0
  description: "A lightning-fast search engine that fits effortlessly into your apps, websites, and workflow."
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/meilisearch/meilisearch.git
      expected-commit: 885b9f07b10ce7c22cbbbe0d6f3468ad1fbc4fd4
      tag: v${{package.version}}
      recurse-submodules: true

  - name: Configure and build
    runs: |
      cargo update --precise 0.3.36 --package time
      cargo build --release --locked -vv
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/meilisearch ${{targets.destdir}}/usr/bin/

  - uses: strip

update:
  enabled: true
  github:
    identifier: meilisearch/meilisearch
    strip-prefix: v

test:
  pipeline:
    - runs: |
        meilisearch --version
