package:
  name: memcached-exporter
  version: 0.14.4
  epoch: 2
  description: Exports metrics from memcached servers for consumption by Prometheus.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/prometheus/memcached_exporter
      tag: v${{package.version}}
      expected-commit: 277c78894347b087cae7fa34a2f550b677f8e383

  - uses: go/build
    with:
      packages: ./cmd/memcached_exporter
      output: memcached_exporter
      ldflags: -s -w

  - uses: strip

subpackages:
  - name: memcached-exporter-bitnami-compat
    description: "compat package with bitnami/memcached-exporter image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: memcached-exporter
          version-path: 0/debian-12

update:
  enabled: true
  github:
    identifier: prometheus/memcached_exporter
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        memcached_exporter --version
