package:
  name: mercurial
  version: 6.8.1
  epoch: 0
  description: "Scalable distributed SCM tool"
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - gettext-dev
      - py3-flit-core
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3
      - python3-dev
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.mercurial-scm.org/release/mercurial-${{package.version}}.tar.gz
      expected-sha256: 030e8a7a6d590e4eaeb403ee25675615cd80d236f3ab8a0b56dcc84181158b05

  - runs: |
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2

      python3 -m installer -d "${{targets.destdir}}" \
        dist/*.whl

      install -Dm755 contrib/hgk contrib/hg-ssh hgeditor -t "${{targets.destdir}}"/usr/bin

      for man in doc/*.?; do
        install -Dm644 "$man" \
          "${{targets.destdir}}"/usr/share/man/man${man##*.}/${man##*/}
      done

  - uses: strip

subpackages:
  - name: "mercurial-doc"
    description: "mercurial documentation"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  release-monitor:
    identifier: 1969

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        hg --version
