package:
  name: meson
  version: 1.5.2
  epoch: 0
  description: Fast and user friendly build system
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - samurai

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - py3-setuptools
      - python3
      - samurai

pipeline:
  - uses: fetch
    with:
      expected-sha256: f955e09ab0d71ef180ae85df65991d58ed8430323de7d77a37e11c9ea630910b
      uri: https://github.com/mesonbuild/meson/releases/download/${{package.version}}/meson-${{package.version}}.tar.gz

  - uses: py/pip-build-install

subpackages:
  - name: meson-doc
    pipeline:
      - uses: split/manpages
    description: meson manpages

update:
  enabled: true
  release-monitor:
    identifier: 6472

test:
  environment:
    contents:
      packages:
        - build-base
  pipeline:
    - runs: |
        meson --version | grep ${{package.version}}
    - runs: |
        mkdir -p /tmp
        cd /tmp
        cat <<'EOF' >> /tmp/main.c
        #include <stdio.h>

        //
        // main is where all program execution starts
        //
        int main(int argc, char **argv) {
        printf("Hello Wolfi.\n");
        return 0;
        }

        EOF
        cat <<'EOF'>> /tmp/meson.build
        project('tutorial', 'c')
        executable('demo', 'main.c')
        EOF

        CC=gcc meson setup builddir
        cd builddir
        meson compile
        ./demo
