package:
  name: mimalloc
  version: 1.8.7
  epoch: 2
  description: "A compact general purpose allocator with excellent performance"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssf-compiler-options
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/microsoft/mimalloc
      tag: v${{package.version}}
      expected-commit: 1f3ecec2e589deabad4fed62853b8bca53ec00e3

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

subpackages:
  - name: "mimalloc-dev"
    description: "headers for mimalloc"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - mimalloc

test:
  environment:
    contents:
      packages:
        - wolfi-base
        - stress-ng
  pipeline:
    - runs: |
        LD_PRELOAD=/usr/lib/libmimalloc.so.1 stress-ng --vdso 1 -t 5 --metrics

update:
  enabled: true
  github:
    identifier: microsoft/mimalloc
    strip-prefix: v
    tag-filter: v1.
    use-tag: true
