package:
  name: minio-operator
  version: 6.0.3
  epoch: 1
  description: Minio Operator creates/configures/manages Minio on Kubernetes
  copyright:
    - license: AGPL-3.0-only

environment:
  contents:
    packages:
      - bash
      - build-base
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/minio/operator
      tag: v${{package.version}}
      expected-commit: 45110b9d7e63caa857daa63776c05dd6a5d7e9d9

  - uses: go/build
    with:
      modroot: ./cmd/operator
      packages: .
      output: minio-operator
      ldflags: -s -w -X github.com/minio/operator/pkg.ReleaseTag=${{package.full-version}} -X github.com/minio/operator/pkg.Version=${{package.full-version}} -X github.com/minio/operator/pkg.ShortCommitID=$(git rev-parse HEAD)

  - uses: strip

  - runs: |
      mkdir ${{targets.destdir}}/licenses
      cp CREDITS LICENSE ${{targets.destdir}}/licenses/

subpackages:
  - name: ${{package.name}}-compat
    description: compatibility symlinks package for minio-operator Dockerfile
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/
          ln -sf /usr/bin/minio-operator ${{targets.contextdir}}/minio-operator

update:
  enabled: true
  github:
    identifier: minio/operator
    strip-prefix: v

# comprehensive test with kwok and minio's kustomize want ephemeral storage, so just check version here
test:
  pipeline:
    - runs: minio-operator --version
