package:
  name: mockgen
  version: 0.4.0
  epoch: 1
  description: GoMock is a mocking framework for the Go programming language.
  url: https://github.com/uber-go/mock
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/uber-go/mock
      tag: v${{package.version}}
      expected-commit: 74a29c6e6c2cbb8ccee94db061c1604ff33fd188

  - uses: go/build
    with:
      output: mockgen
      packages: ./mockgen

  - uses: strip

update:
  enabled: true
  github:
    identifier: uber-go/mock
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - wolfi-base
  pipeline:
    - runs: |
        mockgen --version
