package:
  name: mold
  version: 2.34.0
  epoch: 0
  description: "mold linker"
  copyright:
    - license: MIT
  resources:
    cpu: 10
    memory: 8Gi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - libtbb-dev
      - mimalloc2-dev
      - openssl-dev
      - samurai
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rui314/mold
      tag: v${{package.version}}
      expected-commit: ed7cc1b85aed2ba14fdcf868228e2f704d45ae6c

  - name: 'Configure mold'
    runs: |
      cmake -B build -G Ninja \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DMOLD_LTO=ON \
        -DMOLD_USE_SYSTEM_MIMALLOC=ON \
        -DMOLD_USE_SYSTEM_TBB=ON \
        -DBUILD_TESTING="OFF"

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info

  - uses: strip

update:
  enabled: true
  github:
    identifier: rui314/mold
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        ld.mold --version
        mold --version
