package:
  name: mtr
  version: 0.95
  epoch: 1
  description: Full screen ncurses traceroute tool
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gtk-2.0-dev
      - jansson-dev
      - libcap-dev
      - ncurses-dev
      - pkgconf-dev
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/traviscross/mtr.git
      tag: v${{package.version}}
      expected-commit: 852e5617fbf331cf292723702161f0ac9afe257c

  - runs: ./bootstrap.sh

  - runs: |
      mkdir -p mtr curses gtk
      ./bootstrap.sh
      export GIT_DIR="."
      cd ./curses
      ../configure --prefix=/usr \
      	--without-gtk
      make
      cd ../gtk
      ../configure --prefix=/usr \
      	--with-gtk \
      	--program-suffix=-gtk
      make
      unset GIT_DIR

  - runs: |
      cd ./curses
      make DESTDIR="${{targets.destdir}}" install
      cd ../gtk
      make DESTDIR="${{targets.destdir}}" install
      mkdir -p "${{targets.destdir}}"/usr/share/applications
      install -D -m 644 ../mtr-gtk.desktop \
      	"${{targets.destdir}}"/usr/share/applications/mtr-gtk.desktop
      install -D -m 644 ../img/mtr_icon.xpm \
      	"${{targets.destdir}}"/usr/share/pixmaps/mtr_icon.xpm

subpackages:
  - name: "mtr-doc"
    description: "mtr documentation"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

  - name: "gtk"
    description: "The GTK+ interface for mtr"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/sbin "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/sbin/mtr*-gtk "${{targets.subpkgdir}}"/usr/sbin/
          mv "${{targets.destdir}}"/usr/share/applications "${{targets.subpkgdir}}"/usr/share/
          mv "${{targets.destdir}}"/usr/share/pixmaps "${{targets.subpkgdir}}"/usr/share/

  - name: "mtr-bash-completion"
    description: "bash completion for mtr"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/bash-completion
          mv "${{targets.destdir}}"/usr/share/bash-completion/completions \
          		"${{targets.subpkgdir}}"/usr/share/bash-completion
          rm -rf "${{targets.destdir}}"/usr/share/bash-completion

update:
  enabled: true
  github:
    identifier: traviscross/mtr
    tag-filter-prefix: v
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        mtr --version
        mtr-packet --version
