package:
  name: multus-cni
  version: 4.1.1
  epoch: 0
  description: A CNI meta-plugin for multi-homed pods in Kubernetes
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k8snetworkplumbingwg/multus-cni
      tag: v${{package.version}}
      expected-commit: f1e887e2396c98e9aee6417723f2c5cd433a1cd2

  - uses: go/build
    with:
      packages: ./cmd/multus
      ldflags: -X 'gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/multus.version=${{package.version}}'
      output: multus

  - uses: go/build
    with:
      packages: ./cmd/multus-daemon
      ldflags: -X 'gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/multus.version=${{package.version}}'
      output: multus-daemon

  - uses: go/build
    with:
      packages: ./cmd/multus-shim
      ldflags: -X 'gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/multus.version=${{package.version}}'
      output: multus-shim

  - uses: go/build
    with:
      packages: ./cmd/install_multus
      ldflags: -X 'gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/multus.version=${{package.version}}'
      output: install_multus

  - uses: go/build
    with:
      packages: ./cmd/thin_entrypoint
      ldflags: -X 'gopkg.in/k8snetworkplumbingwg/multus-cni.v4/pkg/multus.version=${{package.version}}'
      output: thin_entrypoint

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/src/multus-cni/bin
          ln -sf /usr/bin/multus ${{targets.contextdir}}/usr/src/multus-cni/bin/multus
          ln -sf /usr/bin/multus-shim ${{targets.contextdir}}/usr/src/multus-cni/bin/multus-shim
          ln -sf /usr/bin/multus-daemon ${{targets.contextdir}}/usr/src/multus-cni/bin/multus-daemon
          ln -sf /usr/bin/install_multus ${{targets.contextdir}}/install_multus
          ln -s /usr/bin/thin_entrypoint ${{targets.contextdir}}/thin_entrypoint

update:
  enabled: true
  github:
    identifier: k8snetworkplumbingwg/multus-cni
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - multus-cni-compat
  pipeline:
    - runs: |
        multus -version
        multus-daemon -h
        multus-shim -h
    - name: "Check compat paths"
      runs: |
        /usr/src/multus-cni/bin/multus -version
        /usr/src/multus-cni/bin/multus-shim -version
        /usr/src/multus-cni/bin/multus-daemon -help
        /thin_entrypoint --multus-log-level info
