package:
  name: nats-server
  version: 2.10.21
  epoch: 0
  description: High-Performance server for NATS.io, the cloud and edge native messaging system.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires a specific go version
  - uses: git-checkout
    with:
      repository: https://github.com/nats-io/nats-server
      tag: v${{package.version}}
      expected-commit: d3a8868e9ddadb2556cddcd99f02d6ed1df11d23

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mkdir -p ${{targets.destdir}}/etc/nats
      go build \
        -ldflags "-w -X github.com/nats-io/nats-server/v2/server.gitCommit=$(git rev-parse HEAD)" \
        -o ${{targets.destdir}}/usr/bin/nats-server \
        .
      mv docker/nats-server.conf ${{targets.destdir}}/etc/nats/nats-server.conf

  - uses: strip

update:
  enabled: true
  github:
    identifier: nats-io/nats-server
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        nats-server --version
