#nolint:git-checkout-must-use-github-updates,valid-pipeline-git-checkout-tag
package:
  name: neuvector-sigstore-interface
  version: 0_git20240801
  epoch: 2
  description: NeuVector sigstore interface for the SUSE NeuVector Container Security Platform
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/neuvector/sigstore-interface
      expected-commit: 96da0529724951cd26b1568a980d66b991353976

  - uses: go/bump
    with:
      deps: github.com/sigstore/cosign/v2@v2.2.4 github.com/hashicorp/go-retryablehttp@v0.7.7
      modroot: .

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: sigstore-interface
      prefix: usr/local
      vendor: true

  - uses: strip

test:
  pipeline:
    - runs: |
        sigstore-interface --help

update:
  manual: true
  exclude-reason: No releases or tags
