package:
  name: nfs-utils
  version: 2.7.1
  epoch: 0
  description: kernel-mode NFS
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - busybox
      - python3

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - keyutils-dev
      - libcap-dev
      - libevent-dev
      - libseccomp-dev
      - libtirpc-dev
      - libtool
      - libxml2-dev
      - lvm2-dev
      - openldap-dev
      - pkgconf-dev
      - sqlite-dev
      - util-linux-dev

pipeline:
  - uses: fetch
    with:
      uri: https://www.kernel.org/pub/linux/utils/nfs-utils/${{package.version}}/nfs-utils-${{package.version}}.tar.xz
      expected-sha512: ce2841e6db209c889677483893ae14080ebb0d9738e2bf18d043a47ccc6493f0b585dce3d049c25a0a6dde5beeb84cf79154969357040685f819281a698d6bda

  - runs: ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --without-tcp-wrappers \
        --with-rpcgen=internal \
        --enable-ipv6 \
        --enable-nfsv4 \
        --enable-uuid \
        --enable-gss \
        --enable-svcgss \
        --enable-libmount-mount

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: "headers for ${{package.name}}"
    pipeline:
      - uses: split/dev

  - name: ${{package.name}}-static
    description: "${{package.name}} static library"
    pipeline:
      - uses: split/static

  - name: ${{package.name}}-doc
    description: "${{package.name}} manpages"
    pipeline:
      - uses: split/manpages

  - name: ${{package.name}}-db
    description: "${{package.name}} debug symbols"
    pipeline:
      - uses: split/debug

  - name: rpcgen
    description: Remote Procedure Call (RPC) protocol compiler
    pipeline:
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/rpcgen "${{targets.contextdir}}"/usr/bin

update:
  enabled: true
  release-monitor:
    identifier: 2081

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        mount.nfs --version
        mount.nfs4 --version
        blkmapd version
        exportfs -v
        mountstats --version
        nfsdcld --version
        nfsdclddb --help
        nfsidmap -h
        nfsiostat --version
        nfsstat --version
        rpc.idmapd -h
        rpc.mountd --version
        rpc.statd --version
        rpcdebug -h
        showmount --version
