package:
  name: nftables
  version: 1.1.0
  epoch: 0
  description: Netfilter tables userspace tools
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - asciidoc
      - autoconf
      - automake
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - flex
      - gmp-dev
      - jansson-dev
      - libedit-dev
      - libmnl-dev
      - libnftnl-dev
      - ncurses-dev
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - readline-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: ef3373294886c5b607ee7be82c56a25bc04e75f802f8e8adcd55aac91eb0aa24
      uri: https://netfilter.org/projects/nftables/files/nftables-${{package.version}}.tar.xz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: nftables-static
    pipeline:
      - uses: split/static
    description: nftables static

  - name: nftables-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - nftables
    description: nftables dev

  - name: nftables-doc
    pipeline:
      - uses: split/manpages
    description: nftables manpages

update:
  enabled: true
  release-monitor:
    identifier: 2082

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        nft --version
