package:
  name: nri-nginx
  version: 3.4.10
  epoch: 0
  description: New Relic Infrastructure Nginx Integration
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-nginx
      expected-commit: a17dd45da7749494ac863fcbe462462ba3a09f15
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-nginx
      ldflags: -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/nginx-definition.yml ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/nginx-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-nginx
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        nri-nginx --help
