package:
  name: nri-memcached
  version: 2.5.8
  epoch: 0
  description: New Relic Infrastructure memcached Integration
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-memcached
      expected-commit: cddce3d45ff7ddcaff06191215fabe02cd93d686
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-memcached
      ldflags: -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/memcached-definition.yml ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/memcached-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-memcached
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        nri-memcached --help
