package:
  name: nri-mssql
  version: 2.12.8
  epoch: 0
  description: New Relic Infrastructure Mssql Integration
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/newrelic/nri-mssql
      expected-commit: c860447351e9be32b1e0cc3963a2f6c42280c913
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: .
      packages: ./src/
      output: nri-mssql
      ldflags: -s -w

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by newrelic-infrastructure-bundle"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin
          ln -sf /usr/bin/${{package.name}} ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/bin/${{package.name}}
          install -Dm644 legacy/mssql-definition.yml ${{targets.subpkgdir}}/var/db/newrelic-infra/newrelic-integrations/mssql-definition.yml

update:
  enabled: true
  github:
    identifier: newrelic/nri-mssql
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        nri-mssql --help
