package:
  name: ocamlbuild
  version: 0.15.0
  epoch: 0
  description: "Generic build tool with built-in rules for building OCaml library and programs"
  copyright:
    - license: LGPL-2.0-only WITH OCaml-LGPL-linking-exception

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ocaml

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ocaml/ocamlbuild
      tag: ${{package.version}}
      expected-commit: af319408376aae66dffcf7d31c6926aef19f4f84

  - runs: |
      make configure \
        OCAML_NATIVE=true \
        OCAMLBUILD_BINDIR=/usr/bin \
        OCAMLBUILD_LIBDIR=/usr/lib/ocaml

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      cd ${{targets.destdir}}
      # Remove annotation files.
      rm -f usr/lib/ocaml/${{package.name}}/*.cmt*

      # Keep only native binary.
      cd usr/bin
      rm ocamlbuild.byte
      mv ocamlbuild.native ocamlbuild

  - uses: strip

update:
  enabled: true
  github:
    identifier: ocaml/ocamlbuild

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        ocamlbuild --version
