package:
  name: ocaml
  version: 5.2.0
  epoch: 0
  description: "The core OCaml system: compilers, runtime system, base libraries"
  copyright:
    - license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception

environment:
  contents:
    packages:
      - binutils-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - gdbm-dev
      - ncurses-dev
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ocaml/ocaml
      tag: ${{package.version}}
      expected-commit: 74a76cc2f2588eb18a443a60918f040838292ac7

  - runs: |
      ./configure \
        --host ${{host.triplet.gnu}} \
        --build ${{host.triplet.gnu}} \
        --target ${{host.triplet.gnu}} \
        --prefix /usr \
        --bindir /usr/bin \
        --libdir /usr/lib/ocaml \
        --mandir /usr/share/man \
        CC="${CC:-gcc}" \
        AS="${CC:-gcc} -c" \
        ASPP="${CC:-gcc} -c"

  - uses: autoconf/make
    with:
      opts: world.opt

  - uses: autoconf/make-install

  - runs: |
      cd ${{targets.destdir}}
      # Remove annotation files and sources.
      find usr/lib/ocaml \
        \( -name '*.cmt' -o -name '*.cmti' -o -name '*.ml' \) \
        -a -delete

      # To be consistent with other binaries.
      mv usr/bin/ocamldoc usr/bin/ocamldoc.byte
      ln -s ocamldoc.opt usr/bin/ocamldoc

  - uses: strip

subpackages:
  - name: ocamldoc
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mkdir -p ${{targets.subpkgdir}}/usr/lib/ocaml
          mv ${{targets.destdir}}/usr/bin/ocamldoc ${{targets.subpkgdir}}/usr/bin/
          mv ${{targets.destdir}}/usr/lib/ocaml/ocamldoc ${{targets.subpkgdir}}/usr/lib/ocaml/

  - name: "ocaml-dev"
    description: "headers for ocaml"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/*.byte ${{targets.subpkgdir}}/usr/bin
    dependencies:
      runtime:
        - ocaml

  - name: "ocaml-compiler-libs"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv ${{targets.destdir}}/usr/lib/ocaml/compiler-libs "${{targets.subpkgdir}}"/usr/lib/ocaml

update:
  enabled: true
  github:
    identifier: ocaml/ocaml

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        ocaml --version
        ocamlc --version
        ocamlc.opt --version
        ocamlcmt --help
        ocamlcp --version
        ocamldebug --help
        ocamldep --help
        ocamldep.opt --help
        ocamldoc.opt --version
        ocamllex --help
        ocamllex.opt --help
        ocamlmklib --version
        ocamlmktop --version
        ocamlobjinfo --help
        ocamlobjinfo.opt --help
        ocamlopt --version
        ocamlopt.opt --version
        ocamloptp --version
        ocamlprof --help
        ocamlrun --help
        ocamlrund --help
        ocamlruni --help
