package:
  name: octo-sts
  version: 0.4.2
  epoch: 1
  description: A GitHub App that acts like a Security Token Service (STS) for the Github API.
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      destination: octo-sts
      expected-commit: 9b40e7d8a65c03a1576bb46b989dff040042387e
      repository: https://github.com/octo-sts/app
      tag: v${{package.version}}

  - uses: go/build
    with:
      modroot: octo-sts
      output: octo-sts
      packages: ./cmd/app

subpackages:
  - name: "octo-sts-webhook"
    description: "OctoSTS Validation Webhook"
    pipeline:
      - uses: go/build
        with:
          modroot: octo-sts
          output: webhook
          packages: ./cmd/webhook

update:
  enabled: true
  github:
    identifier: octo-sts/app
    strip-prefix: v
