package:
  name: onetbb
  version: 2021.13.0
  epoch: 1
  description: oneAPI Threading Building Blocks
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - hwloc-dev
      - linux-headers
      - py3-setuptools
      - python3-dev
      - samurai
      - swig

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 1c4c93fc5398c4a1acb3492c02db4699f3048dea
      repository: https://github.com/oneapi-src/oneTBB
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DTBB4PY_BUILD=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: py3-tbb
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/python* "${{targets.subpkgdir}}"/usr/lib/
    description: onetbb FIXME

  - name: onetbb-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - onetbb
        - linux-headers
    description: onetbb dev

  - name: onetbb-doc
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/doc/TBB
          mv "${{targets.destdir}}"/usr/share/doc/TBB/README.md "${{targets.subpkgdir}}"/usr/share/doc/TBB/README.md
    description: onetbb readme

update:
  enabled: true
  ignore-regex-patterns:
    - -rc
  github:
    identifier: oneapi-src/oneTBB
    strip-prefix: v
    tag-filter: v
    use-tag: true
