package:
  name: openssl
  version: 3.3.2
  epoch: 0
  description: "the OpenSSL cryptography suite"
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 16
    memory: 16Gi
  # For now, continue to install the legacy openssl provider if the parent openssl
  # package is installed.  This is done because users may be installing the openssl
  # package to gain that provider.
  dependencies:
    runtime:
      - openssl-provider-legacy

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssf-compiler-options
      - perl
  environment:
    # Using openssf-compiler-options instead
    CFLAGS: ""
    CPPFLAGS: ""
    CXXFLAGS: ""
    LDFLAGS: ""

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openssl/openssl.git
      tag: openssl-${{package.version}}
      expected-commit: fb7fab9fa6f4869eaa8fbb97e0d593159f03ffe4

  - name: Configure and build
    runs: |
      export CC=${{host.triplet.gnu}}-gcc
      export CXX=${{host.triplet.gnu}}-g++
      export CPP=${{host.triplet.gnu}}-cpp

      perl ./Configure \
         linux-$(uname -m) \
         --prefix=/usr \
         --libdir=lib \
         --openssldir=/etc/ssl \
         enable-ktls \
         shared \
         no-zlib \
         no-async \
         no-comp \
         no-idea \
         no-mdc2 \
         no-rc5 \
         no-ec2m \
         no-sm2 \
         no-sm4 \
         no-ssl3 \
         no-seed \
         no-weak-ssl-ciphers \
         -Wa,--noexecstack
      perl configdata.pm --dump
      make -j$(nproc)

  - uses: autoconf/make-install

  - runs: |
      rm ${{targets.destdir}}/usr/bin/c_rehash
      # Effectively no-op config file, which matches fallback behaviour
      # The CA cert generation options are not fit for any certs
      rm ${{targets.destdir}}/etc/ssl/openssl.cnf
      # Second identical copy of the above
      rm ${{targets.destdir}}/etc/ssl/openssl.cnf.dist
      # Empty CT log
      rm ${{targets.destdir}}/etc/ssl/ct_log_list.cnf
      # Second copy of CT log
      rm ${{targets.destdir}}/etc/ssl/ct_log_list.cnf.dist
      # Keeping etc/ssl/misc CA.pl & tsget perl scripts
      # without depending on perl, here in openssl package
      # This now makes openssl-config empty package, remove it
      # This also removes the need to have things coupled with
      # openssl-config-fipshardened going forward.

  - uses: strip

data:
  - name: engines
    items:
      afalg: Linux AF_ALG engine
      capi: CAPI engine
      padlock: VIA Padlock engine

subpackages:
  - name: "openssl-doc"
    description: "OpenSSL documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share

  - name: "libcrypto3"
    description: "OpenSSL libcrypto library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libcrypto.so.3 "${{targets.subpkgdir}}"/usr/lib

  - name: "libssl3"
    description: "OpenSSL libssl library"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libssl.so.3 "${{targets.subpkgdir}}"/usr/lib

  - name: "openssl-dev"
    description: "OpenSSL headers"
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf

  - range: engines
    name: "openssl-engine-${{range.key}}"
    description: "OpenSSL ${{range.value}}"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/engines-3
          mv "${{targets.destdir}}"/usr/lib/engines-3/${{range.key}}.so "${{targets.subpkgdir}}"/usr/lib/engines-3/

  - name: "openssl-engine-loader-attic"
    description: "OpenSSL Loader Attic internal test engine"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/engines-3
          mv "${{targets.destdir}}"/usr/lib/engines-3/loader_attic.so "${{targets.subpkgdir}}"/usr/lib/engines-3/

  - name: "openssl-provider-legacy"
    description: "OpenSSL legacy provider"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/ossl-modules
          mv "${{targets.destdir}}"/usr/lib/ossl-modules/legacy.so "${{targets.subpkgdir}}"/usr/lib/ossl-modules/

test:
  environment:
    contents:
      packages:
        - curl
        - git
        - wget
  pipeline:
    - uses: test/hardening-check
      with:
        package-match: "^openssl$\\|libssl3\\|libcrypto3"
    - name: Verify curl still works
      runs: |
        curl -I https://github.com/openssl/openssl
        ! curl https://expired.badssl.com/
    - name: Verify git still works
      runs: |
        git ls-remote --exit-code https://github.com/openssl/openssl refs/tags/openssl-${{package.version}}
    - name: Verify wget still works
      runs: |
        wget -O /dev/null https://github.com/openssl/openssl
        ! wget https://expired.badssl.com/

update:
  enabled: true
  github:
    identifier: openssl/openssl
    strip-prefix: openssl-
    tag-filter-prefix: openssl-
