package:
  name: openssf-compiler-options
  version: 20240627
  epoch: 2
  description: "Compiler Options Hardening Guide for C and C++"
  url: https://best.openssf.org/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.html
  copyright:
    - license: CC-BY-4.0

environment:
  contents:
    packages:
      - busybox

pipeline:
  - name: Install
    runs: |
      mkdir -p "${{targets.destdir}}"
      cp -r etc usr "${{targets.destdir}}"
      for i in 15 16 17 18; do
        ln -s clang "${{targets.destdir}}"/etc/clang-$i
      done
      cd ${{targets.destdir}}/usr/local/bin
      ln -s gcc-wrapper cc
      ln -s gcc-wrapper cpp
      for suffix in 12 13 14; do
        ln -s gcc-wrapper cpp-$suffix
      done
      for app in c++ g++ gcc; do
        ln -s gcc-wrapper $app
        ln -s gcc-wrapper ${{host.triplet.gnu}}-$app
        for suffix in 12 13 14; do
          ln -s gcc-wrapper $app-$suffix
          ln -s gcc-wrapper ${{host.triplet.gnu}}-$app-$suffix
        done
      done

test:
  environment:
    contents:
      packages:
        - clang-18
        - gcc
        - gcc-12
  pipeline:
    - uses: test/compiler-hardening-check
      with:
        cc: clang-18
    - uses: test/compiler-hardening-check
      with:
        cc: gcc
    - uses: test/compiler-hardening-check
      with:
        cc: gcc-12
    - name: Ensure gcc_s is linked
      runs: |
        touch foo.c
        gcc -v foo.c &>stderr.log || true
        grep gcc_s stderr.log

update:
  enabled: false
