package:
  name: parallel
  version: "20240922"
  epoch: 0
  description: "GNU parallel is a shell tool for executing jobs in parallel using one or more computers"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - perl

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/parallel/parallel-${{package.version}}.tar.bz2
      expected-sha256: 63210715e8b7c5e129e098f333cd7cdd5fc7a2f325e8e0fb9ed6edba9f1acbc4

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 5448
