package:
  name: pax-utils
  version: 1.3.8
  epoch: 0
  description: "ELF related utilities for 32-bit and 64-bit binaries"
  copyright:
    - license: GPL-2.0-only
  dependencies:
    runtime:
      - scanelf

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-baselayout
      - xz

pipeline:
  - uses: git-checkout
    with:
      repository: git://anongit.gentoo.org/proj/pax-utils.git
      tag: v${{package.version}}
      expected-commit: 9ef54b472e42ba2c5479fbd86b8be2275724b064

  - runs: |
      make -j$(nproc) USE_CAP=no CC="${{host.triplet.gnu}}-gcc"

  - uses: autoconf/make-install

  - runs: |
      rm -f "${{targets.destdir}}"/usr/bin/lddtree

subpackages:
  - name: "scanelf"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv "${{targets.destdir}}"/usr/bin/scanelf "${{targets.subpkgdir}}"/usr/bin/scanelf

update:
  enabled: true
  release-monitor:
    identifier: 2601

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        dumpelf --version
        pspax --version
        scanmacho --version
        symtree version
