package:
  name: pcre2
  version: "10.44"
  epoch: 1
  description: "perl-compatible regular expression library"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libedit-dev
      - libtool
      - wolfi-base
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/PCRE2Project/pcre2.git
      tag: pcre2-${{package.version}}
      expected-commit: 6ae58beca071f13ccfed31d03b3f479ab520639b

  - runs: ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: --enable-jit --enable-pcre2-16 --enable-pcre2-32 --enable-pcre2grep-libz --enable-pcre2test-libedit

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "pcre2-doc"
    description: "pcre2 documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/

  - name: "pcre2-dev"
    description: "pcre2 development headers"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libpcre2-8-0
        - libpcre2-16-0
        - libpcre2-32-0
        - libpcre2-posix-3
        - libedit-dev
        - zlib-dev

  - name: "libpcre2-8-0"
    description: "pcre2 runtime library 8-bit"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libpcre2-8* "${{targets.subpkgdir}}"/usr/lib/

  - name: "libpcre2-16-0"
    description: "pcre2 runtime library 16-bit"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libpcre2-16* "${{targets.subpkgdir}}"/usr/lib/

  - name: "libpcre2-32-0"
    description: "pcre2 runtime library 32-bit"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libpcre2-32* "${{targets.subpkgdir}}"/usr/lib/

  - name: "libpcre2-posix-3"
    description: "pcre2 runtime library (posix)"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libpcre2-posix* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  github:
    identifier: PCRE2Project/pcre2
    strip-prefix: pcre2-

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        pcre2grep --version
        pcre2test --version
