package:
  name: perl-tk
  version: "804.036"
  epoch: 3
  description: Tk - a Graphical User Interface Toolkit
  copyright:
    - license: Artistic-1.0-Perl OR GPL-1.0-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - file
      - libpng-dev
      - libx11-dev
      - perl
      - perl-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 32aa7271a6bdfedc3330119b3825daddd0aa4b5c936f84ad74eabb932a200a5e
      uri: https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Tk-${{package.version}}.tar.gz

  - name: apply patches from alpine - gcc-14 and others.
    uses: patch
    with:
      patches: |
        gcc14.patch
        Tk-804.036-crash.patch
        Tk-804.036-Fix-STRLEN-vs-int-pointer-confusion-in-Tcl_GetByteAr.patch

  - runs: |
      PERL_MM_USE_DEFAULT=1 perl -I. Makefile.PL INSTALLDIRS=vendor
      make

  - runs: |
      make DESTDIR="${{targets.destdir}}" install
      find "${{targets.destdir}}" \( -name perllocal.pod -o -name .packlist \) -delete

  - uses: strip

subpackages:
  - name: perl-tk-doc
    pipeline:
      - uses: split/manpages
    description: perl-tk manpages

update:
  enabled: true
  release-monitor:
    identifier: 3471
