package:
  name: pgbouncer
  version: 1.22.1
  epoch: 1
  description: lightweight connection pooler for PostgreSQL
  copyright:
    - license: ISC

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates-bundle
      - libevent-dev
      - libtool
      - openssl-dev
      - pkgconf-dev

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: mangled-package-version

pipeline:
  # Use fetch instead of git-checkout, if we get the repo from git we need to generate docs
  # and the docs require pandoc which requires haskell
  - uses: fetch
    with:
      uri: https://github.com/pgbouncer/pgbouncer/releases/download/pgbouncer_${{vars.mangled-package-version}}/pgbouncer-${{package.version}}.tar.gz
      expected-sha256: 2b018aa6ce7f592c9892bb9e0fd90262484eb73937fd2af929770a45373ba215

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      mkdir -p "${{targets.contextdir}}"/etc/pgbouncer/
      install -Dm755 ./etc/pgbouncer.ini "${{targets.contextdir}}"/etc/pgbouncer/
      install -Dm755 ./etc/userlist.txt "${{targets.contextdir}}"/etc/pgbouncer/

  - uses: strip

subpackages:
  - name: pgbouncer-doc
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/doc/
          mv "${{targets.destdir}}"/usr/share/doc/pgbouncer "${{targets.subpkgdir}}"/usr/share/doc
    description: pgbouncer manpages

update:
  enabled: false
  manual: true
  exclude-reason: Doesn't work with var transforms
  github:
    identifier: pgbouncer/pgbouncer
    strip-prefix: pgbouncer_
    tag-filter: pgbouncer_

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        pgbouncer --version
