package:
  name: pluto
  version: 5.20.3
  epoch: 0
  description: A cli tool to help discover deprecated apiVersions in Kubernetes
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/FairwindsOps/pluto
      tag: v${{package.version}}
      expected-commit: bed05e30b6932aec8ee6615ddc88310fc959e248

  - uses: go/build
    with:
      packages: ./cmd/pluto/main.go
      output: pluto
      ldflags: |
        -X main.version=${{package.version}} -X main.commit=$(git rev-parse HEAD)}

  - uses: strip

update:
  enabled: true
  github:
    identifier: FairwindsOps/pluto
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  pipeline:
    - runs: |
        pluto version
