package:
  name: poppler
  version: 24.09.0
  epoch: 0
  description: Poppler is a PDF rendering library based on the xpdf-3.0 code base.
  copyright:
    - license: GPL-2.0-or-later

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo-dev
      - cmake
      - expat-dev
      - gobject-introspection-dev
      - lcms2-dev
      - libfontconfig1
      - libjpeg-turbo-dev
      - libnspr-dev
      - libnss-dev
      - libpng-dev
      - libxml2-dev
      - openjpeg-dev
      - openjpeg-tools
      - samurai
      - tiff-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.freedesktop.org/poppler/poppler.git
      tag: poppler-${{package.version}}
      expected-commit: e23bd900b7c5f3262c3b6c5fb20d7569ca5193db

  - uses: cmake/configure
    with:
      opts: |
        -DENABLE_GPGME=OFF \
        -DENABLE_LIBCURL=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_QT5=OFF \
        -DENABLE_QT6=OFF

  - uses: cmake/build

  - uses: cmake/install

subpackages:
  - name: poppler-dev
    pipeline:
      - uses: split/dev

  - name: poppler-doc
    pipeline:
      - uses: split/dev

  - name: poppler-glib
    pipeline:
      - uses: split/dev

  - name: poppler-utils
    pipeline:
      - uses: split/dev

update:
  enabled: true
  ignore-regex-patterns:
    - before-
  git:
    tag-filter-prefix: poppler-
    strip-prefix: poppler-
