package:
  name: protobuf-c
  version: 1.5.0
  epoch: 9
  description: Protocol Buffers implementation in C
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - abseil-cpp-dev
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - protobuf-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8c201f6e47a53feaab773922a743091eb6c8972a
      repository: https://github.com/protobuf-c/protobuf-c.git
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: deprecated-FileDescriptorLegacy.patch

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: protobuf-c-compiler
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/bin
          mv ${{targets.destdir}}/usr/bin/protoc-c ${{targets.subpkgdir}}/usr/bin/
          mv ${{targets.destdir}}/usr/bin/protoc-gen-c ${{targets.subpkgdir}}/usr/bin/
    description: Protocol Buffers C compiler

  - name: protobuf-c-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - protobuf-c
        - protobuf-c-compiler
    description: protobuf-c dev

update:
  enabled: true
  github:
    identifier: protobuf-c/protobuf-c
    strip-prefix: v
