package:
  name: pstack
  version: 2.8.1
  epoch: 2
  description: "Print stack traces from running processes, or core files."
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - cmake
      - openssf-compiler-options
      - python-3.12
      - wolfi-base
      - xz
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/peadar/pstack
      tag: v${{package.version}}
      expected-commit: 7bcbdb785b5ede6a558c033a9366d8e301d6bf2f
      cherry-picks: |
        master/f506eb1cf5e7edb20c63e75fc5e929cfb73bacdf: fix build with 2.8.1 and gcc-14

  - name: Set directories
    runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      mkdir -p "${{targets.destdir}}"/usr/include/
      mkdir -p "${{targets.destdir}}"/usr/lib/
      mkdir -p "${{targets.destdir}}"/usr/share/
      mkdir -p "${{targets.destdir}}"/usr/share/licenses/pstack/
      mkdir -p "${{targets.destdir}}"/usr/share/man/man1/

  - name: Configure
    runs: |
      CXXFLAGS="$CXXFLAGS -std=c++14" \
      cmake -B build \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DVERSION_TAG="${{package.version}}" \
      -DPYTHON3=OFF \
      -DPYTHON2=OFF \
      -Wno-dev

  - name: Build
    runs: |
      cmake --build build

  - name: Install
    runs: |
      install -m755 build/pstack "${{targets.destdir}}"/usr/bin/
      install -m755 build/canal "${{targets.destdir}}"/usr/bin/
      install -m755 build/hdmp "${{targets.destdir}}"/usr/bin/
      mv libpstack "${{targets.destdir}}"/usr/include/
      mv build/*.so* "${{targets.destdir}}"/usr/lib/
      mv LICENSE "${{targets.destdir}}"/usr/share/licenses/
      mv pstack.1 "${{targets.destdir}}"/usr/share/man/man1/

  - uses: strip

subpackages:
  - name: pstack-doc
    description: pstrack manpages
    pipeline:
      - runs: |
          cd "${{targets.destdir}}"
          mkdir -p "${{targets.subpkgdir}}"/usr/share/man/man1/
          mv -f "${{targets.destdir}}"/usr/share/man/man1/pstack.1 "${{targets.subpkgdir}}"/usr/share/man/man1/

update:
  enabled: true
  github:
    identifier: peadar/pstack
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - runs: /usr/bin/pstack --help
