package:
  name: pulumi-kubernetes-operator
  version: 1.16.0
  epoch: 1
  description: A Kubernetes Operator that automates the deployment of Pulumi Stacks
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 2ca775387e522fd5c29668a85bfba2f8fd791848
      repository: https://github.com/pulumi/pulumi-kubernetes-operator.git
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/hashicorp/go-retryablehttp@v0.7.7
      replaces: github.com/whilp/git-urls=github.com/chainguard-dev/git-urls@v1.0.2

  - runs: |
      # Original Go build args found in ./scripts/build.sh
      CGO_ENABLED=0 go build -o "${{targets.destdir}}/usr/bin/${{package.name}}" \
        -ldflags "-s -w -X github.com/pulumi/pulumi-kubernetes-operator/version.Version=v${{package.version}} -extldflags \"-static\"" \
        -tags netgo ./cmd/manager/main.go

  - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-kubernetes-operator
    strip-prefix: v
    tag-filter: v1.1
