package:
  name: py3-virtualenv
  version: 20.26.6
  epoch: 0
  description: Virtual Python Environment builder
  copyright:
    - license: "MIT"
  dependencies:
    provider-priority: 0

vars:
  pypi-package: virtualenv

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-supported-hatch-vcs
      - py3-supported-hatchling
      - py3-supported-pip
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypa/virtualenv
      tag: ${{package.version}}
      expected-commit: ec04726d065372ffad9920998aef1ce41252a61d

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      runtime:
        - py${{range.key}}-distlib
        - py${{range.key}}-filelock
        - py${{range.key}}-importlib-metadata
        - py${{range.key}}-platformdirs
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - name: Remove embedded setuptools wheel for python3.7 (CVE-2024-6345)
        runs: |
          # https://github.com/pypa/virtualenv/issues/2758
          cd ${{targets.contextdir}}/usr/lib/python${{range.key}}/site-packages/virtualenv/seed/wheels/embed/
          rm -v \
            pip-24.0-py3-none-any.whl \
            setuptools-68.0.0-py3-none-any.whl \
            wheel-0.42.0-py3-none-any.whl
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-bin
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}
      provides:
        - py3-${{vars.pypi-package}}-bin
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr
          mv ${{targets.contextdir}}/../py${{range.key}}-${{vars.pypi-package}}/usr/bin ${{targets.contextdir}}/usr
    test:
      pipeline:
        - runs: |
            virtualenv -h

test:
  pipeline:
    - runs: |
        virtualenv -h
    - uses: python/import
      with:
        import: ${{vars.pypi-package}}

update:
  enabled: true
  github:
    identifier: pypa/virtualenv
    use-tag: true
