package:
  name: py3-frozenlist
  version: 1.4.1
  epoch: 2
  description: A list-like structure which implements collections.abc.MutableSequence
  copyright:
    - license: Apache-2.0
  dependencies:
    provider-priority: 0

vars:
  pypi-package: frozenlist

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-supported-cython
      - py3-supported-expandvars
      - py3-supported-pip
      - py3-supported-python-dev
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: c037a86e8513059a2613aaba4d817bb90b9d9b6b69aace3ce9c877e8c8ed402b
      uri: https://files.pythonhosted.org/packages/source/f/frozenlist/frozenlist-${{package.version}}.tar.gz

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

test:
  pipeline:
    - uses: python/import
      with:
        import: ${{vars.pypi-package}}

update:
  enabled: true
  release-monitor:
    identifier: 41138
