package:
  name: py3-cmaes
  version: 0.11.1
  epoch: 0
  description: Lightweight Covariance Matrix Adaptation Evolution Strategy (CMA-ES) implementation for Python 3.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - numpy
      - py3-scipy
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-installer
      - py3-setuptools
      - py3-wheel
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/CyberAgentAILab/cmaes
      expected-commit: a6e791a8fb22723ceb1a581ae2fe739b10c0b62f
      tag: v${{package.version}}

  - name: Python Build
    runs: python -m build --sdist --wheel

  - name: Python Install
    runs: python -m installer -d "${{targets.destdir}}/" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: CyberAgentAILab/cmaes
    strip-prefix: v

test:
  pipeline:
    - runs: |
        LIBRARY="cmaes"
        IMPORT_STATEMENT="from cmaes import CMA"

        if ! python -c "$IMPORT_STATEMENT"; then
            echo "Failed to import library '$LIBRARY'."
            python -c "$IMPORT_STATEMENT" 2>&1
            exit 1
        else
            echo "Library '$LIBRARY' is installed and can be imported successfully."
            exit 0
        fi
