package:
  name: py3-urllib3
  version: 2.2.3
  epoch: 0
  description: "HTTP library with thread-safe connection pooling, file post, and more"
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-hatch-vcs
      - py3-supported-hatchling
      - py3-supported-pip
      - py3-supported-python
      - py3-supported-wheel

vars:
  pypi-package: urllib3

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/urllib3/urllib3.git
      tag: ${{package.version}}
      expected-commit: 2458bfcd3dacdf6c196e98d077fc6bb02a5fc1df

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provides:
        - py3-${{vars.pypi-package}}
      provider-priority: ${{range.value}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.pypi-package}}

update:
  enabled: true
  ignore-regex-patterns:
    - (\d+\.\d+)\.\da\d+ # urllib3 releases alpha versions with a suffix "a" followed by a digit, let's ignore these
  github:
    identifier: urllib3/urllib3
    strip-prefix: v
