package:
  name: py3-urllib3-1
  version: 1.26.20
  epoch: 0
  description: "HTTP library with thread-safe connection pooling, file post, and more"
  copyright:
    - license: MIT
  dependencies:
    provides:
      - py3-urllib3=1.999

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/urllib3/urllib3.git
      tag: ${{package.version}}
      expected-commit: 6f2ad7ca0cdde53751bab29cbc10bcc965bb4387

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import urllib3

update:
  enabled: true
  ignore-regex-patterns:
    - (\d+\.\d+)\.\da\d+ # urllib3 releases alpha versions with a suffix "a" followed by a digit, let's ignore these
  github:
    identifier: urllib3/urllib3
    use-tag: true
    tag-filter: "1"
