package:
  name: py3-rich
  version: 13.8.1
  epoch: 0
  description: "Rich is a Python library for rich text and beautiful formatting in the terminal."
  copyright:
    - license: LGPL-2.1-or-later
  dependencies:
    runtime:
      - py3-markdown-it-py
      - py3-pygments

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-pip
      - py3-poetry
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Textualize/rich
      tag: v${{package.version}}
      expected-commit: 260b35fd99c6b6ee9e28be8e3789e74bc3dd0cef

  - uses: py/pip-build-install

  - runs: |
      install -Dm644 LICENSE \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: Textualize/rich
    strip-prefix: v

test:
  environment:
    environment:
      RICH_TEST_STRING: "This is a test string for Rich!"
  pipeline:
    - name: Test Rich Installation
      runs: |
        python=$(set +x; m=/usr/bin/python3.*; set -- $m
            [ $# -eq 1 -a -x "$1" ] && echo "$1" && exit 0
            echo "found $# matches to $m"; exit 1;)
        $python -c "from rich import print; print('${RICH_TEST_STRING}')"

        # Test Rich Formatting Capabilities
        $python -c "from rich.console import Console; console = Console(); console.print('${RICH_TEST_STRING}', style='bold red')"

        # Test Rich JSON Rendering
        $python -c "from rich import print; print({'json': ['Renders', 'well', 'in', 'Rich']})"
