package:
  name: py3-psycopg
  version: 3.2.3
  epoch: 0
  description: PostgreSQL database adapter for Python
  copyright:
    - license: LGPL-3.0-only
  dependencies:
    runtime:
      - libpq-16
      - py3-typing-extensions
      - py3-tzdata

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - poetry
      - py3-gpep517
      - py3-pip
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/psycopg/psycopg
      tag: ${{package.version}}
      expected-commit: ce8f07321b8d0f0d95043596cbbbb6fd1e5831e7

  - uses: py/pip-build-install
    working-directory: psycopg

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - pool-*
    - 3.0.dev*
  github:
    identifier: psycopg/psycopg
    use-tag: true

test:
  environment:
    contents:
      packages:
        - postgresql
        - postgresql-client
        - wolfi-base
        - shadow
        - sudo-rs
        - glibc-locales
    environment:
      PGDATA: /tmp/test_db
      PGUSER: wolfi
  pipeline:
    - name: "Test database creation"
      runs: |
        useradd $PGUSER
        sudo -u $PGUSER initdb -D /tmp/test_db
        sudo -u $PGUSER pg_ctl -D /tmp/test_db -l /tmp/logfile start
        sudo -u $PGUSER createdb testdb
        psql -lqt | cut -d \| -f 1 | grep -qw testdb
    - name: "Test psycopg"
    - runs: |
        cat <<'EOF' >> /tmp/test.py
        import psycopg

        def main():
            conn = psycopg.connect(dbname="testdb", user="wolfi")
            cursor = conn.cursor()

            try:
                # Create Table
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS example_table (
                        id SERIAL PRIMARY KEY,
                        message TEXT
                    )
                """)

                # Insert value
                cursor.execute("INSERT INTO example_table (message) VALUES (%s)", ("Hello Wolfy!",))
                conn.commit()

                # Select and print
                cursor.execute("SELECT message FROM example_table")
                result = cursor.fetchone()
                message = result[0].decode("utf-8")
                print("Message retrieved from database:", message)

            except Exception as e:
                print("Error:", e)

            finally:
                cursor.close()
                conn.close()

        if __name__ == "__main__":
            main()
        EOF

        python=$(m=/usr/bin/python3.*; set +x; set -- $m
            [ $# -eq 1 -a -x "$1" ] && echo "$1" && exit 0
            echo "found $# matches to $m"; exit 1;)
        $python /tmp/test.py
