package:
  name: py3-more-itertools
  version: 10.5.0
  epoch: 0
  description: "more routines for operating on iterables, beyond itertools"
  copyright:
    - license: MIT
  dependencies:
    provider-priority: 0

vars:
  pypi-package: more-itertools

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-supported-flit-core
      - py3-supported-pip
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/more-itertools/more-itertools.git
      tag: v${{package.version}}
      expected-commit: 4998a257373f36e91edef7324572ed8df10f39d1

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: more_itertools

test:
  pipeline:
    - uses: python/import
      with:
        import: more_itertools

update:
  enabled: true
  github:
    identifier: more-itertools/more-itertools
    strip-prefix: v
