package:
  name: py3-influxdb-client
  version: 1.46.0
  epoch: 0
  description: "InfluxDB 2.0 python client"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-certifi
      - py3-dateutil
      - py3-pip
      - py3-setuptools
      - py3-urllib3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/influxdata/influxdb-client-python.git
      tag: v${{package.version}}
      expected-commit: dfd815d92dd26817396b9594c79c6c6fd977bd36

  - uses: py/pip-build-install

  - uses: strip

update:
  enabled: true
  github:
    identifier: influxdata/influxdb-client-python
    strip-prefix: v
    use-tag: true
