package:
  name: py3-pyelftools
  version: 0.31
  epoch: 0
  description: "Python Library for analyzing ELF files and DWARF debugging information"
  copyright:
    - license: LicenseRef-pyelftools-public-domain
      license-path: LICENSE
  dependencies:
    provider-priority: 0

vars:
  pypi-package: pyelftools

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - py3-supported-pip
      - py3-supported-python-dev
      - py3-supported-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/eliben/pyelftools
      tag: v${{package.version}}
      expected-commit: ff0118701a091ea9cbf3b44c65046754e3c77156

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      provider-priority: ${{range.value}}
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - runs: python${{range.key}} setup.py clean --all
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip

  - name: py3-wheels-${{vars.pypi-package}}
    pipeline:
      - uses: py/collect-wheels

update:
  enabled: true
  github:
    identifier: eliben/pyelftools
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        readelf.py --version
