package:
  name: py3-setproctitle
  version: 1.3.3
  epoch: 0
  description: A Python module to customize the process title
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dvarrazzo/py-setproctitle
      tag: version-${{package.version}}
      expected-commit: 52dd8dc9cd1d551c25396cf14f1c2adf01a28ef9

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - version-*
  github:
    identifier: dvarrazzo/py-setproctitle
    use-tag: true
    tag-filter-prefix: version-
    strip-prefix: version-
