# This package provides a binary wheel for python-3.XX packages
# in lieu of ensurepip's bundled wheels.  It allows us to proctively
# update those wheels by tracking the upstream package release.
# python is compiled with --with-wheel-pkg-dir=/usr/share/python-wheels
package:
  name: py3-setuptools-wheel
  version: 75.1.0
  epoch: 0
  description: "python3 setuptools wheel from pypi"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/py3/s/setuptools/setuptools-${{package.version}}-py3-none-any.whl
      expected-sha256: 35ab7fd3bcd95e6b7fd704e4a1539513edad446c097797f2985e0e4b960772f2
      extract: false

  - name: Install wheel
    runs: |
      wdir="${{targets.contextdir}}/usr/share/python-wheels"
      mkdir -p "$wdir"
      cp -v *.whl "$wdir"

update:
  enabled: true
  release-monitor:
    identifier: 4021
