package:
  name: R-sf
  version: 1.0.17
  epoch: 0
  description: Simple Features for R
  copyright:
    - license: GPL-2.0-only AND MIT
  dependencies:
    runtime:
      - R
      - R-DBI
      - R-classInt
      - R-magrittr
      - R-s2
      - R-units
      - Rcpp
      - gdal
      - geos
      - proj

environment:
  contents:
    packages:
      - R
      - R-DBI
      - R-classInt
      - R-dev
      - R-magrittr
      - R-s2
      - R-units
      - Rcpp
      - busybox
      - gdal-dev
      - geos-dev
      - pkgconf
      - proj-dev
      - sqlite-dev
      - tiff-dev

var-transforms:
  - from: ${{package.version}}
    match: ^(.+)\.(\d+)$
    replace: $1-$2
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cran/sf
      tag: ${{vars.mangled-package-version}}
      expected-commit: b49b06184c7af828d3b5a0f06e461dd1f55ed8ff

  - uses: R/build
    with:
      package: sf
      version: ${{vars.mangled-package-version}}

  - uses: strip

test:
  pipeline:
    - runs: |
        Rscript -e 'library(sf)'

update:
  enabled: true
  ignore-regex-patterns:
    - 'R-.*'
  version-transform:
    - match: ^(.+)\-(\d+)$
      replace: $1.$2
  github:
    identifier: cran/sf
    use-tag: true
