package:
  name: R-wk
  version: 0.9.3
  epoch: 0
  description: Lightweight Well-Known Geometry Parsing
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - R

environment:
  contents:
    packages:
      - R
      - R-dev
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cran/wk
      tag: ${{package.version}}
      expected-commit: f0d65c5f6132f1489bbb547c62984a3d768f7dcd

  - uses: R/build
    with:
      package: wk
      version: ${{package.version}}

  - uses: strip

test:
  pipeline:
    - runs: |
        Rscript -e 'library(wk)'

update:
  enabled: true
  ignore-regex-patterns:
    - 'R-.*'
  github:
    identifier: cran/wk
    use-tag: true
