package:
  name: rabbitmq-cluster-operator
  version: 2.10.0
  epoch: 1
  description: Open source RabbitMQ cluster operator. Kubernetes operator to deploy and manage RabbitMQ clusters.
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rabbitmq/cluster-operator
      tag: v${{package.version}}
      expected-commit: 008ed9fd1742791c97c1bb8004e58b7563ea9dbb

  - uses: go/build
    with:
      packages: .
      output: manager
      tags: timetzdata

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          # link /usr/bin/manager to /manager due to hardcoded command
          # See https://github.com/rabbitmq/cluster-operator/blob/main/config/manager/manager.yaml#L34-L35
          mkdir -p ${{targets.subpkgdir}}/
          ln -sf /usr/bin/manager ${{targets.subpkgdir}}/manager

update:
  enabled: true
  github:
    identifier: rabbitmq/cluster-operator
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        manager --help
