package:
  name: rancher-agent-2.9
  version: 2.9.2
  epoch: 0
  description: Complete container management platform - agent
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - rancher-agent=${{package.full-version}}
    runtime:
      - acl-dev
      - bash
      - busybox # nsenter
      - busybox
      - curl
      - gawk
      - gzip
      - iproute2
      - jq
      - kubectl
      - mount
      - net-tools
      - openssh-client
      - openssl
      - posix-libc-utils
      - rancher-charts-${{vars.major-minor-version}}
      - rancher-helm3-charts
      - rancher-kontainer-driver-metadata-${{vars.major-minor-version}}
      - rancher-loglevel
      - rancher-partner-charts
      - rancher-rke2-charts
      - rancher-system-charts-${{vars.major-minor-version}}
      - sysstat
      - tini
      - umount
      - util-linux-dev
      - util-linux-misc # unshare
      - vim

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rancher/rancher
      tag: v${{package.version}}
      expected-commit: 3da2ae0cabd11aa3af8bc463f5e5e74a3f156c71

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 k8s.io/kubernetes@v1.30.3 k8s.io/apiserver@v0.30.3 github.com/opencontainers/runc@v1.1.14

  - uses: go/build
    with:
      packages: ./cmd/agent
      output: agent
      ldflags: |
        -X main.VERSION=${{package.version}}
      tags: k8s

  - runs: |
      mkdir -p ${{targets.contextdir}}/usr/bin
      install -Dm755 package/run.sh ${{targets.contextdir}}/usr/bin/
      install -Dm755 package/kubectl-shell.sh ${{targets.contextdir}}/usr/bin/
      install -Dm755 package/shell-setup.sh ${{targets.contextdir}}/usr/bin/

test:
  pipeline:
    - runs: |
        agent | grep "Rancher agent version ${{package.version}}"

update:
  enabled: true
  github:
    identifier: rancher/rancher
    strip-prefix: v
    use-tag: true
    tag-filter: v2.9.
