package:
  name: render-template
  version: 1.0.7
  epoch: 2
  description: CLI tool for rendering templates with custom data
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/bitnami/render-template
      tag: v${{package.version}}
      expected-commit: b12a4c8de912be9e6b2ab2a3fe0bca324988a9ca

  - runs: |
      CGO_ENABLED=1 go build -trimpath -ldflags '-linkmode external -extldflags "-static"' .
      mkdir -p ${{targets.destdir}}/usr/bin
      mv render-template ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: bitnami/render-template
    strip-prefix: v
    use-tag: true
