package:
  name: rootlesskit
  version: 2.3.1
  epoch: 1
  description: RootlessKit is a Linux-native implementation of "fake root" using user_namespaces(7).
  copyright:
    - license: Apache-2.0
  dependencies:
    # Let's ensure that we have config. This gets the default, but can also
    # be overriden by users.
    runtime:
      - rootlesskit-config

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rootless-containers/rootlesskit
      expected-commit: fcc67feacd7deea8bca12a1a849e638704b8e7d2
      tag: v${{package.version}}

  - runs: |
      CGO_ENABLED=0 make all
      DESTDIR=${{targets.destdir}} BINDIR="/usr/bin" make install

  - uses: strip

subpackages:
  - name: "rootlesskit-config-nonroot"
    description: Rootlesskit config for nonroot user
    dependencies:
      runtime:
        - rootlesskit
      provides:
        - rootlesskit-config=${{package.full-version}}
    pipeline:
      # See https://rootlesscontaine.rs/getting-started/common/subuid/
      - runs: |
          mkdir -p ${{targets.destdir}}/etc
          echo "nonroot:100000:65536" > ${{targets.destdir}}/etc/subuid
          echo "nonroot:100000:65536" > ${{targets.destdir}}/etc/subgid

update:
  enabled: true
  github:
    identifier: rootless-containers/rootlesskit
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        rootlessctl --version
        rootlesskit --version
        rootlesskit-docker-proxy --help
