package:
  name: ruby3.2-rexml
  version: 3.3.8
  epoch: 0
  description: An XML toolkit for Ruby
  copyright:
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: rexml

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 036d50851ce091c797db0b9ba3ed8e5a39c3918c
      repository: https://github.com/ruby/rexml
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: ruby/rexml
    strip-prefix: v
    use-tag: true
