package:
  name: ruby3.2-console
  version: 1.27.0
  epoch: 1
  description: Beautiful logging for Ruby.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-fiber-annotation
      - ruby3.2-fiber-local
      - ruby3.2-fiber-storage
      - ruby3.2-json

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: console

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b40f588e6e98f743402b3c93921d5053d5c15127
      repository: https://github.com/socketry/console
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

test:
  pipeline:
    - runs: ruby -e "require 'console'"

update:
  enabled: true
  github:
    identifier: socketry/console
    strip-prefix: v
    use-tag: true
