package:
  name: ruby3.2-webrick
  version: 1.8.2
  epoch: 0
  description: WEBrick is an HTTP server toolkit that can be configured as an HTTPS server, a proxy server, and a virtual-host server.
  copyright:
    - license: Ruby
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: webrick

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0fb9de6788a3ba5fe903e63d778a0fb8c1dce786
      repository: https://github.com/ruby/webrick
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: ruby/webrick
    strip-prefix: v
