package:
  name: ruby3.2-http
  version: 5.2.0
  epoch: 0
  description: An easy-to-use client library for making requests from Ruby. It uses a simple method chaining system for building requests, similar to Python's Requests.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby3.2-addressable
      - ruby3.2-base64
      - ruby3.2-http-cookie
      - ruby3.2-http-form_data
      - ruby3.2-llhttp

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/httprb/http
      tag: v${{package.version}}
      expected-commit: bb754c7d85dca26180567b781815e1b84c784d86

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: http

test:
  pipeline:
    - runs: ruby -e "require 'http'"
    - name: Basic HTTP request parsing
      runs: |
        cat <<EOF > /tmp/test.rb
        require "http"
        HTTP.get("https://github.com").to_s
        EOF
        ruby /tmp/test.rb

update:
  enabled: true
  github:
    identifier: httprb/http
    strip-prefix: v
    use-tag: true
