package:
  name: ruby3.2-kubeclient
  version: 4.12.0
  epoch: 1
  description: An efficient, thread safe LRU cache.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby3.2-faraday
      - ruby3.2-faraday-follow_redirects
      - ruby3.2-http
      - ruby3.2-jsonpath
      - ruby3.2-recursive-open-struct
      - ruby3.2-rest-client

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ManageIQ/kubeclient
      tag: v${{package.version}}
      expected-commit: 0feda1d7de6bdab96286c81eb0f2ccc2127040cf

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: kubeclient

test:
  pipeline:
    - runs: |
        ruby -e "require 'kubeclient'"
    - name: Simple test
      runs: |
        cat <<EOF > /tmp/test.rb
        require 'kubeclient'
        Kubeclient::Client.new('http://localhost:8080/api', 'v1')
        EOF
        ruby /tmp/test.rb

update:
  enabled: true
  github:
    identifier: ManageIQ/kubeclient
    strip-prefix: v
    use-tag: true
