package:
  name: ruby3.2-systemd-journal
  version: 2.0.0
  epoch: 0
  description: Provides the ability to navigate and read entries from the systemd journal in ruby, as well as write events to the journal.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - libsystemd # libsystemd.so.0 is dlopened
      - ruby-3.2
      - ruby3.2-ffi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: systemd-journal

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8ff684ac1ff17d2de2db4e942112dc3ec5db40e5
      repository: https://github.com/ledbettj/systemd-journal
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

test:
  pipeline:
    - runs: |
        ruby -e "require 'systemd/journal'"

update:
  enabled: true
  github:
    identifier: ledbettj/systemd-journal
    strip-prefix: v
