package:
  name: ruby3.2-ffi-compiler
  version: 1.3.2
  epoch: 0
  description: Ruby FFI Rakefile generator
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ruby3.2-ffi

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ffi/ffi-compiler
      tag: ${{package.version}}
      expected-commit: 1bd1547f721c17e976505f09dadf0a189f062eaa

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: ffi-compiler

test:
  pipeline:
    - runs: |
        cat <<EOF > test.rb
        require 'ffi'
        require 'ffi-compiler/loader'
        EOF
        ruby test.rb

update:
  enabled: true
  github:
    identifier: ffi/ffi-compiler
    use-tag: true
