package:
  name: ruff
  version: 0.6.8
  epoch: 0
  description: An extremely fast Python linter, written in Rust.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/astral-sh/ruff
      tag: ${{package.version}}
      expected-commit: ae39ce56c0cc1f8ac15f980c0b457b16b67c1f2a

  - runs: |
      cargo auditable build --release
      mkdir -p ${{targets.destdir}}/usr/bin
      mv target/release/ruff ${{targets.destdir}}/usr/bin/

  - uses: strip

subpackages:
  - name: ruff-python-formatter
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          ls target/release/
          mv target/release/ruff_python_formatter ${{targets.subpkgdir}}/usr/bin/

update:
  enabled: true
  github:
    identifier: astral-sh/ruff

test:
  pipeline:
    - name: Verify ruff installation
      runs: |
        ruff --version || exit 1
    - name: Lint a Python file
      runs: |
        echo 'print("Hello, world!")' > test.py
        ruff check test.py || exit 1
    - name: Lint with specific rules
      runs: |
        echo 'print("Hello, world!")' > test.py
        ruff check --select F401 test.py || exit 1
