package:
  name: runit
  version: 2.1.2
  epoch: 4
  description: UNIX init scheme with service supervision
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://smarden.org/runit/runit-${{package.version}}.tar.gz
      expected-sha512: a18773ebf1aa22305dd89ed67363165b9fcf86c192b2be4e268d08005dd82d51265160c637abe072f2f2e378c4b315a75bd3d3e602c3e75bdd451a3b0190f8cf
      strip-components: 2

  - runs: |
      mv src/* .

  - uses: patch
    with:
      patches: svlogd-udp.patch

  - runs: |
      # patch in some flags, or it will not build with gcc-14
      cp conf-cc conf-cc.dist
      for flag in \
          implicit-function-declaration \
          incompatible-pointer-types \
          ; do
          sed -i -e "1s/$/ -Wno-error=$flag/" conf-cc
      done
      diff conf-cc.dist conf-cc && exit 1

  - uses: autoconf/make

  - runs: |
      install -d "${{targets.destdir}}"/sbin "${{targets.destdir}}"/usr/bin
      for i in chpst runit runit-init runsv runsvchdir runsvdir sv svlogd utmpset; do
        install -m755 "$i" "${{targets.destdir}}"/sbin/$i
      done
      ln -sfv /sbin/runsvdir "${{targets.destdir}}"/usr/bin/runsvdir
      install -d "${{targets.destdir}}"/usr/share/man/man8
      cp -rf man/* "${{targets.destdir}}"/usr/share/man/man8
      mkdir -p "${{targets.destdir}}"/etc/service
      mkdir -p "${{targets.destdir}}"/etc/sv

  - uses: strip

subpackages:
  - name: runit-doc
    pipeline:
      - uses: split/manpages
    description: runit manpages

update:
  enabled: true
  release-monitor:
    identifier: 279717

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        runit-init --version
