package:
  name: sbt
  version: 1.10.2
  epoch: 1
  description: A scala build tool
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - openjdk-11-jre

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      # The first time this is built, it depends on sbt-stage0.yaml being built first,
      # using pre-built sbt binaries, which `provides` a sbt package at an earlier version.
      # Afterwards it depends on previous versions of this package built from source.
      - openjdk-11
      - sbt

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sbt/sbt
      tag: v${{package.version}}
      expected-commit: 4951e3e6da01e11bfb6818b901d8ea0c8e80cdb0

  - runs: |
      cd launcher-package

      sbt -Dsbt.build.version=${{package.version}}  universal:packageZipTarball

      tar -xf target/universal/sbt.tgz

      mkdir -p ${{targets.destdir}}/usr/share/java/sbt/bin
      mkdir -p ${{targets.destdir}}/usr/share/java/sbt/conf

      install -m644 -Dt ${{targets.destdir}}/usr/share/java/sbt/bin ./sbt/bin/sbt-launch.jar
      install -m755 -Dt ${{targets.destdir}}/usr/share/java/sbt/bin ./sbt/bin/sbt

      mkdir -p ${{targets.destdir}}/usr/bin
      ln -sf /usr/share/java/sbt/bin/sbt ${{targets.destdir}}/usr/bin/sbt

      install -m644 -Dt ${{targets.destdir}}/usr/share/java/sbt/bin ./sbt/bin/sbtn-${{build.arch}}-pc-linux

update:
  enabled: true
  github:
    identifier: sbt/sbt
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - openjdk-11-default-jdk
        - openjdk-11-jmods
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk
  pipeline:
    - name: Test sbt compile
      runs: |
        cd HelloWorldProject && /usr/bin/sbt run
