package:
  name: scudo-malloc
  version: 19.1.0
  epoch: 0
  description: "scudo-malloc aims at providing additional mitigation against heap based vulnerabilities, while maintaining good performance"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - libstdc++

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-18
      - clang-18-dev
      - coreutils
      - linux-headers
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/llvm/llvm-project/releases/download/llvmorg-${{package.version}}/compiler-rt-${{package.version}}.src.tar.xz
      expected-sha256: 808b858e93b0bbae4002e13dcbe8bee850c514a58cbfb63b03d8b465ba95a3de

  - runs: |
      unset cflags_crc32
      case "${{build.arch}}" in
          aarch64)
              # this has broken emulation in aarch64 qemu (incl qemu-user),
              # which causes it to abort instantly
              cflags_crc32="-DSCUDO_DISABLE_TBI -march=armv8-a+crc"
              ;;
          x86*)
              cflags_crc32="-mcrc32 -msse4.2"
              ;;
      esac

      cd lib || exit 1
      # building libscudo
      clang++ -fPIC -std=c++17 -O2 -pthread -shared \
          $cflags_crc32 \
          -I scudo/standalone/include \
          scudo/standalone/*.cpp \
          -o ./libscudo.so

      install -Dm755 ./libscudo.so -t "${{targets.contextdir}}"/usr/lib/

test:
  environment:
    contents:
      packages:
        - wolfi-base
        - stress-ng
  pipeline:
    - runs: |
        LD_PRELOAD=/usr/lib/libscudo.so stress-ng --vdso 1 -t 5 --metrics

update:
  enabled: true
  github:
    identifier: llvm/llvm-project
    strip-prefix: llvmorg-
    use-tag: true
  ignore-regex-patterns:
    - ".*-init"
    - ".*-rc.*"
