package:
  name: sdp-k8s-injector
  version: 1.3.4
  epoch: 0
  description: "SDP Client for Kubernetes"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - openssl-dev
      - rust
      - wolfi-base

data:
  - name: other_binaries
    items:
      sdp-identity-service: "sdp-identity-service"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/appgate/sdp-k8s-injector
      tag: v${{package.version}}-sdp-k8s-injector-crd
      expected-commit: 5317ed9bab100f255dbd0acdeaacd30498ac25a6

  - name: Configure and build
    runs: |
      # mitigate GHSA-q445-7m23-qrmw
      cargo update openssl --precise 0.10.66

      cargo auditable build --release
      mkdir -p ${{targets.destdir}}/usr/bin

      # move the executable binaries to the destdir
      for f in target/release/sdp-*; do
        if [ -x "$f" ] && [ -f "$f" ] ; then
          mv "$f" ${{targets.destdir}}/usr/bin/
        fi
      done

subpackages:
  - range: other_binaries
    name: ${{range.key}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          mv ${{targets.destdir}}/usr/bin/${{range.key}} ${{targets.subpkgdir}}/usr/bin/

update:
  enabled: true
  github:
    identifier: appgate/sdp-k8s-injector
    strip-prefix: v
    strip-suffix: -sdp-k8s-injector-crd
