package:
  name: secrets-store-csi-driver
  # When bumping the version check if the CVE mitigations below can be removed.
  version: 1.4.5
  epoch: 2
  description: Secrets Store CSI driver for Kubernetes secrets
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - busybox # the csi driver needs the 'mount' applet

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/kubernetes-sigs/secrets-store-csi-driver
      tag: v${{package.version}}
      expected-commit: e5b8e5c33dfdc6fc4d361da611deb7e7f3ec07f8

  - runs: |
      # Our global LDFLAGS conflict with a Makefile parameter: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/Makefile#LL49C3-L49C3
      unset LDFLAGS
      make build

  - runs: |
      install -Dm755 _output/secrets-store-csi ${{targets.destdir}}/usr/bin/secrets-store-csi

  - uses: strip

subpackages:
  - name: ${{package.name}}-crds
    description: "CRDs for secrets-store-csi-driver"
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/crds
          make build-crds
          cp -R _output/crds/* ${{targets.contextdir}}/crds/

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/secrets-store-csi-driver
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        secrets-store-csi --version
