package:
  name: shfmt
  version: 3.9.0
  epoch: 1
  description: A shell formatter
  copyright:
    - license: BSD-3-Clause

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mvdan/sh
      tag: v${{package.version}}
      expected-commit: 7bd422f92937020ddf4519e47f8ea1bbf815a6d5

  - uses: go/build
    with:
      packages: ./cmd/shfmt
      ldflags: -s -w -X main.version=v${{package.version}}
      output: shfmt

  - uses: strip

update:
  enabled: true
  github:
    identifier: mvdan/sh
    strip-prefix: v

test:
  pipeline:
    - runs: |
        shfmt --version
