package:
  name: skalibs
  version: 2.14.2.0
  epoch: 1
  description: "set of general-purpose C programming libraries for skarnet.org software"
  copyright:
    - license: ISC

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 0e86d31f6091903510fc5e6be2d0dea6ff54b1c8
      repository: https://github.com/skarnet/skalibs.git
      tag: v${{package.version}}

  - name: Configure
    runs: |
      ./configure \
        --enable-shared \
        --enable-static \
        --libdir=/usr/lib

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "skalibs-dev"
    description: "skalibs development headers"
    pipeline:
      - uses: split/dev
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib/skalibs
          mv "${{targets.destdir}}"/usr/lib/skalibs/sysdeps "${{targets.subpkgdir}}"/usr/lib/skalibs/

update:
  enabled: true
  github:
    identifier: skarnet/skalibs
    strip-prefix: v
    tag-filter-prefix: v
    use-tag: true
