package:
  name: smartypants
  version: 2.0.1
  epoch: 1
  description: Translate plain ASCII punctuation characters into “smart” typographic punctuation HTML entities
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-docutils
      - py3-pygments
      - py3-setuptools
      - py3-sphinx
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/leohemsted/smartypants.py
      expected-commit: d4b99ab7e7e6f42ba2d75624715c5c47c8de650d
      tag: v${{package.version}}

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

subpackages:
  - name: smartypants-doc
    pipeline:
      - uses: split/manpages
    description: smartypants manpages

update:
  enabled: true
  github:
    identifier: leohemsted/smartypants.py
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        smartypants --version
