package:
  name: snyk-cli
  version: 1.1293.1
  epoch: 1
  description: Snyk CLI scans and monitors your projects for security vulnerabilities
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - libstdc++

environment:
  contents:
    packages:
      - apk-tools
      - build-base
      - busybox
      - ca-certificates
      - convco
      - curl
      - go
      - nodejs
      - npm
      - perl-utils
      - py3-requests
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/snyk/cli
      tag: v${{package.version}}
      expected-commit: 42280db5572aaae848e2b99b92198d9043b7f490

  - uses: go/bump
    with:
      deps: github.com/hashicorp/go-retryablehttp@v0.7.7 github.com/open-policy-agent/opa@v0.68.0
      modroot: ./cliv2

  - runs: git checkout -b release/wolfi # This is so the determine-release-channel.sh script decides the to use the correct channel and not create a -dev version

  - runs: make build

  - runs: |
      mkdir -p "${{targets.contextdir}}"/usr/bin
      mv ./binary-releases/snyk-* "${{targets.contextdir}}"/usr/bin/snyk

  - uses: strip

update:
  enabled: true
  github:
    identifier: snyk/cli
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    - runs: |
        # snyk requires auth to do anything meaningful, so we just check the version
        snyk --version | grep ${{package.version}}
