package:
  name: spqr
  version: 1.5.0
  epoch: 1
  description: Stateless Postgres Query Router
  copyright:
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - postgresql-client

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pg-sharding/spqr
      expected-commit: 46815b50f24af959759e535742369f616de8d53c
      tag: ${{package.version}}

  - runs: |
      make build
      mkdir -p ${{targets.destdir}}/usr/bin
      mv spqr-* ${{targets.destdir}}/usr/bin

  - uses: strip

update:
  enabled: true
  github:
    identifier: pg-sharding/spqr

test:
  pipeline:
    - runs: |
        spqr-router --help
        spqr-coordinator --help
        spqr-balancer --help
        spqr-coordinator --help
        spqr-mover --help
        spqr-router --help
        spqr-workloadreplay --help
        spqr-worldmock --help

        spqr-router --version | grep ${{package.version}}
