package:
  name: sqlmap
  version: "1.8"
  epoch: 0
  description: "a tool that automates the process of detecting and exploiting SQL injection flaws"
  copyright:
    - license: GPL-2.0-or-later
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - busybox
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sqlmapproject/sqlmap
      tag: ${{package.version}}
      expected-commit: f94ab0f650fbaee68e928a9801648f9881a1ae80
      destination: sqlmap

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/share/app/sqlmap && mkdir -p "${{targets.destdir}}"/usr/bin
      mv sqlmap/* "${{targets.destdir}}"/usr/share/app/sqlmap
      ln -s /usr/share/app/sqlmap/sqlmap.py "${{targets.destdir}}"/usr/bin/sqlmap
      find "${{targets.destdir}}"/usr/share/app/sqlmap \( -type d -name doc \) -exec rm -rf '{}' \+

  - uses: strip

update:
  enabled: true
  github:
    identifier: sqlmapproject/sqlmap

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        sqlmap --version
