package:
  name: src
  version: 5.5.0
  epoch: 1
  description: Sourcegraph CLI
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
      - git

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
      - libx11-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sourcegraph/src-cli
      expected-commit: ffb972710454ca51480f7cfe214f90dad865c78d
      tag: ${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/golang/protobuf@v1.5.4 k8s.io/api@v0.27.13 k8s.io/apimachinery@v0.27.13 k8s.io/client-go@v0.27.13 k8s.io/metrics@v0.27.13

  - uses: go/build
    with:
      packages: ./cmd/src
      output: src
      ldflags: "-s -w -X github.com/sourcegraph/src-cli/internal/version.BuildTag=${{package.version}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: sourcegraph/src-cli

test:
  pipeline:
    - name: Verify src installation
      runs: |
        src version || exit 1
    - name: Display src CLI help
      runs: |
        src -h || exit 1
