package:
  name: starship
  version: 1.20.1
  epoch: 4
  description: "The minimal, blazing-fast, and infinitely customizable prompt for any shell!"
  copyright:
    - license: ISC

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - cmake
      - openssf-compiler-options
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/starship/starship
      tag: v${{package.version}}
      expected-commit: f505324dac96a7f39b92ff85477c109d7efe6c5e

  - uses: rust/cargobump

  - runs: |
      cargo auditable build --release
      install -Dm755 target/release/starship "${{targets.destdir}}"/usr/bin/starship

  - uses: strip

update:
  enabled: true
  github:
    identifier: starship/starship
    strip-prefix: v

test:
  pipeline:
    - runs: |
        starship --version
