package:
  name: strace
  version: "6.11"
  epoch: 0
  description: Diagnostic, debugging and instructional userspace tracer
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - autoconf
      - autoconf-archive
      - automake
      - binutils-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils # GNU date - busybox date not sufficient.
      # - elfutils-dev TODO
      - gawk

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8399328f628182cf236a1c39a074d601babdeaa4
      repository: https://github.com/strace/strace.git
      tag: v${{package.version}}

  - runs: ./bootstrap

  - uses: autoconf/configure
    with:
      opts: |
        --host=${{host.triplet.gnu}} \
        --build=${{host.triplet.gnu}} \
        --enable-mpers=no

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: strace-doc
    pipeline:
      - uses: split/manpages
    description: strace manpages

update:
  enabled: true
  github:
    identifier: strace/strace
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        strace --version
        strace-log-merge --help
