package:
  name: subversion
  version: 1.14.3
  epoch: 1
  description: Replacement for CVS, another versioning system (svn)
  copyright:
    - license: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND HPND-Markus-Kuhn AND MIT AND Unicode-DFS-2015 AND FSFAP

environment:
  contents:
    packages:
      - apr-util-dev
      - autoconf
      - boost-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cyrus-sasl-dev
      - file
      - libapr-dev
      - libmagic-dev
      - libtool
      - lz4-dev
      - serf-dev
      - sqlite-dev
      - utf8proc-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 949efd451a09435f7e8573574c71c7b71b194d844890fa49cd61d2262ea1a440
      uri: https://archive.apache.org/dist/subversion/subversion-${{package.version}}.tar.bz2

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: subversion-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - subversion-libs
    description: subversion development files

  - name: subversion-doc
    pipeline:
      - uses: split/manpages
    description: subversion manpages

  - name: subversion-bash-completion
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/bash-completion/completions
          install -Dm644 tools/client-side/bash_completion "${{targets.subpkgdir}}"/usr/share/bash-completion/completions/subversion
          for i in svn svnadmin svndumpfilter svnlook svnsync svnversion; do ln -sf subversion "${{targets.subpkgdir}}"/usr/share/bash-completion/completions/$i; done
    description: subversion bash completion rules

  - name: subversion-libs
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/* "${{targets.subpkgdir}}"/usr/lib
    description: subversion libraries

update:
  enabled: true
  release-monitor:
    identifier: 4905

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        svn --version
        svnadmin --version
        svnbench --version
        svndumpfilter --version
        svnfsfs --version
        svnlook --version
        svnmucc --version
        svnrdump --version
        svnserve --version
        svnsync --version
        svnversion --version
