package:
  name: svt-av1
  version: 2.2.1
  epoch: 0
  description: "Scalable Video Technology for AV1 (SVT-AV1 Encoder)"
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake
      - nasm
      - openssf-compiler-options
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/AOMediaCodec/SVT-AV1.git
      expected-commit: 55a01def732bb9e7016d23cc512384f7a88d6e86
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: -DSVT_AV1_LTO=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: "${{package.name}}-dev"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 24271

test:
  environment:
    contents:
      packages:
        - busybox
        - ffmpeg
  pipeline:
    - name: Verify SvtAv1EncApp binary exists
      runs: |
        SvtAv1EncApp --version
    - name: Generate a sample video
      runs: |
        ffmpeg -f lavfi -i testsrc=duration=10:size=1280x720:rate=25 -pix_fmt yuv420p sample.y4m
    - name: Encode the generated sample video to SvtAv1
      runs: |
        SvtAv1EncApp -i sample.y4m -b encoded.ivf
    - name: Package SvtAv1 stream into an MP4 container
      runs: |
        ffmpeg -i encoded.ivf -c copy encoded.mp4
    - name: Verify the encoded video is a valid MP4 file
      runs: |
        ffprobe -v error -show_entries format=format_name -of default=noprint_wrappers=1:nokey=1 encoded.mp4 | grep -q 'mp4'
