package:
  name: systemd
  version: "256.6"
  epoch: 2
  description: The systemd System and Service Manager
  copyright:
    - license: LGPL-2.1-or-later AND GPL-2.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox-full
      - ca-certificates-bundle
      - clang-16
      - cmake
      - coreutils
      - gperf
      - kmod-dev
      - libbpf
      - libcap-dev
      - libmount
      - libuuid
      - llvm16
      - meson
      - ninja
      - openssf-compiler-options
      - posix-libc-utils
      - py3-jinja2
      - py3-pyelftools
      - python3
      - util-linux-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/systemd/systemd
      tag: v${{package.version}}
      expected-commit: 230f5613c97175985f878580ef2f5f1937963da6

  - uses: meson/configure

  - uses: meson/compile

  - uses: meson/install

  - runs: |
      mkdir -p ${{targets.destdir}}/lib
      mv ${{targets.destdir}}/usr/lib/libsystemd.so* ${{targets.destdir}}/lib/

subpackages:
  - name: "systemd-dev"
    description: "headers for systemd"
    pipeline:
      - uses: split/dev

  - name: "libsystemd"
    description: "systemd library"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/lib
          mv ${{targets.destdir}}/lib/libsystemd.so.* ${{targets.subpkgdir}}/lib

  - name: "libsystemd-shared"
    description: "systemd library"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          cp ${{targets.destdir}}/usr/lib/systemd/libsystemd-shared-*.so  ${{targets.subpkgdir}}/usr/lib/

  - name: "systemd-boot"
    description: "systemd bootloader"
    dependencies:
      runtime:
        - libsystemd-shared
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc/
          mkdir -p ${{targets.subpkgdir}}/usr/bin/
          mkdir -p ${{targets.subpkgdir}}/usr/lib/kernel/
          mkdir -p ${{targets.subpkgdir}}/usr/lib/systemd/
          mkdir -p ${{targets.subpkgdir}}/usr/lib/systemd/system-generators/
          cp -r ${{targets.destdir}}/etc/kernel ${{targets.subpkgdir}}/etc/
          cp -r ${{targets.destdir}}/usr/bin/kernel-install ${{targets.subpkgdir}}/usr/bin/
          cp -r ${{targets.destdir}}/usr/bin/bootctl ${{targets.subpkgdir}}/usr/bin/
          cp -r ${{targets.destdir}}/usr/lib/kernel ${{targets.subpkgdir}}/usr/lib/
          cp -r ${{targets.destdir}}/usr/lib/systemd/boot ${{targets.subpkgdir}}/usr/lib/systemd/
          cp -r ${{targets.destdir}}/usr/lib/systemd/systemd-bless-boot ${{targets.subpkgdir}}/usr/lib/systemd/
          cp -r ${{targets.destdir}}/usr/lib/systemd/system-generators/systemd-bless-boot-generator ${{targets.subpkgdir}}/usr/lib/systemd/system-generators/

  - name: "systemd-init"
    description: "Configure systemd for use as an init system"
    dependencies:
      runtime:
        - ${{package.name}}
        - tzdata
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/etc
          ln -s /usr/lib/systemd/systemd ${{targets.subpkgdir}}/init
          ln -sf /usr/share/zoneinfo/UTC ${{targets.subpkgdir}}/etc/localtime

update:
  enabled: true
  github:
    identifier: systemd/systemd
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - build-base
        - systemd-dev
        - libsystemd
  pipeline:
    - name: "Check systemctl version"
      runs: |
        systemctl --version
    - name: "Verify key binaries"
      runs: |
        systemctl --version
        systemd-analyze --version
        udevadm --version
        systemd-detect-virt --version
    - name: "Check libsystemd"
      runs: |
        ldconfig -p | grep libsystemd.so
        echo '#include <systemd/sd-bus.h>
        int main() { sd_bus *bus; return sd_bus_default_system(&bus); }' > test.c
        cc test.c -lsystemd -o test_systemd
        rm test.c test_systemd
