#nolint:valid-pipeline-git-checkout-tag
package:
  name: tclap
  version: 1.4
  epoch: 0
  description: "Templatized command-line argument parser for C++"
  copyright:
    - license: LicenseRef-tclap
      license-path: COPYING

environment:
  contents:
    packages:
      - build-base
      - busybox
      - python3

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.code.sf.net/p/tclap/code
      branch: ${{package.version}}
      expected-commit: 61cfae16ceba4cadc3d74439fa1e9fd4fce16bc9

  - uses: patch
    with:
      patches: no-docs.patch

  - uses: cmake/configure
    with:
      opts: -DBUILD_DOC=OFF

  - uses: cmake/build

  - uses: cmake/install

update:
  enabled: true
  git: {}
