package:
  name: tempo
  version: 2.5.0
  epoch: 6
  description: Grafana Tempo is a high volume, minimal dependency distributed tracing backend.
  copyright:
    - license: AGPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 46dad34116020a57b16410e020b56111ff357864
      repository: https://github.com/grafana/tempo
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: go.opentelemetry.io/collector/config/configgrpc@v0.102.1 go.opentelemetry.io/collector/config/confighttp@v0.102.0 go.opentelemetry.io/collector/receiver/otlpreceiver@v0.102.1 go.opentelemetry.io/collector/processor@v0.102.1 go.opentelemetry.io/collector/otelcol@v0.102.1 go.opentelemetry.io/collector/exporter/otlpexporter@v0.102.1 github.com/open-telemetry/opentelemetry-collector-contrib/receiver/opencensusreceiver@v0.102.0 github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver@v0.102.0 github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver@v0.102.0 github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver@v0.102.0 github.com/open-telemetry/opentelemetry-collector-contrib/exporter/zipkinexporter@v0.102.0 github.com/mostynb/go-grpc-compression@v1.2.3 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 google.golang.org/grpc@v1.64.1

  - uses: patch
    with:
      patches: opentelemetry.patch

  - runs: |
      go mod vendor
      make ${{package.name}}
      install -Dm755 bin/linux/${{package.name}}-$(go env GOARCH) ${{targets.destdir}}/usr/bin/${{package.name}}

  - uses: strip

data:
  - name: components
    items:
      query: query
      vulture: vulture
      cli: cli

subpackages:
  - range: components
    name: "${{package.name}}-${{range.key}}"
    pipeline:
      - runs: |
          make ${{package.name}}-${{range.key}}
          install -Dm755 bin/linux/${{package.name}}-${{range.key}}-$(go env GOARCH) ${{targets.subpkgdir}}/usr/bin/${{package.name}}-${{range.key}}
      - uses: strip

update:
  enabled: true
  github:
    identifier: grafana/tempo
    strip-prefix: v
    tag-filter: v

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - name: Smoke test for Tempo binary
      runs: |
        tempo --version
    - name: Test Tempo server start
      runs: |
        # Create a simple tempo.yaml config file
        cat <<EOF > tempo.yaml
        auth_enabled: false
        server:
          http_listen_port: 3200
        distributor:
          receivers:
            jaeger:
              protocols:
                thrift_compact:
        ingester:
          trace_idle_period: 10s
          max_block_bytes: 1048576
        storage:
          trace:
            backend: local
            local:
              path: /tmp/tempo/traces
        EOF

        tempo start -config.file=tempo.yaml &

        attempts=0
        until curl -f http://localhost:3200/ready || [ $attempts -eq 5 ]; do
          sleep 10
          attempts=$((attempts+1))
        done
        if [ $attempts -eq 5 ]; then exit 1; fi
