package:
  name: tfsec
  version: 1.28.10
  epoch: 2
  description: Security scanner for your Terraform code
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4476b18b3c222da05b2a44c797bad6b57da1f0d7
      repository: https://github.com/aquasecurity/tfsec
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/open-policy-agent/opa@v0.68.0

  - uses: go/build
    with:
      packages: ./cmd/tfsec
      output: tfsec
      ldflags: -X github.com/aquasecurity/tfsec/version.Version=v${{package.version}} -s -w -extldflags '-fno-PIC -static'

  - uses: go/build
    with:
      packages: ./cmd/tfsec-checkgen
      output: tfsec-checkgen
      ldflags: -X github.com/aquasecurity/tfsec/version.Version=v${{package.version}} -s -w -extldflags '-fno-PIC -static'

  - uses: strip

update:
  enabled: true
  github:
    identifier: aquasecurity/tfsec
    use-tag: true
    strip-prefix: v

test:
  pipeline:
    - runs: |
        tfsec --version
        tfsec --version | grep v${{package.version}}
