package:
  name: tigera-operator-1.35
  version: 1.35.1
  epoch: 0
  description: Kubernetes operator for installing Calico and Calico Enterprise
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - tigera-operator=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tigera/operator
      tag: v${{package.version}}
      expected-commit: 43944ed42ece2e3e69fc9f2a2aa29da8d8f83483

  - runs: |
      PACKAGE_NAME=github.com/tigera/operator
      ARCH=$(go env GOARCH)
      BINDIR=build/_output/bin
      GIT_VERSION=$(git describe --tags --dirty --always --abbrev=12)
      CGO_ENABLED=0

      echo "Building operator for ${ARCH} with CGO_ENABLED=${CGO_ENABLED} GOEXPERIMENT=${GOEXPERIMENT} TAGS=${TAGS}"
      GOEXPERIMENT=${GOEXPERIMENT} GO111MODULE=on CGO_ENABLED=${CGO_ENABLED} go build -buildvcs=false -v -o ${BINDIR}/operator-${ARCH} -tags "${TAGS}" -ldflags "-X ${PACKAGE_NAME}/version.VERSION=${GIT_VERSION} -w" ./main.go
      install -Dm755 build/_output/bin/operator-$(go env GOARCH) "${{targets.destdir}}"/usr/bin/operator

  - uses: strip

update:
  enabled: true
  github:
    identifier: tigera/operator
    use-tag: true
    strip-prefix: v
    tag-filter: v1.35.

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        operator --version
