package:
  name: trillian
  version: 1.6.1
  epoch: 1
  description: Merkle tree implementation used in Sigstore
  copyright:
    - license: Apache-2.0
  checks:
    disabled:
      - empty

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/google/trillian
      tag: v${{package.version}}
      expected-commit: 68ab90ccb3406f22e1040b9e3d822845c063bb96

subpackages:
  - name: ${{package.name}}-logserver
    pipeline:
      - uses: go/build
        with:
          modroot: .
          packages: ./cmd/trillian_log_server
          output: trillian_log_server
      - uses: strip

  - name: ${{package.name}}-logsigner
    pipeline:
      - uses: go/build
        with:
          modroot: .
          packages: ./cmd/trillian_log_signer
          output: trillian_log_signer
      - uses: strip

update:
  enabled: true
  github:
    identifier: google/trillian
    strip-prefix: v
