package:
  name: trust-manager
  version: 0.12.0
  epoch: 1
  description: trust-manager is an operator for distributing trust bundles across a Kubernetes cluster.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - docker
      - go
      - rsync
      - wolfi-baselayout

pipeline:
  # We can't use go/install because this requires specific ldflags to set the version
  - uses: git-checkout
    with:
      repository: https://github.com/cert-manager/trust-manager
      tag: v${{package.version}}
      expected-commit: db4471f813dd7752cf5d9cdd2bc8bbf2c9834a44
      destination: trust-manager

  - runs: |
      cd trust-manager
      mkdir ./bin
      go build -o ./bin/trust-manager ./cmd/trust-manager
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 ./bin/trust-manager ${{targets.destdir}}/usr/bin/trust-manager

  - uses: strip

update:
  enabled: true
  github:
    identifier: cert-manager/trust-manager
    strip-prefix: v
    use-tag: true
    tag-filter: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        trust-manager --help
