package:
  name: tzdata
  version: 2024b
  epoch: 0
  description: "Timezone data provided by IANA"
  copyright:
    - license: CC-PDDC

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - tzutils
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6903dde39ed637adaafc352c4b6993739253f058
      repository: https://github.com/eggert/tz
      tag: ${{package.version}}

  - runs: |
      make cc="${CC:-gcc}" CFLAGS="$CFLAGS -DHAVE_STDINT_H=1" TZDIR="/usr/share/zoneinfo"

  - runs: |
      _timezones="africa antarctica asia australasia europe northamerica southamerica etcetera backward factory"

      zic -b fat -y ./yearistype -d "${{targets.destdir}}"/usr/share/zoneinfo $_timezones
      zic -b fat -y ./yearistype -d "${{targets.destdir}}"/usr/share/zoneinfo/right -L leapseconds $_timezones
      zic -b fat -y ./yearistype -d "${{targets.destdir}}"/usr/share/zoneinfo -p America/New_York

      install -m444 -t "${{targets.destdir}}"/usr/share/zoneinfo iso3166.tab zone1970.tab zone.tab
      install -Dm644 leap-seconds.list "${{targets.destdir}}"/usr/share/zoneinfo

update:
  enabled: true
  github:
    identifier: eggert/tz
    use-tag: true
