package:
  name: unbound
  version: 1.21.0
  epoch: 0
  description: "Unbound is a validating, recursive, and caching DNS resolver."
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - expat-dev
      - flex
      - libevent-dev
      - libsodium-dev
      - openssl-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/NLnetLabs/unbound
      expected-commit: 79e4c578518886a32475cfbb0de383ff3a905033
      tag: release-${{package.version}}

  - uses: autoconf/configure
    with:
      opts: |
        --with-libevent \
        --with-expat \
        --enable-dnscrypt

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: unbound-doc
    description: unbound manpages
    pipeline:
      - uses: split/manpages

  - name: "unbound-dev"
    description: "headers for unbound"
    pipeline:
      - uses: split/dev

  - name: "unbound-libs"
    description: "libraries for unbound"
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/lib*.so.* ${{targets.subpkgdir}}/usr/lib

update:
  enabled: true
  github:
    identifier: NLnetLabs/unbound
    strip-prefix: release-
    use-tag: true
    tag-filter: release-

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        unbound -V
        unbound-host version
