package:
  name: varnish
  version: 7.6.0
  epoch: 1
  description: "Varnish Cache is a web application accelerator also known as a caching HTTP reverse proxy"
  copyright:
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - libunwind-dev
      - m4
      - openssf-compiler-options
      - pcre2-dev
      - pkgconf
      - pkgconf-dev
      - py3-docutils
      - py3-sphinx
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/varnishcache/varnish-cache
      tag: varnish-${{package.version}}
      expected-commit: ed1243ca162a7b1d975bc0332f0d66d33f0bc78e

  - runs: autoreconf -vif

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "varnish-dev"
    description: "varnish dev"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: varnishcache/varnish-cache
    strip-prefix: varnish-
    use-tag: true
    tag-filter: varnish-

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        varnishadm -h
        varnishhist -h
        varnishlog -h
        varnishncsa -h
        varnishstat --help
        varnishstat_help_gen --version
        varnishtop -h
        varnishd -V
