package:
  name: vendir
  version: 0.42.0
  epoch: 0
  description: Easy way to vendor portions of git repos, github releases, helm charts, docker image contents, etc. declaratively
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 09ab9ab732b18cfaa735ab9b5b74be82a0f4d5ba
      repository: https://github.com/carvel-dev/vendir
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/vendir
      output: vendir
      ldflags: -X carvel.dev/vendir/pkg/vendir/version.Version=v${{package.version}}

update:
  enabled: true
  github:
    identifier: carvel-dev/vendir
    strip-prefix: v

test:
  pipeline:
    - name: version check
      runs: |
        vendir version | grep ${{package.version}}
    - uses: git-checkout
      with:
        expected-commit: 09ab9ab732b18cfaa735ab9b5b74be82a0f4d5ba
        repository: https://github.com/carvel-dev/vendir
        tag: v${{package.version}}
    - name: run sync
      runs: |
        cd examples/inline
        vendir sync
