package:
  name: vulkan-headers
  version: 1.3.296
  epoch: 0
  description: Vulkan header files and API registry
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - ninja-build # samurai doesn't provide a new enough version
      - openssf-compiler-options

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/KhronosGroup/Vulkan-Headers
      tag: v${{package.version}}
      expected-commit: 29f979ee5aa58b7b005f805ea8df7a855c39ff37

  - runs: |
      cmake -G Ninja -B build \
        -DCMAKE_MAKE_PROGRAM="/usr/lib/ninja-build/bin/ninja" \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake  --install build

  - uses: strip

update:
  enabled: true
  github:
    identifier: KhronosGroup/Vulkan-Headers
    strip-prefix: v
    use-tag: true
    tag-filter: v1
