#nolint:git-checkout-must-use-github-updates,valid-pipeline-git-checkout-tag
package:
  name: w3m
  version: 0.5.3.20230718
  epoch: 3
  description: text-based web & gopher browser, as well as pager
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - perl

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - gc-dev
      - imlib2-dev
      - linux-headers
      - ncurses-dev
      - openssf-compiler-options
      - openssl-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tats/w3m
      expected-commit: ee66aabc3987000c2851bce6ade4dcbb0b037d81

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: w3m-doc
    pipeline:
      - uses: split/manpages
    description: w3m manpages

update:
  enabled: true
  release-monitor:
    identifier: 5115

# Basic test, requires newtork access, to dump https://example.com to stdout
test:
  pipeline:
    - runs: |
        w3m -dump https://example.com
