package:
  name: wave
  version: 0.9.0
  epoch: 2
  description: Kubernetes configuration tracking controller
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wave-k8s/wave
      tag: v${{package.version}}
      expected-commit: 6d5c4bdb486f8e962d631083c79da0d04eaf63cc

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0

  - uses: go/build
    with:
      packages: ./cmd/manager
      output: wave
      ldflags: -X main.VERSION=${{package.version}}

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - "wave-"
  github:
    identifier: wave-k8s/wave
    strip-prefix: v

test:
  pipeline:
    - runs: wave --version
    - runs: wave 2>&1 | grep -qi "try setting KUBERNETES_MASTER environment variable"
