package:
  name: websockify
  version: 0.12.0
  epoch: 2
  description: WebSockets support for any application/server
  copyright:
    - license: LGPL-3.0-or-later
  dependencies:
    runtime:
      - numpy
      - py3-jwcrypto
      - py3-requests
      - py3-simplejson

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssf-compiler-options
      - py3-gpep517
      - py3-setuptools
      - py3-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/novnc/websockify
      tag: v${{package.version}}
      expected-commit: 99f83ca08390dc876b1b3580c210abea5b9f4edd

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

test:
  pipeline:
    - uses: python/import
      with:
        imports: |
          import websockify

update:
  enabled: true
  github:
    identifier: novnc/websockify
    strip-prefix: v
