# source is git.zx2c4.com so we can't use github updates to get expected commit
# let's still auto create the PR, it will fail as expected commit will be wrong
# however it will be easy to fix
#nolint:git-checkout-must-use-github-updates
package:
  name: wireguard-tools
  version: 1.0.20210914
  epoch: 0
  description: "Next generation secure network tunnel: userspace tools"
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - iproute2
      - libmnl-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.zx2c4.com/wireguard-tools
      tag: v${{package.version}}
      expected-commit: 3ba6527130c502144e7388b900138bca6260f4e8

  - uses: autoconf/make-install
    with:
      dir: src
      opts: |
        WITH_BASHCOMPLETION=no \
        WITH_WGQUICK=no \
        WITH_SYSTEMDUNITS=no

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/share/doc/${{package.name}}
      cp -rf contrib "${{targets.destdir}}"/usr/share/doc/${{package.name}}/

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 62381

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        wg --version
