package:
  name: xcaddy
  version: 0.4.2
  epoch: 3
  description: Build Caddy with plugins
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: d7277dbc5dad26d22ea8e77fba92943c508c9b0f
      repository: https://github.com/caddyserver/xcaddy
      tag: v${{package.version}}

  - uses: go/build
    with:
      output: xcaddy
      packages: ./cmd/xcaddy

  - uses: strip

update:
  enabled: true
  github:
    identifier: caddyserver/xcaddy
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - busybox
        - go
  pipeline:
    - runs: |
        export GOPATH=/tmp
        export GOCACHE=/tmp
        xcaddy build \
          --with github.com/caddyserver/ntlm-transport
        ./caddy -v
