package:
  name: xcb-proto
  version: 1.17.0
  epoch: 1
  description: XML-XCB protocol descriptions
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssf-compiler-options
      - python3

pipeline:
  - uses: fetch
    with:
      expected-sha256: 2c1bacd2110f4799f74de6ebb714b94cf6f80fb112316b1219480fd22562148c
      uri: https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-${{package.version}}.tar.xz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: true
  release-monitor:
    identifier: 13646
