package:
  name: xh
  version: 0.22.2
  epoch: 3
  description: Friendly and fast tool for sending HTTP requests.
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cargo-auditable
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ducaale/xh
      tag: v${{package.version}}
      expected-commit: c0f46a49995f8096b33d6351473e6134446b3038

  - uses: rust/cargobump

  - runs: |
      cargo auditable build --locked --release
      install -Dm755 target/release/xh "${{targets.destdir}}"/usr/bin/xh

  - uses: strip

update:
  enabled: true
  github:
    identifier: ducaale/xh
    strip-prefix: v

test:
  pipeline:
    - runs: |
        xh --version | grep ${{package.version}}
    - runs: |
        xh GET https://example.com
