package:
  name: xprop
  version: 1.2.7
  epoch: 1
  description: Property displayer for X
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - libx11-dev
      - openssf-compiler-options
      - util-macros

pipeline:
  - uses: fetch
    with:
      expected-sha256: 4436e3148bb91a162406230d9f736a49ca8b50b74790015dc15d78d6ce8e825f
      uri: https://www.x.org/archive/individual/app/xprop-${{package.version}}.tar.xz

  - uses: autoconf/configure

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: xprop-doc
    description: xprop documentation
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  release-monitor:
    identifier: 14958
