package:
  name: yace
  version: 0.61.2
  epoch: 1
  description: Prometheus exporter for AWS CloudWatch.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nerdswords/yet-another-cloudwatch-exporter
      tag: v${{package.version}}
      expected-commit: 43c09fe4ed3e93449121765462433ed924d679a2

  - uses: go/build
    with:
      packages: ./cmd/yace
      ldflags: -s -w -buildid= -X main.version=${{package.version}}
      output: yace

  - uses: strip

update:
  enabled: true
  github:
    identifier: nerdswords/yet-another-cloudwatch-exporter
    strip-prefix: v

test:
  pipeline:
    - name: Verify yace installation
      runs: |
        yace version
