package:
  name: yq
  version: 4.44.3
  epoch: 1
  description: "yq is a portable command-line YAML, JSON, XML, CSV and properties processor"
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mikefarah/yq
      tag: v${{package.version}}
      expected-commit: bbdd97482f2d439126582a59689eb1c855944955

  - uses: go/build
    with:
      packages: .
      output: yq

  - runs: |
      ${{targets.destdir}}/usr/bin/yq --version | grep "version v${{package.version}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: mikefarah/yq
    strip-prefix: v

test:
  pipeline:
    - name: Test yq eval command
      runs: |
        # Test setting a key-value pair in YAML
        result=$(yq eval --null-input --no-colors '.key = "cat"')
        [ "$result" = "key: cat" ]
    - name: Test yq eval with pipe input
      runs: |
        # Test extracting a key value from YAML
        result=$(echo "key: cat" | yq eval ".key" -)
        [ "$result" = "cat" ]
