package:
  name: ytt
  version: 0.50.0
  epoch: 1
  description: YAML templating tool that works on YAML structure instead of text
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b60ca0d4900a558b1fa71d744ee095316d9b84e1
      repository: https://github.com/carvel-dev/ytt
      tag: v${{package.version}}

  - uses: go/build
    with:
      packages: ./cmd/ytt
      output: ytt
      ldflags: -X github.com/vmware-tanzu/carvel-ytt/pkg/version.Version=v${{package.version}}

  - uses: strip

update:
  enabled: true
  github:
    identifier: carvel-dev/ytt
    strip-prefix: v

test:
  pipeline:
    - name: version check
      runs: ytt --version
    - name: simple YAML templating from stdin
      runs: |
        echo "name: world" | ytt -f -
    - name: simple YAML templating from file
      runs: |
        cat <<EOF > test.yaml
        name: world
        # comments are ignored in the output
        demo_list:
        - hello
        - world
        demo_map:
          demo_key: demo_value
        EOF
        ytt -f test.yaml
