package:
  name: zstd
  version: 1.5.6
  epoch: 5
  description: "the Zstandard compression algorithm"
  copyright:
    - license: BSD-2-Clause AND GPL-2.0-only

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake-bootstrap
      - grep
      - openssf-compiler-options
      - samurai
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 794ea1b0afca0f020f4e57b6732332231fb23c70
      repository: https://github.com/facebook/zstd
      tag: v${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -S build/cmake

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: "zstd-doc"
    description: "zstd documentation"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

  - name: "zstd-static"
    description: "zstd static libraries"
    pipeline:
      - uses: split/static

  - name: "zstd-dev"
    description: "zstd development headers"
    dependencies:
      provides:
        - zstd-cmake=${{package.full-version}}
    pipeline:
      - uses: split/dev

  - name: "libzstd1"
    description: "libzstd runtime libraries"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libzstd.so.* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  github:
    identifier: facebook/zstd
    strip-prefix: v
    tag-filter: v

test:
  environment:
    contents:
      packages:
        - pkgconf
        - zstd-dev
  pipeline:
    - runs: |
        pkg-config --libs libzstd | grep /usr/lib
